### ISSUE TITLE
[IDEA] Dragon-specific magic providing Haste-like effects for their respective tool equivalent

### ISSUE THREAD

**Issue by thebloxxer11** [DragonSurvivalTeam/DragonSurvival#100]
Description of Idea:
Some kind of Active Magic skill (and Beacon effect) that boosts speed when mining, digging, or cutting down trees for Cave, Sea, and Forest dragon types respectively for a short period of time.

Some name suggestions:
Rock Shatter - Cave Dragon mining boost
Sand Excavate - Sea Dragon digging boost
Wood Splinter - Forest Dragon chopping boost

Duration tiering (adjust for balancing): 30s/60s/120s/180s

Source of Idea: Cave Beacon of Fire doesn't have Haste by default, and need to clear out a cavern.

Also, outside of this, I'd suggest making two formats for these: Ideas/Suggestions and Bug/Crash reports.

**Comment by BlackAures1** [comment]
Please do not use the bug report section for suggestions. Use the discord.
