### ISSUE TITLE
isnt working on aternos

### ISSUE THREAD

**Issue by forkinmyfoot** [DragonSurvivalTeam/DragonSurvival#103]
^

**Comment by ravewyvern** [comment]
did you install geckolib for forge and not fabric

**Comment by BlackAures1** [comment]
Considering that you didn't even bother to write a proper description of the "problem", which is not there, and think with your head a little bit - I'm closing this.

**Comment by forkinmyfoot** [comment]
Man shut the fuck up ur toxic dont take ur bad day on me
