### ISSUE TITLE
[Bug]: Boots not showing 

### ISSUE THREAD

**Issue by LatentDesire** [DragonSurvivalTeam/DragonSurvival#107]
### ■ Your Discord ID

LatentDesire#2799

### ■ Dragon Survival version

DragonSurvival_TreasureUpdate-1.16.5-0.9.2

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Wearing boots do not show in the boots slot. They are still there. Seems like a graphical bug only.

### ■ To Reproduce

Put on boots.

### ■ Expected behavior

Being able to see the boots and durability in the armor slot.

**Comment by BlackAures1** [comment]
What kind of boots? Everything works for us.
