### ISSUE TITLE
[Bug]: Predator Stars replacing blocks and making it so we cant replace blocks

### ISSUE THREAD

**Issue by Robomnz** [DragonSurvivalTeam/DragonSurvival#113]
### ■ Your Discord ID

Blue (Robomnz)#2472

### ■ Dragon Survival version

Dragon Survival 1.16.5-0.9.2

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

we built an enderman farm however when predators fall and die they delete the carpet at the bottom and replace it with the predator star, when we get rid of the star however we cannot replace the carpets! i wish that the star just wouldnt spawn if theres carpet/slabs where it dies instead of replacing blocks and making it so we cant replace what the star broke.

### ■ To Reproduce

Follow this farm tutorial and make the enderman farm

https://www.youtube.com/watch?v=nh8voJScSbw

ours looked like this
![image](https://user-images.githubusercontent.com/34904608/156943880-511203d9-d958-4fbf-8584-7a53ce1f95e3.png)

occasionally predators will fall down and die deleting the carpet and making it so you cannot replace the carpet 
![image](https://user-images.githubusercontent.com/34904608/156943905-e94e5c50-61da-46e1-b6c5-f75070b5f04f.png)

### ■ Expected behavior

the predator stars wouldnt spawn at all due to there being carpet/slabs there and also when we do remove the star we would be able to replace the blocks the star broke

**Comment by BlackAures1** [comment]
Forest beacon of Magic removes the spawn for magical predators.https://dragons-survival.fandom.com/wiki/Dragon_Beacons
