### ISSUE TITLE
[1.16.5 Forge Bug]: Vanilla Food Pantry Incompatability

### ISSUE THREAD

**Issue by KateReller** [DragonSurvivalTeam/DragonSurvival#115]
### ■ Your Discord ID

Skippy#6399

### ■ Dragon Survival version

DragonSurvival_TreasureUpdate-1.16.5-0.9.2.jar

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Usually yes, but this time no.

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

The foods in the mod [Vanilla Food Pantry](https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod) will restore hunger for any dragon type regardless if it's not in their `server.food.list`.

### ■ To Reproduce

1. Become a dragon (like a cave dragon since they only eat charred food and coals).
2. Eat any food from Vanilla Food Pantry.
3. Watch as it restores hunger normally.

### ■ Expected behavior

The food should give the player the hunger debuff since the food is not on the dragon's `server.food.list`.

**Comment by BlackAures1** [comment]
Sounds like a third-party mod problem, not ours. If they decided to get creative and make some special food code, we can't help.
