### ISSUE TITLE
[Bug]: Mowzies mobs Axe of 1000 metals in DS Young mod

### ISSUE THREAD

**Issue by RagnarokBazil** [DragonSurvivalTeam/DragonSurvival#119]
### ■ Your Discord ID

𝓛𝓸𝓻𝓭 𝓑𝓪𝔃𝓲𝓵 𝓖𝓻𝓲𝓶𝓼𝓽𝓻𝓲𝓭𝓮#0666

### ■ Dragon Survival version

Mowzies mobs Axe of 1000 metals makes you turn human when you use right click and shift rightclick.. Anyway to fix this when in dragon form..? This is your Modpack btw.. Dragon Survival Young mod

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

When you rightclick with the Axe of 1000 metals you turn human 
when you shift rightclick with the Axe of 1000 metals you turn human

### ■ To Reproduce

When you rightclick with the Axe of 1000 metals you turn human 
when you shift rightclick with the Axe of 1000 metals you turn human

### ■ Expected behavior

When you rightclick with the Axe of 1000 metals you turn human 
when you shift rightclick with the Axe of 1000 metals you turn human

**Comment by naanahstnil** [comment]
as a note; you turn human just because hitting with the axe reproduces an animation with the human model, after the animation the model returns to the dragon and you do not lose any progress
must be easy to fix, as it's just the animation model overlaping with the dragon model

**Comment by RagnarokBazil** [comment]
Yeah but Everyone can see it..

**Comment by BlackAures1** [comment]
Send the full id of this item. I'll add it to the list of banned dragon items.

**Comment by RagnarokBazil** [comment]
> Send the full id of this item. I'll add it to the list of banned dragon items.

Or just fix the model bug in dragon form.. I love and adore the axe it fits the whole dragon Smash strength..

**Comment by Horeak** [comment]
This is a issue for the author of Mowzies Mobs to fix, they are overwriting the model to do that animation so that is not something i am going to fix.

**Comment by RagnarokBazil** [comment]
> This is a issue for the author of Mowzies Mobs to fix, they are overwriting the model to do that animation so that is not something i am going to fix.

Well could there be dragon based weapons that are like the axe?

**Comment by RagnarokBazil** [comment]
Ill just ask Mowzie to get it fixed.
