### ISSUE TITLE
[1.16.5 Forge Bug]:  Tetra mod incompatibility

### ISSUE THREAD

**Issue by SaltyyCoffee** [DragonSurvivalTeam/DragonSurvival#120]
### ■ Your Discord ID

SaltyyCoffee#6310

### ■ Dragon Survival version

DragonSurvival_TreasureUpdate-1.16.5-0.9.2.jar

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

Tetra Tools cannot go into dragon inventory. 

### ■ To Reproduce

Make a tetra tool with the tetra Mod, then attempt to put it into the Dragon Inventory, it doesn't go in.

**Comment by BlackAures1** [comment]
In inventory or in claws and teeth? If in claws and teeth, it's a matter of how Tetra Tools registers its instruments and whether the game considers them instruments.
