### ISSUE TITLE
[Bug]: Charged debuff lasting on players too long

### ISSUE THREAD

**Issue by RagnarokBazil** [DragonSurvivalTeam/DragonSurvival#121]
### ■ Your Discord ID

𝓛𝓸𝓻𝓭 𝓑𝓪𝔃𝓲𝓵 𝓖𝓻𝓲𝓶𝓼𝓽𝓻𝓲𝓭𝓮#0666

### ■ Dragon Survival version

treasure update

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

It lasts too long.. it damages armor too much.. in full armor it takes away 25% from 1 30 second long effect.. and if the mob is near by being zapped refreshes the timer on players even if far away.. Recommend that it don't refresh on players.. Full netherite armor just got instantly deleted >>

### ■ To Reproduce

Zap your bolt on someone.. anyone lol

### ■ Expected behavior

Zap your bolt on someone.. anyone lol

### ■ Crash Report

no crashes

**Comment by BlackAures1** [comment]
ust turn off the recochets in the config! chargedEffectMaxChain, chargedChainRange, chargedEffectDamage, chargedSpreadBlacklist
