### ISSUE TITLE
[Bug]: Dragonfruit needs higher version(?)

### ISSUE THREAD

**Issue by NotAPotter** [DragonSurvivalTeam/DragonSurvival#123]
### ■ Your Discord ID

PonyPon#2838

### ■ Dragon Survival version

Dragon Editor Update

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

In trying to use the editor update, upon starting up, the game said that dragonfruit needed an updated version of dragonsurvival to function, yet curiously didn't tell me what version i was using.

### ■ To Reproduce

Run the latest version of dragonsurvial and dragonfruit with all appropriate dependencies.

### ■ Expected behavior

The mods would all be loaded and the game would function.

**Comment by BlackAures1** [comment]
dragonfruit has long been unnecessary for the display of food indicators.

**Comment by NotAPotter** [comment]
Ah, my mistake.
