### ISSUE TITLE
[Bug]: returning from the end wiping your dragon status and reverting you to human

### ISSUE THREAD

**Issue by joeyjumper94** [DragonSurvivalTeam/DragonSurvival#129]
### ■ Your Discord ID

joey_#3699

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.0.jar.jar

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Hopping through the return portal in the end or the void after entering the end will wipe your dragon selection and revert you to being human

### ■ To Reproduce

give yourself a dragon altar and turn into a dragon of any kind
go to the end
return by jumping into the void( you can just run **execute in the_end run tp @s 0 0 0**)

### ■ Expected behavior

i expect to be a dragon when appearing at my spawn position

### ■ Crash Report

no crashing

**Comment by joeyjumper94** [comment]
after doing a test with the version before the latest, i can confirm that this bug currently affects only the latest version

**Comment by BlackAures1** [comment]
![image](https://user-images.githubusercontent.com/43911230/160499934-6f1a800c-fece-4786-9598-350e8257ce7e.png)
this will be fixed in the next update.
