### ISSUE TITLE
[Compatibility]: Picking up Items in Survival using modpack - Crash

### ISSUE THREAD

**Issue by Skyglazer** [DragonSurvivalTeam/DragonSurvival#131]
### ■ Your Discord ID

Skygazer#5309

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.1

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

Attempting to manually update the Dragon Survival mod in the Young Dragon modpack without touching the other mods results in a strange behavior- when in Survival Mode, if any item is picked up by a dragon player, their game will immediately crash, in both singleplayer and multiplayer. Playing with only Dragon Survival and Geckolib did not encounter this problem.

### ■ To Reproduce

1. Install Young Dragon modpack.
2. Update Dragon Survival to latest version via CurseForge.
3. Load into a singleplayer world or server.
4. Become a dragon.
5. Try to pick up any item (vanilla or modded), crash.

### ■ Crash Report

[crash-2022-03-29_20.17.03-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8375841/crash-2022-03-29_20.17.03-client.txt)

**Comment by Drulikar** [comment]
At least for the moment, this appears to be a mod conflict between the DragonEditor versions of DragonSurvival and these two mods:

- mcw-bridges-2.0.1-mc1.16.5
- mowziesmobs-1.5.22

I slowly came to this conclusion just by mass disabling mods and testing until crash behavor changed. Updating the forge version had no effect, nor did updating any of the other mods. Try disabling those two mods for now.
