### ISSUE TITLE
[Compatibility]: Generating elder dragon dust and bones instead quark items

### ISSUE THREAD

**Issue by Bergimus** [DragonSurvivalTeam/DragonSurvival#134]
### ■ Your Discord ID

Bergim#7114

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.1

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

Instead of generating in chests some items from quark, there is elder dragon dust and elder dragon bones from dragon survival

### ■ To Reproduce

1. Install mods:
AutoRegLib-1.6-49
DragonSurvival_DragonEditor-1.16.5-0.10.1
geckolib-forge-1.16.5-3.0.65
Quark-r2.4-322

2. Locate and go to the vanilla stronghold

3. Find a library where items from quark appear most often (works on other structures too)

4. Open chest being human or dragon

5. See.

**Comment by BlackAures1** [comment]
What exactly is the problem? These bones and dust are added to the vanilla treasure house loot. If the chest from some mod generates loot according to the vanilla loot table, there will be bones and dust. This is not a bug. If you need to remove any loot bones and dust in the chests just delete the files in _main\resources\data\minecraft\loot_tables\chests_
