### ISSUE TITLE
[1.16.5 Forge Bug]: Players that reconnect over LAN appear as Human for that client

### ISSUE THREAD

**Issue by Drulikar** [DragonSurvivalTeam/DragonSurvival#140]
### ■ Your Discord ID

Drathek#9503

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.1 (and latest from source as of commit e3dcb9da28153b84f6c2bb860216c93fb561e827)

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Playing with friends over a local network (Hamachi, etc.)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

When opening a single player game to lan, any reconnecting player that was a dragon before will appear to the host as a dragon, but as a human for that player's client. If they interact with the altar again to become the same dragon type again, their abilities screen will show them with all newborn ability levels. However, if they gain six xp level to increment a skill they previously had increased, it will increment their old value. See reproduction steps for clarification.

NOTE: Does not appear to affect dedicated servers; ONLY LAN (even if LAN port is same as it was previously).

### ■ To Reproduce

1. Start a new survival game w/ cheats in single player w/ gecko and dragon survival.
2. Open to LAN (survival no cheats).
3. Connect a friend via LAN.
4. Friend interacts with dragon altar to become a forest dragon.
5. (Optional) Friend earns xp enough for 6 levels (using bottle o enchanting).
6. (Optional) Friend increments mana passive skill 1 level.
7. Friend disconnects
8. Friend reconnects as human (host sees them as forest dragon).
9. (Optional) Friend interacts with dragon altar to become a forest dragon again.
10. (Optional) Friend earns xp enough for 6 levels (using bottle o enchanting) again.
11. (Optional) Friend increments mana passive skill 1 level but now it is at level 2 instead of 1.

### ■ Expected behavior

Players that reconnect to an existing game over LAN can continue to play as dragons w/o re-interacting with altar and more or less starting fresh (even though their old stats exist and will be incremented for cheaper than they should be).

**Comment by Drulikar** [comment]
Also worth mentioning: the reconnecting player always loses their items in claw tool slots (but I didn't confirm the behavior if re-slotting in a tool in a slot that used to have a tool).

**Comment by BlackAures1** [comment]
Is this problem still present or has it been fixed?

**Comment by Drulikar** [comment]
> Is this problem still present or has it been fixed?

I have not experienced the problem in either version DragonSurvival_DragonEditor-1.16.5-0.10.3_fix.jar or DragonSurvival_DragonEditor-1.16.5-0.10.4.jar. If it does exist again for some, it has different reproduction steps or other conditions.
