### ISSUE TITLE
[1.16.5 and 1.18.2 Forge Bug]: Dannys Expansion crash in altar

### ISSUE THREAD

**Issue by Crykenpie** [DragonSurvivalTeam/DragonSurvival#141]
### ■ Your Discord ID

Crykenpie#7779

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.3_fix

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

My game crashes while im using the altar to switch dragon types on the altar, either when choosing a dragon or while moving the mouse cursor over the dragon types/choices. Says in the report there is an issue with rendering the player model, unless i read it wrong. 
(modpack this is used in is Medieval Minecraft)

### ■ To Reproduce

Use the altar and either move mouse over the different choices or choosing a dragon has both proven as ways to do it, though not everytime.

### ■ Expected behavior

I expect the game to not crash.

### ■ Crash Report

[crash-2022-04-08_21.08.16-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8455979/crash-2022-04-08_21.08.16-client.txt)

**Comment by BlackAures1** [comment]
Try turning off this mod: dannys_expansion
