### ISSUE TITLE
Crash with Nest Block

### ISSUE THREAD

**Issue by Jorgee9001** [DragonSurvivalTeam/DragonSurvival#15]
1.16.5; Specifically, friend used a Growth Heart inside the nest as a sea dragon, and a crash resulted.

[crash-2021-05-08_09.44.27-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/6448234/crash-2021-05-08_09.44.27-client.txt)

**Comment by AlexiyOrlov** [comment]
Should be fixed in the new version
