### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by AuroraNW** [DragonSurvivalTeam/DragonSurvival#154]
### ■ Your Discord ID

AuroranKingslayer#5700

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.0.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Sea dragons in character editor have an error that gives both of their eyes a different starting color. Changing the color value on the slider will alter the color value of both eyes, but you can never give the eyes the same color. 

(For example, one eye is red and the other is orange. If I slide down towards cool colors, the red eye will turn green and the orange one will turn blue.) 

### ■ To Reproduce

This happens every time I open the editor to alter the sea dragon newborn specifically. All other color regions and patterns work fine. Other dragon species work fine as well.

### ■ Expected behavior

I expected both eyes to have the same color.

### ■ Crash Report

N/A

**Comment by Horeak** [comment]
Not a bug, the sea dragon has different eye colors on all textures. Any changes for that should be directed to @BlackAures1

**Comment by BlackAures1** [comment]
Directed to me to direct them [here](https://bit.ly/3vwHC85)?
