### ISSUE TITLE
[1.16.5 Forge Bug]: Crashing after I trying enter the world i played before.

### ISSUE THREAD

**Issue by DIMAA1119** [DragonSurvivalTeam/DragonSurvival#156]
### ■ Your Discord ID

DIMAA1119#1415

### ■ Dragon Survival version

DragonSurvival_DragonEditorUpdate-0.10.4-server-1.16.5

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Usually yes, but this time no.

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Forge crashed when I was trying to enter a world I played before and I was flying across the ocean before exiting the world.

### ■ To Reproduce

This crash not repeatable.

### ■ Expected behavior

Game shouldn't crash when I trying to enter the world I played before.

### ■ Crash Report
                                                                                                                                                                               
[crash-2022-04-30_10.39.43-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8596563/crash-2022-04-30_10.39.43-client.txt)

**Comment by BlackAures1** [comment]
Your crash report is not loading

**Comment by Horeak** [comment]
Closing this as it is not DS related, best guess seems to be "fpsreducer" causing the issue
