### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by Alarah** [DragonSurvivalTeam/DragonSurvival#162]
### ■ Your Discord ID

Alarah#1625

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.3_beta

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Getting a crash when entering a certain portion of the world.  Crash report seems to indicate an error rendering the knight entity but I am not sure. It is a custom modpack from curse so it is likely something I have done in putting it together. This was on a fresh install and map generation, no upgrade in place of mods.

### ■ To Reproduce

Happens whenever i get near to the area. It is a mod pack running on a hosted server. I can compile an archive of the mods and save on request.

### ■ Expected behavior

To not crash

### ■ Crash Report

[crash-2022-05-10_01.36.39-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8664650/crash-2022-05-10_01.36.39-client.txt)
[crash-2022-05-10_01.32.28-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8664651/crash-2022-05-10_01.32.28-client.txt)
[crash-2022-05-10_01.09.07-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8664652/crash-2022-05-10_01.09.07-client.txt)

**Comment by Alarah** [comment]
It appears that it may be a conflict between Dragon Survival and Blue Skies (or it's dependency Structure Gel API). Removing those mods from the pack has prevented me from reproducing the error.

**Comment by CvoidWyvern** [comment]
Same issue in a pack we're in the process of making for a group

[crash-2022-05-28_16.17.51-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8792303/crash-2022-05-28_16.17.51-client.txt)
