### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by jaded353** [DragonSurvivalTeam/DragonSurvival#163]
### ■ Your Discord ID

jaded353#7468

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.3_beta.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

i attempted to start the game but it crashes before it even reaches the initial loading phase, displaying the error "org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError:", i have tested repeatedly, systematically removing the mods i have one by one, i saved dragon survival for last (as it was the one i was most wanting to work so i was desperately hoping it was not the issue) but alas, my testing showed that dragon survival was indeed the culprit, the game loaded fine with every other mod but this one (as i found when i tried using literally all the other mods with only dragon survival and geckolib removed)

### ■ To Reproduce

the issue reproduces itself every time i attempt to load the game with dragon survival installed (even the attempt or two in which i forgot geckolib so that being forgotten wasn't the issue)

### ■ Expected behavior

i expected the game to at least finish the initial loading phase before giving me an error log in the event i may have forgotten something one of the mods required (like how i initially forgot geckolib for dragon survival but added it on the third attempt hoping that was the reason it crashed before even loading)

### ■ Crash Report

[crash-2022-05-12_20.07.52-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8683384/crash-2022-05-12_20.07.52-client.txt)

**Comment by Horeak** [comment]
The log file you sent there indicates that geckolib is either missing or an incompatible version as it does not show up as loaded. So double check it is installed correctly and then send a new log if it still crashes

**Comment by jaded353** [comment]
well this is a bit embarrassing, i remember going to geckolib to download it on curseforge after i tested to see what mod was causing it not to start loading, but now that i go look, i couldn't find geckolib in either the mod folder or the storage folder i was putting things in while i tested, i was so sure i'd even moved it alongside dragon survival earlier, but upon redownloading geckolib and testing with it it works now, or at least it actually makes it to the initial loading phase, it's late at night so won't be testing beyond that for now, still not sure where it went from before, if it got deleted somehow or if i made a mistake and somehow tricked myself into thinking i'd downloaded it but hadn't or something but either way the issue i had is fixed now, so thank you for the help ^^
