### ISSUE TITLE
[1.18.2 Forge Bug]: Significant fps drops

### ISSUE THREAD

**Issue by Kosolaper** [DragonSurvivalTeam/DragonSurvival#164]
### ■ Your Discord ID

Kosolaper#9869

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.3_beta.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

While being any dragon, or looking on one, fps drops significantly, from 50 to 20. Been tested in singleplayer and lan server. But after my first death my dragon model disappeared for me, but not for my friend. While for me fps returned for normal, my friend still suffered from fps drop.

### ■ To Reproduce

1. Become any dragon.

### ■ Expected behavior

Expected no to little fps drops.

**Comment by Kosolaper** [comment]
After some testing (stripping all mods except ds and gecolib, deleting configs, creating new world) found that fps drop si still appearing.

**Comment by Kosolaper** [comment]
More testing, did tests on 1.16.5 latest version, fps drops is presented, but on smaller scale.

**Comment by Horeak** [comment]
I can't reproduce this atm so I need some more info.

What world type do you use? Any difference on different worlds? 
Which forge version? 
Which geckolib version?

What are the computer specs you are running it on?
How much ram is allocated?

**Comment by Kosolaper** [comment]
World type default. No settings chaged.
Forge 40.1.19
Geckolib 3.0.18

OS: Windows 10 Pro x64 (2004 build 19041)
Core: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Graphic card: NVIDIA GeForce GTX 1650, 4 GB
RAM: 8 GB
RAM used in game: 5048 MG

Using TLauncher.
