### ISSUE TITLE
I get this error when I try to start my game with the mod installed

### ISSUE THREAD

**Issue by fishofthecondom** [DragonSurvivalTeam/DragonSurvival#169]
### ■ Your Discord ID

Condom Fish#5369

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.4_beta

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

When I click 'start' in the launcher, it give me this error message:
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

### ■ To Reproduce

1. install mod 2. click 'start' in launcher

### ■ Expected behavior

I expect the game to start

### ■ Crash Report

[crash-2022-05-26_20.17.54-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8788077/crash-2022-05-26_20.17.54-client.txt)

**Comment by BlackAures1** [comment]
You didn't put Fabric on Forge, did you?

**Comment by fishofthecondom** [comment]
> You didn't put Fabric on Forge, did you?

No, I'm using the Curseforge app, so it automatically installs forge for me

**Comment by Horeak** [comment]
You didnt install geckolib3

**Comment by BlackAures1** [comment]
Send a screenshot of your mod folder.

**Comment by fishofthecondom** [comment]
> Send a screenshot of your mod folder.
![Capture](https://user-images.githubusercontent.com/106396173/170746676-9e276173-33d3-4554-8a04-a4e724345f95.PNG)

**Comment by BlackAures1** [comment]
You need the Forge version of Geckolib
https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3785773

**Comment by fishofthecondom** [comment]
> You need the Forge version of Geckolib https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3785773

that fixed it, thank you so much!
