### ISSUE TITLE
[1.16.5 Forge Bug]: If player inventory is full on death and a Corail Tombstone is made, any items equipped in dragon tool slots are lost.

### ISSUE THREAD

**Issue by SumaniPardia** [DragonSurvivalTeam/DragonSurvival#170]
### ■ Your Discord ID

Filnbirt#5146

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.6.jar.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

When using Corail Tombstone version 6.7.6 (although most likely affects all versions) for player graves and a player that is a dragon with a full inventory and tools in the dragon tool slots dies, the tombstone doesn't contain the dragon tool slot items, deleting them.

### ■ To Reproduce

1) Make a pack with both Dragon Survival and Corail Tombstone
2) Turn into a dragon
3) Equip tools in your dragon slots
4) fill inventory
5) die
6) recover items from tombstone (but not tools equipped)

### ■ Expected behavior

6) recover all items from tombstone

**Comment by BlackAures1** [comment]
To do this, use the config to save items in the claws when you die. 
```
#Whether to keep items in the claw slots on death otherwise they will drop on death.
		keepClawItems = true
```

**Comment by xiagu** [comment]
If I recall correctly, the Gravestone mod dumps extra items into the world if your inventory is full when retrieving items, so you could try that as a workaround.
