### ISSUE TITLE
[1.18.2 Forge Bug]: Game crashes when hovering over the Human option in the dragon altar while Danny´s expansion is installed

### ISSUE THREAD

**Issue by MorrisMo333** [DragonSurvivalTeam/DragonSurvival#171]
### ■ Your Discord ID

Hieronymus33#2762

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.4_beta.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

When looking at the human option on the dragon altar while having danny´s expansion installed the game crashes. 
The Version of Dannys expansion used was: dannys_expansion-1.2.5.jar

### ■ To Reproduce

Right click Dragon altar. Hover over Human option.

### ■ Expected behavior

Seeing whatever I´m supposed to see when hovering  over the Human option.

### ■ Crash Report

[crash-2022-05-30_12.31.14-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8797617/crash-2022-05-30_12.31.14-client.txt)

**Comment by BlackAures1** [comment]
duplicate https://github.com/DragonSurvivalTeam/DragonSurvival/issues/141
