### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by Quubin** [DragonSurvivalTeam/DragonSurvival#173]
### ■ Your Discord ID

Heated Haunches#8964

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.4_beta.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Most times I use the Waystone mod to teleport somewhere, I end up getting squished; usually if no one's in the chunk I'm teleporting to.

### ■ To Reproduce

Put a waystone somewhere, put one a few chunks away, and teleport between the two until it happens.

### ■ Expected behavior

Preferably not being squished.

**Comment by Shurhaian** [comment]
This happens with other forms of teleportation too, even if the place being teleported to is wide open. It's especially vexing that there's no way to get out of it - once it's decided you've been squished, no matter if you're out in the open air with nothing around you for dozens of blocks, you WILL eventually die.

**Comment by BlackAures1** [comment]
Fixed in the latest version of the DS.
If you are using the old one or don't delete configs, make useModifiedHitboxes = false in the server config.
