### ISSUE TITLE
[1.18.2 Forge Bug]: multiple

### ISSUE THREAD

**Issue by vixenthief** [DragonSurvivalTeam/DragonSurvival#174]
### ■ Your Discord ID

🦊VixenThiefVT🦊#2705

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.4_beta.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

multiple issues. Items im holding are not the ones displaying on my character for other players. same vise versa. other players are in a constant biting animation after digging or attacking. non stop footsteps when the dragons are not moving at all. treasure sleeping does not pass the night. 

### ■ To Reproduce

it keeps happening during normal game play

### ■ Expected behavior

items to switch, and no items to show when not holding anything.
No sound if not walking.
Day to come if I sleep on treasure

**Comment by CvoidWyvern** [comment]
A list of mods & mod versions + forge version would be helpful

**Comment by vixenthief** [comment]
Forge 40.1.20

Better Villages - Forge
jtl_elisa
BetterVillage-Forge-1.18.2-1.0.0.jar

CreativeCore
CreativeMD
CreativeCore_FORGE_v2.6.9_mc1.18.2.jar

Kiwi 🥝 (Forge)
Snownee_
Kiwi-1.18.2-forge-6.1.0.jar

Mantle
mDiyo
Mantle-1.18.2-1.9.20.jar

Straw Golem Reborn - Forge
CommodoreThrawn
Strawgolem-forge-1.18.2-2.0.0a2.jar

The Gold Rush
Ddx11__
The Gold Rush 1.1.jar

Alex's Mobs
sbom_xela
alexsmobs-1.18.3.jar

Collective (Forge)
Serilum
collective-1.18.2-4.25.jar

GeckoLib
ThanosGecko
geckolib-1.18-forge-3.0.18.jar

Guard Villagers
almightytallestred
guardvillagers-1.18.2.1.4.2.jar

Immersive Weathering [FORGE]
OrdanaryMods
immersive_weathering-1.18.2-1.2.10.jar

JourneyMap
techbrew
journeymap-1.18.2-5.8.4-forge.jar

Kotlin for Forge
thedarkcolour
kotlinforforge-3.3.2-obf.jar

Macaw's Fences and Walls
sketch_macaw
mcw-fences-1.0.4-mc1.18.2.jar

PAUCAL
petrak_at
paucal-forge-1.18.2-0.4.5.jar

Reeves's Furniture [PLANTS UPDATE 🌳]
ree_ves
reeves-furniture-1.18.2-0.4r.jar

Selene Lib
MehVahdJukaar
selene-1.18.2-1.16.6.jar

Sophisticated Backpacks
P3pp3rF1y
sophisticatedbackpacks-1.18.2-3.17.2.588.jar

Sophisticated Core
P3pp3rF1y
sophisticatedcore-1.18.2-0.2.5.28.jar

Supplementaries
MehVahdJukaar
supplementaries-1.18.2-1.4.0.jar

Adorn (Forge)
Juicebus
Adorn-3.5.0+1.18.2-forge.jar

AutoRegLib
Vazkii
AutoRegLib-1.7-53.jar

Butcher's Delight
onuadan
Butchersdelight alpha 1.18 1.0.0.jar

Chisels & Bits - For Forge
AlgorithmX2
ChiselsBits-forge-1.18.2-1.2.90-universal.jar

Decoration and Furniture (Forge)
Skart2007
Decoration Mod 1.7.1 (Ver 1.18.2).jar

Decorative Blocks
stohun
Decorative Blocks-forge-1.18.2-2.1.0.jar

Dragon Survival [Forge]
BlackAuresArt
DragonSurvival_DragonEditor-1.18.2-0.11.4_beta.jar

Farmer's Delight
vectorwing
FarmersDelight-1.18.2-1.1.1.jar

Farmer's Respite
lumpazl
FarmersRespite-1.18.2-1.2.0.jar

Library Ferret - Forge
jtl_elisa
LibraryFerret-Forge-1.18.2-1.0.3.jar

Mine-Pop!
steficy3110
Mine-Pop! 1.2-1.18.2 (FORGE).jar

Nether's Delight
lumpazl
NethersDelight-1.18.2-2.2.0.jar

Oak's Decor
continuedoakgaming
Oak's+Decor+v4.0 (PRIVATE).jar

Quark
Vazkii
Quark-3.2-357.jar

Serene Seasons
TheAdubbz
Serene Seasons-1.18.2-7.0.0.13.jar

Snow! Real Magic! ⛄ (Forge)
Snownee_
SnowRealMagic-1.18.2-forge-4.1.0.jar

Towns and Towers - Structure Add-on
Biban_Auriu
Towns-and-Towers-1.18.2-1.6.0.jar

HT's TreeChop
hammertater
TreeChop-1.18.2-0.15.7.jar

YUNG's API (Forge)
YUNGNICKYOUNG
YungsApi-1.18.2-Forge-2.0.8.jar

YUNG's Better Dungeons (Forge)
YUNGNICKYOUNG
YungsBetterDungeons-1.18.2-Forge-2.1.0.jar

YUNG's Better Mineshafts (Forge)
YUNGNICKYOUNG
YungsBetterMineshafts-1.18.2-Forge-2.1.3.jar

YUNG's Better Strongholds (Forge)
YUNGNICKYOUNG
YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar

YUNG's Extras (Forge)
YUNGNICKYOUNG
YungsExtras-1.18.2-Forge-2.1.0.jar

Furniture Frenzy
Season_Cookie
[FORGE] Furniture Frenzy V0.0.8 - 1.18.2.jar

Alex's Delight
NCP_Bails
alexsdelight-1.18.2-1.2.3.jar

Balm (Forge Edition)
BlayTheNinth
balm-3.0.3+0.jar

BlockUI
H3lay
blockui-1.18.2-0.0.47-ALPHA.jar

Camp Chair
dmitrylovin
campchair-forge.1.18-1.0.0.jar

Carry On
Tschipp
carryon-1.18.2-1.17.0.8.jar

MrCrayfish's Furniture Mod
MrCrayfish
cfm-7.0.0-pre29-1.18.2.jar

Citadel
sbom_xela
citadel-1.11.3-1.18.2.jar

Corn Delight
sz0999312
corn_delight-1.0.4-1.18.2.jar

Corpse
henkelmax
corpse-1.18.2-1.0.1.jar

Double Doors (Forge)
Serilum
doubledoors_1.18.2-3.3.jar

Farming for Blockheads
BlayTheNinth
farmingforblockheads-forge-1.18.2-10.0.1.jar

Gems & Jewels
sea_leaf
gemsnjewels-1.18.2-0.5.5.jar

Goblin Traders
MrCrayfish
goblintraders-1.7.2-1.18.2.jar

Heartstone
plantspookable
heartstone-1.18-1.0.0.jar

Honey Expansion (Add-on for Farmer's Delight)
Spiteful_raccoon
honeyexpansion-1.1.1.jar

Just Enough Items (JEI)
mezz
jei-1.18.2-9.5.5.174.jar

Macaw's Doors
sketch_macaw
mcw-doors-1.0.6-mc1.18.2.jar

Macaw's Furniture
sketch_macaw
mcw-furniture-3.0.0-mc1.18.2.jar

Macaw's Windows
sketch_macaw
mcw-windows-2.0.3-mc1.18.2.jar

Mysterious Mountain Lib
sz0999312
mmlib-1.0.2-1.18.2.jar

Overweight Farming
agentmhkskg
overweightfarming-1.18.2-1.3.2-forge.jar

Player Companions
Kaworru
player_companions_1.18.2-1.1.0.jar

Polymorph (Forge)
TheIllusiveC4
polymorph-forge-1.18.2-0.44.jar

Realistic Bees (Forge)
Serilum
realisticbees_1.18.2-2.5.jar

Server Performance - Smooth Chunk Save[Forge/Fabric]
someaddon
smoothchunk-1.18.2-1.9.jar

Snowy Spirit
MehVahdJukaar
snowyspirit-1.18.2-1.3.1.jar

Starter Kit (Forge)
Serilum
starterkit_1.18.2-3.2.jar

Valhelsia Core
ValhelsiaTeam
valhelsia_core-1.18.2-0.3.1.jar

Valhelsia Structures
ValhelsiaTeam
valhelsia_structures-forge-1.18.2-0.1.0.jar

Wall-Jump! [FORGE]
genandnic
walljump-forge-1.18.1-1.3.7.jar

Waystones
BlayTheNinth
waystones-forge-1.18.2-10.0.0.jar

**Comment by CvoidWyvern** [comment]
Forge version is about a month out of date, maybe try updating it and the rest of the pack?

**Comment by BlackAures1** [comment]
Update to the latest version and let me know if any problems reappear. Do not bundle many bug reports into 1 bug report. Each bug should be in a separate bug report with a detailed description.
