### ISSUE TITLE
[1.18.2 Forge Bug]: Being a dragon blocks interaction with MnA constructs

### ISSUE THREAD

**Issue by Shurhaian** [DragonSurvivalTeam/DragonSurvival#175]
### ■ Your Discord ID

MadMephit#9207

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.4_beta.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

When playing alongside Mana and Artifice, being a dragon prevents the player from interacting with animated constructs (the modular golems). Turning back into a human is a workaround, but this entails sacrificing all growth progress.

Tested with a Sea Beacon active / while having the Sea Peace and Animal Calm effects to see if it was an interaction with the "animals fear dragons" interaction, but this did not help.

I am playing in a custom set of mods, but have confirmed that the error occurs with only Dragon Survival, Geckolib, Mana and Artifice, and JEI present.

### ■ To Reproduce

1. Become a dragon at the Dragon Altar. (Any kind)
2. Obtain a Codex Arcana to unlock Mana and Artifice mechanics.
3. Craft a Manaweaving Altar.
4. Make a Bell of Bidding, and a set of Wickerwood construct parts (head, torso, legs, left arm, right arm).
5. Make an armor stand. Place the construct parts onto it.
6. Make Animus Dust and use it on the armor stand with construct.
7. Hold the Bell of Bidding and use the command wheel ('z' default) to select Follow.
8. Attempt to right-click on the construct.
9. Nothing happens - no animation, no sound, and the construct does not start following.
10. Turn back into a human.
11. Try again to give instructions to the construct.
12. It works.

### ■ Expected behavior

The Bell should be able to issue the construct instructions (or look at its diagnostics). Without being able to issue commands, the constructs cannot be used except by temporarily turning into a human again (and perhaps spawning some dragon hearts to recover lost growth progress).

### ■ Crash Report

N/A. This doesn't cause a crash or any log messages, it just doesn't work.

**Comment by Horeak** [comment]
Could you try disabling the new hitboxes in DragonSurvival by going to server `config > general > useModifiedHitboxes` and setting it to false?

**Comment by Shurhaian** [comment]
That does seem to be a functioning workaround! Thanks much.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Horeak** [comment]
Good to hear and sorry for the long wait.

Will probably rework or remove the hitboxes anyway at this point.
