### ISSUE TITLE
[1.18.2 Forge Bug]: Sudden Crash after warping Home

### ISSUE THREAD

**Issue by KingXaldin** [DragonSurvivalTeam/DragonSurvival#184]
### ■ Your Discord ID

☪ King Xaldin ☪#4046

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-0.11.4.beta.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I used some waystones to warp to a village to get some carpet so I could make the occulus from mana and artifice, and there were the prince and their knights from dragon survival. After getting the carpets, I used the waystones to warp back, using a second waystone along the way because my base was just far enough that warping directly to it would cost me EXP. After I warped back to my base, the game froze and then crashed, and now crashes every time I try to reload the world.

### ■ To Reproduce

Haven't tried

### ■ Expected behavior

Well I didn't expect it to Crash

### ■ Crash Report

[crash-2022-07-23_12.31.21-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9176504/crash-2022-07-23_12.31.21-client.txt)

**Comment by BlackAures1** [comment]
Should be fixed in the new version. If this is still relevant to you, make backup the world, disable DS, go into the world. If everything works, return the DS and update to the latest version.
