### ISSUE TITLE
[1.18.2 Forge Bug]: Default Configs crash

### ISSUE THREAD

**Issue by Reshy** [DragonSurvivalTeam/DragonSurvival#188]
### ■ Your Discord ID

Reshy#5860

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.15.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

The game crashes attempting to use the Default Config folder with the configs for Dragon Survival

### ■ To Reproduce

Put dragon survival into the "default configs" folder.

### ■ Expected behavior

It should load the config from the default configs without crashing.

### ■ Crash Report

[crash-2022-08-05_05.46.49-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9268963/crash-2022-08-05_05.46.49-server.txt)

**Comment by Horeak** [comment]
Forge issue: https://github.com/MinecraftForge/MinecraftForge/issues/7963
