### ISSUE TITLE
[1.18.2 Forge Bug]: Changing Dimensions brings up dragon prompt

### ISSUE THREAD

**Issue by Reshy** [DragonSurvivalTeam/DragonSurvival#189]
### ■ Your Discord ID

Reshy#5860

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.15.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

When entering another dimension, the prompt for choosing the dragon form appears each time you change dimension.
![2022-08-05_08 43 08](https://user-images.githubusercontent.com/2096384/183113403-a976914d-f7cc-422f-b922-d7579523e26c.png)
![2022-08-05_08 44 00](https://user-images.githubusercontent.com/2096384/183113409-9938d034-33e3-49ec-90a9-44904feff599.png)

### ■ To Reproduce

Enter another dimension with default settings.

### ■ Expected behavior

The prompt should only appear once upon loading into the world for the first time, not every time the world/dimension is loaded.

**Comment by Horeak** [comment]
Will be fixed in next version.
