### ISSUE TITLE
[1.18.2 Forge Bug]: crash on the screen

### ISSUE THREAD

**Issue by Charaxiphare** [DragonSurvivalTeam/DragonSurvival#190]
### ■ Your Discord ID

Charaxiphare#8524

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.15.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Yesterday it would crash on the screen. Now it lags extremely whenever I hover over it, to the point where the game freezes and I have to force quit. 

### ■ To Reproduce

1. Open an existing world or create one. 2. Wait for it to load. 3. Hover mouse over the GUI/Game interface that has the dragon icons. 4. Have computer freeze up as so. 

### ■ Expected behavior

I expect to be able to load into a world and not freeze my game on a selection screen. 

### ■ Crash Report

Not really a crash but I did get this exit code: 9

**Comment by BlackAures1** [comment]
Logs?
![image](https://user-images.githubusercontent.com/43911230/184872639-0a38ab65-6909-4ef3-ade6-f89555d4cf91.png)

**Comment by BlackAures1** [comment]
No answer - no problem?
