### ISSUE TITLE
[1.16.5 Forge Bug]: Can't change the color of dragon

### ISSUE THREAD

**Issue by EvaLinn** [DragonSurvivalTeam/DragonSurvival#191]
### ■ Your Discord ID

EvaLinn#2973

### ■ Dragon Survival version

DragonSurvival_dragoneditor-1.16.5-0.10.6

### ■ Single game or server?

Playing with friends over a local network (Hamachi, etc.)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

![изображение_2022-08-08_000057559](https://user-images.githubusercontent.com/83809307/183304699-30c7cbc0-9cff-4426-810d-c13e5700c16f.png)
I change colors but nothing happens

### ■ To Reproduce

I tried to turn off the shaders but it didn't help

### ■ Expected behavior

choose color and color remains the same

**Comment by EvaLinn** [comment]
Incompatibility with mod Dragon Mounts: Legacy

**Comment by EvaLinn** [comment]
Incompatibility witch oculus

**Comment by BlackAures1** [comment]
I don't see any connection between anything you wrote. All these mods work together and the dragon editor also works without errors.

**Comment by EvaLinn** [comment]
Короче, у меня стоял Dragon Mounts и даже если шейдеры в окулус отключить, то цвета не меняются.После я удалила Dragon Mounts и отключила шейдеры и всё заработало. Но если шейдеры все же оставить, то цвет не меняется. Цвет не меняется только на базе, а на дополнительном все окей.

**Comment by EvaLinn** [comment]
> I don't see any connection between anything you wrote. All these mods work together and the dragon editor also works without errors.

Короче, у меня стоял Dragon Mounts и даже если шейдеры в окулус отключить, то цвета не меняются.После я удалила Dragon Mounts и отключила шейдеры и всё заработало. Но если шейдеры все же оставить, то цвет не меняется. Цвет не меняется только на базе, а на дополнительном все окей.

**Comment by BlackAures1** [comment]
Если ты смотришь от первого лица, то тут виноват только oculus и о несовместимости с ним написано на вики. От 3 лица всё выглядит корректно и в самом редакторе тоже нормально работает. Эти 3 вещи, что ты написал никак не воспроизводятся и не связаны.
При чём тут Dragon Mounts вообще в душе не чаю. Много играла с ним на разных версиях DS.
------
If you look in first person, then there is only oculus to blame and the incompatibility with it is written on the wiki. In third person, everything looks correct and in the editor itself also works fine. 
What does Dragon Mounts have to do with it at all. Played with it a lot on different versions of DS.
