### ISSUE TITLE
[1.18.2 Forge Bug]: Lava Swim speed

### ISSUE THREAD

**Issue by blaxout1213** [DragonSurvivalTeam/DragonSurvival#193]
### ■ Your Discord ID

dimwit10⁵#8052

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.19

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

The Cave Dragon's fast swimming does nothing to your speed, whereas this worked in previous versions

### ■ To Reproduce

1. Pick a cave dragon
2. Sprint in lava
3. Observe the lack of speed

### ■ Expected behavior

I would expect the cave dragon's speed to be higher. This was the case in version DragonSurvival_DragonEditorUpdate 0.11.4 - 1.18.2)

**Comment by BlackAures1** [comment]
This is a planned change
