### ISSUE TITLE
[Compatibility]: World loading deadlock with Project Expansion

### ISSUE THREAD

**Issue by tlitookilakin** [DragonSurvivalTeam/DragonSurvival#198]
### ■ Your Discord ID

tlitookilakin#1010

### ■ Dragon Survival version

1.18.2-1.4.19

### ■ Minecraft version

1.18

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

The problem occurs even on a minimal installation. (GeckoLib, Dragon Survival, ProjectE, Project Expansion).
Project Expansion seems to be causing reflection errors- first crashing dragon survival, and then preventing the server from shutting down correctly, leaving the game to hang. 
Already reported to Project Expansion devs (DonovanDMC/ProjectExpansion#70) but closed as "unrelated".

### ■ To Reproduce

* Install Dragon Survival (and requirements)
* Install Project Expansion (and requirements)
* Attempt to load or create a world

### ■ Crash Report

[Log](https://mclo.gs/Onp8AMb)

**Comment by BlackAures1** [comment]
![image](https://user-images.githubusercontent.com/43911230/184930480-5b617a87-1851-4692-8020-0625b0e3fee8.png)
You made a typo in the server config. Delete them to check.

**Comment by tlitookilakin** [comment]
This is from a fresh install on a brand new world, but I'll do that.

**Comment by BlackAures1** [comment]
Okay, I'm getting the same error, but I can't help with that right now. These are questions for the programmer, but compatibility bugs with other mods are at the lowest priority. So a fix may not be very soon.

**Comment by tlitookilakin** [comment]
thanks for looking into it. I'll let you know if I find anything on the other end

**Comment by BlackAures1** [comment]
It seems the programmer was in a good mood and fixed it yesterday. It's definitely working now. I will upload this fix to curseforge soon

**Comment by tlitookilakin** [comment]
awesome! thanks a bunch.
