### ISSUE TITLE
[1.18.2 Forge Bug]: cannot play on the recommended version of forge

### ISSUE THREAD

**Issue by joeyjumper94** [DragonSurvivalTeam/DragonSurvival#200]
### ■ Your Discord ID

joey_#3699

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

unable  to play dragon survival on the recommended version of forge.

### ■ To Reproduce

1. use curseforge to make a fresh 1.18.2 install
2. click add more content and add dragon survival( geckolib will be installed automatically)
3. start the game.

### ■ Expected behavior

i expect to see the main menu, not error loading mod

### ■ Crash Report

[crash-2022-08-21_22.32.04-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9391493/crash-2022-08-21_22.32.04-fml.txt)

**Comment by BlackAures1** [comment]
Just read the patch descriptions or installation instructions - https://dragons-survival.fandom.com/wiki/Start_and_Setting#1.18.2

**Comment by Horeak** [comment]
40.1.67 Is the oldest version that is supported by the current DS version
