### ISSUE TITLE
[1.18.2 Forge Bug]: Apple Skin

### ISSUE THREAD

**Issue by DarkMoon-XY** [DragonSurvivalTeam/DragonSurvival#201]
### ■ Your Discord ID

DarkMoon-XY#7515

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I updated the last version of DS and checked the appleskin support dissapear. I see the old config file and there exist the appleskin support in the configs but in the new no.

### ■ To Reproduce

1. Change the old file to new
2. Enter to game 
3. The config reload and dont get appleskin mod support

### ■ Expected behavior

The new update of DS eliminate the appleskin support.

**Comment by BlackAures1** [comment]
We do not support AppleSkin on 1.18.2 due to closed source code. We will make our own system for food display at a later date.
