### ISSUE TITLE
[1.16.5 Forge Bug]:  Valhelsia incompat

### ISSUE THREAD

**Issue by SeadragonDreams** [DragonSurvivalTeam/DragonSurvival#203]
### ■ Your Discord ID

SeadragonDreams#3687

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.6.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Whenever I try to use one of the in-game menus from the mod (dragon altar selection, hovering over the skill and other tabs), the game gives me the following error: The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

This happens in both a server and on single-player mode.

### ■ To Reproduce

Put down a dragon altar. Attempt to choose a dragon. Alternatively, make yourself a dragon via command and attempt to access the editor or other tabs.

### ■ Expected behavior

I expect to be able to choose a dragon and look at the various menus without issue. If I wanted to check the Your Dragon or Skill tab, I would like to be able to toggle my custom skin or upgrade my skills.

### ■ Crash Report

[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9429396/latest.log)
[crash-2022-08-25_22.55.16-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9429397/crash-2022-08-25_22.55.16-client.txt)

**Comment by BlackAures1** [comment]
Is your modpack in the public domain? The clean version of DS without other mods works correctly on this version.

**Comment by SeadragonDreams** [comment]
Unfortunately no as we are trying to test things before release. I can, however, provide the .zip file.

**Comment by SeadragonDreams** [comment]
Oops, accidentally hit closed. Sorry!

**Comment by BlackAures1** [comment]
Don't rush into it just yet. I will wait for an answer from @Horeak

**Comment by Horeak** [comment]
Try to delete or move the "dragon-survival" folder in the modpack folder, then try to launch it again

**Comment by SeadragonDreams** [comment]
Unfortunately that didn't work. I'm trying to track down the mod that's conflicting with it to see if that's an issue, but that will take a while.

**Comment by SeadragonDreams** [comment]
I found the proverbial needle in the haystack- It has something to do with Valhelsia Structures, Valhelsia Core, or Valhelsia Tweaks.
