### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by UngaBungaNoise** [DragonSurvivalTeam/DragonSurvival#204]
### ■ Your Discord ID

a_confused_ungabunga_noise#3710

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

when trying to load up this mod I keep getting an error message saying the mod didn't load I guessed that it clashed with a different mod but when I tried it on its own it still didn't work i have the GeckoLib mod (geckolib-forge-1.18-3.0.36.jar) I looked at the wiki and this seemed to be fine 

### ■ To Reproduce

i dont know how to recreate it it just refuses to load the mod 

### ■ Expected behavior

i expect the mod to load 

### ■ Crash Report

[crash-2022-08-30_15.43.27-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9454026/crash-2022-08-30_15.43.27-fml.txt)

**Comment by Horeak** [comment]
Update the forge version and it should fix it.

**Comment by BlackAures1** [comment]
Did it happen again?
