### ISSUE TITLE
[1.18.2 Forge Bug]: Food as not marked in the config gives 0 food and saturation in any case

### ISSUE THREAD

**Issue by SiJunma** [DragonSurvivalTeam/DragonSurvival#205]
### ■ Your Discord ID

Seramis#4283

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

If a dragon eats food that is not intended for him - after that the saturation from the food does not rise, the saturation is always 0.
You have to die to fix it.

### ■ To Reproduce

1. Eat food not intended for this kind of dragon.
2. You are no longer getting saturation - not from the food, not from the effects.

### ■ Expected behavior

After getting the debuff and feeding the saturation must be added

**Comment by Darkvulpine** [comment]
I too also  have the same issue, any food not designed for dragon will still restore hunger, but saturation is completely stopped.
Forge 40.1.80 and 40.1.70 tested.

https://user-images.githubusercontent.com/69316348/190864843-3de05568-1342-4423-ac92-34dffe2748f0.mp4

**Comment by LoneWolf137** [comment]
had that too. I was confused when the f3 saturation value said NaN. Now i know where it is from and how to doge it. It gets interesting when you play a big modpack and this kind of stuff happens.
