### ISSUE TITLE
[1.18.2 Forge Bug]: Skill resets in a local multiplayer

### ISSUE THREAD

**Issue by Rihnami** [DragonSurvivalTeam/DragonSurvival#207]
### ■ Your Discord ID

Rihnami#4701

### ■ Dragon Survival version

DragonSurvival_DragonEditorUpdate 1.4.26 - 1.18.2

### ■ Single game or server?

Playing with friends over a local network (Hamachi, etc.)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

All passive skills level reset at my friend

### ■ To Reproduce

Launch Minecraft
Create world
Open world to local server
Friend login
Friend transform to a dragon
Friend level up any passive skills
Friend logoff
Relaunch Minecraft (I and my friend)
Open world to local server
Friend login

### ■ Expected behavior

Relaunch Minecraft

**Comment by BlackAures1** [comment]
This is only a visual bug. If your friend connects again everything will be fine. We are aware of this problem, but Lan is very hard to fix.

**Comment by seelderr** [comment]
Very old, closing as stale.
