### ISSUE TITLE
[1.18.2 Forge Bug]:  Changing Dimension bring sup Dragon Prompt

### ISSUE THREAD

**Issue by Reshy** [DragonSurvivalTeam/DragonSurvival#208]
### ■ Your Discord ID

Reshy#5860

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

When changing dimensions, dying, or reloading into an already created world the dragon select prompt is given.

### ■ To Reproduce

1.  Die or Enter the Nether
2.  See Prompt

![2022-09-01_02 27 17](https://user-images.githubusercontent.com/2096384/187881833-6f784182-f2aa-426e-a9eb-6cadab3871fa.png)
![2022-09-01_02 27 28](https://user-images.githubusercontent.com/2096384/187881838-a8dfafbf-6685-45ca-b7bf-0f6921e7419f.png)
![2022-09-01_02 27 38](https://user-images.githubusercontent.com/2096384/187881852-49b26b7a-8174-479d-8d1e-342e6a382cee.png)
![2022-09-01_02 27 42](https://user-images.githubusercontent.com/2096384/187881868-91af12c0-4540-4835-8418-c6810aa77487.png)

### ■ Expected behavior

The prompt should only appear a single time, when a player first connects to the server.

**Comment by Horeak** [comment]
Update to version 1.4.26 and thos issue should already be fixed

**Comment by BlackAures1** [comment]
On 1.4.26 version the same problem
