### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by TrikiNya** [DragonSurvivalTeam/DragonSurvival#209]
### ■ Your Discord ID

TrikiNya#2902

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

The dragon magic system here is screwy
Trying to use lightning breath depletes my XP bar most of the time without even getting so much as a spark out
Not to mention slow-flying depletes my hunger bar way too quickly than I think it should
I don't know if it's lag because I have all bars of ping filled

### ■ To Reproduce

1. Start a new multiplayer server world with Dragon Survival and its dependencies installed
2. You'd see the dragon selection screen. I selected sea dragon
3. rack up some XP (at least 5 levels)
4. Hold down the casting key for your elemental breath attack. You'll see the XP bar deplete while the casting bar goes up slower, then mentions the lack of mana and experience.

1. Spread your wings
2. go upwards
3. You start to purge

### ■ Expected behavior

The XP bar shouldn't be depleting before I manage to properly cast the spell, and I'm not sure if hunger should deplete so quickly.

**Comment by BlackAures1** [comment]
Use this config to fix the balance and flight problem.  https://ptb.discord.com/channels/486465167572336641/834425775620882432/1014307315127693352

To fix your problem with XP, disable noEXPRequirements. Enter this parameter if you do not have it in your configs
![image](https://user-images.githubusercontent.com/43911230/188020112-2e89161b-6f68-4292-9eb9-bf4da44ea7d8.png)

**Comment by TrikiNya** [comment]
> Use this config to fix the balance and flight problem. Please read the patch notes before any updates. https://ptb.discord.com/channels/486465167572336641/834425775620882432/1014307315127693352
> 
> To fix your problem with XP, disable noEXPRequirements. Enter this parameter if you do not have it in your configs ![image](https://user-images.githubusercontent.com/43911230/188020112-2e89161b-6f68-4292-9eb9-bf4da44ea7d8.png)

it's not my server 😕

**Comment by BlackAures1** [comment]
Just arrange it with the administrator. Your problems are solved by elementary configuration of configs.
