### ISSUE TITLE
[1.18.2 Forge Bug]: RenderLevelStageEvent crash

### ISSUE THREAD

**Issue by Wakatsu** [DragonSurvivalTeam/DragonSurvival#210]
### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Game fails to start with the following message:
![2022-09-02_20 28 23](https://user-images.githubusercontent.com/61901375/188109668-394bd09b-53a6-4916-9755-7a52b73e4b1f.png)

### ■ To Reproduce

Try to start the game

### ■ Expected behavior

The game should start normally

### ■ Crash Report

[crash-2022-09-02_20.28.15-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9476775/crash-2022-09-02_20.28.15-fml.txt)

P.S. If this is an OptiFine issue, then just say so and I'll get outta your hair. I'm reporting because I can't tell if it is a known unfixable problem or something new.

**Comment by Horeak** [comment]
Update your forge version to atleast 40.1.67
