### ISSUE TITLE
[1.18.2 Forge Bug]: saveAllAbilities = true crashing abilities after transforming

### ISSUE THREAD

**Issue by ManironRafnrun** [DragonSurvivalTeam/DragonSurvival#213]
### ■ Your Discord ID

Croacking_God#9912

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

При включенном конфиге сохранения навыков после превращения в человека, когда я превращаюсь обратно в дракона, у меня исчезают все навыки

When the configs saveAllAbilities = true and I turn back into a dragon, all my skills disappear

При необходимости я могу отправить скриншоты или видео с воспроизведением ошибки

### ■ To Reproduce

1. Открыть файл конфигурации \saves\<Название мира>\serverconfig\dragonsurvival-server.toml
2. Изменить пункт saveAllAbilities на true (строка 52)
3. Сохранить файл конфигурации
4. Запустить Minecraft
5. Зайти в мир
6. Если играешь за человека - превратиться в дракона (Если играешь за дракона - Повысить навык)
7. Повысить навык (Если играешь за дракона - превратиться в человека)
8. Превратиться в человека (Если играешь за дракона - превратиться в дракона)
9. Превратиться в дракона
10. При открытии вкладки магии дракона - у всех навыков будут отсутствовать иконки

-------------

1. Open the configuration file \saves\<World Name>\serverconfig\dragonsurvival-server.tool
2. Change save All Abilities to true (line 52)
3. Save the configuration file
4. Launch Minecraft
5. Enter the world
6. If you play for a human, turn into a dragon (If you play for a dragon, increase your skill)
7. Increase your skill (If you play for a dragon, turn into a human)
8. Turn into a human (If you play as a dragon, turn into a dragon)
9. Turn into a dragon
10. When opening the dragon magic tab, all skills will be missing icons

### ■ Expected behavior

Навыки, у которых повышен уровень, сохранят его после превращения в человека и обратно в дракона

Skills that have an increased level will retain it after turning into a human and back into a dragon

**Comment by itsdinkd** [comment]
Will this be addressed any time soon?\

**Comment by BlackAures1** [comment]
There's no way I can help with that and speed up the fix. I apologize for the inconvenience.
