### ISSUE TITLE
[1.18.2 Forge Bug]: Some problems about dragon editor. (Report from mcmod.cn)

### ISSUE THREAD

**Issue by Gairlading** [DragonSurvivalTeam/DragonSurvival#214]
### ■ Your Discord ID

Gairlading#3776

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.35

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

1. I can't select the correct color in the dragon editor. Most of the time the color displayed does not match the color of where the slider is.
![2022-09-11_23 07 27](https://user-images.githubusercontent.com/84556705/190656452-6ae18112-858b-4648-b4d3-78a674d5c8e6.png)
![2022-09-11_23 09 03](https://user-images.githubusercontent.com/84556705/190656493-f2ed2091-2935-4ea4-b358-56612f94db2f.png)
2. Some buttons seems to be on the wrong layer.
![2022-09-11_23 07 50](https://user-images.githubusercontent.com/84556705/190656955-c2a62a04-978f-4f78-966d-cb6eb9cc4114.png)

### ■ To Reproduce

1.1. Open dragon editor.
1.2. Choose a part, change it corlor.
1.3. The color doesn't match.

2.1. Move mouse on the size slider, the text on nearby buttons is covered, but buttons are not.

### ■ Expected behavior

1. The displayed color match the color choose by slider.
2. Both the buttons and texts can be coverd same time.

**Comment by BlackAures1** [comment]
Every time someone talks about how a color change icon should be functional and not just an icon with no functionality - there are two DS developers screaming in the world. 

It's not a bug. The colors on the HUE are just pictures. Were pictures and will be pictures without functionality.
