### ISSUE TITLE
[Compatibility]: game crashes when the Ender Dragon dies and drops experience(Try multiple saves with different computer results

### ISSUE THREAD

**Issue by LLLZOMBIE** [DragonSurvivalTeam/DragonSurvival#215]
### ■ Your Discord ID

LZOMBIE#7007

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.6.jar

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Description of incompatibility

Dragon survival mod works perfectly fine alone, But when I played the DS young modpack killing the Ender Dragon, the game crashed

### ■ To Reproduce

1、Install DS young modpack
2、kill the ender dragon

![1](https://user-images.githubusercontent.com/114101174/191577831-742da742-4014-4160-970c-4f53b0d9fbd3.png)
![2](https://user-images.githubusercontent.com/114101174/191577836-137d7715-d444-4000-854b-8b8e9ce62631.png)
![3](https://user-images.githubusercontent.com/114101174/191577843-60d9f99b-0b92-4c34-894d-dba41b5a7337.png)

### ■ Crash Report

[minecraft-exported-crash-info-2022-09-22T01-41-54.zip](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9619237/minecraft-exported-crash-info-2022-09-22T01-41-54.zip)

**Comment by BlackAures1** [comment]
delete endergetic expansion
Young pack Abandoned
