### ISSUE TITLE
[1.18.2 Forge Bug]: Adverse side effects like hunger being applied when eating intended food items for said species.

### ISSUE THREAD

**Issue by Zalycon** [DragonSurvivalTeam/DragonSurvival#216]
### ■ Your Discord ID

real icepick #5041

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.22

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Food introduced by the mod is not marked as "Cave Dragon Food" or other variants of the kind, hence the game treats it as a toxic food and gives the players hunger/poison.

Example: When viewing Charred Food it has no tag saying what food type it is.

### ■ To Reproduce

1. Launch Game
2. Create/Join a world
3. Go into creative inventory and type in "Charred" or any of the subtypes
4. Notice the missing tag and side effects caused by eating said food
5. Finished.

### ■ Expected behavior

Food eaten should not cause adverse side effects if it's intended for the type of dragon the player is playing as.

**Comment by BlackAures1** [comment]
I can't make that mistake again. Install the DS correctly.
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update#-installation
