### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by WolffsPlays** [DragonSurvivalTeam/DragonSurvival#218]
### ■ Dragon Survival version

1.18.2.-1.4.22

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Closing the game on Dragon editor 

### ■ To Reproduce

https://prnt.sc/trfCCPMk1byk

### ■ Expected behavior

Crashin with my mod pack on dragon editor 

### ■ Crash Report

Crashin with my mod pack on dragon editor

**Comment by BlackAures1** [comment]
#220
