### ISSUE TITLE
[1.18.2 Forge Bug]: Download for 1.4.26 instead gives 1.4.22

### ISSUE THREAD

**Issue by AStrangeMouse** [DragonSurvivalTeam/DragonSurvival#219]
### ■ Your Discord ID

Mousy#2784

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.26

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

The CurseForge download page for **Dragon Survival 1.4.26** instead shows, and downloads, version **1.4.22** from an older update. This leads to the latest version being completely unavailable for download.

![image](https://user-images.githubusercontent.com/100734364/195254318-0528b4c4-efd2-41e2-a87d-d14413646651.png)

### ■ To Reproduce

This happens on both the browser page, and in the CurseForge launcher.

### ■ Expected behavior

The page should give version 1.4.26, but instead 1.4.22 is downloaded.

**Comment by Horeak** [comment]
Likely just @BlackAures1 that mislabeled the version, so the latest version on curse forge is still the right version.
