### ISSUE TITLE
[1.18.2 Forge Bug]: 

### ISSUE THREAD

**Issue by akirawav3** [DragonSurvivalTeam/DragonSurvival#220]
### ■ Your Discord ID

🎃 ”彡₊.・Akirawave#0616

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.28

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

World crashes soon as you get to the dragon editor screen. Doesn't render anything, just crashes.

### ■ To Reproduce

No

### ■ Expected behavior

I expected to create a dragon and play minecraft.

### ■ Crash Report

[crash-2022-10-20_20.19.18-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9835444/crash-2022-10-20_20.19.18-client.txt)

**Comment by AetherDrake** [comment]
Remove this mod and read installation guide on DS wiki.
![image](https://user-images.githubusercontent.com/114911522/197106420-4c91df07-86c3-4874-90f6-67d66920291f.png)
