### ISSUE TITLE
[1.18.2 Forge Bug]: Incompatibility with Better Combat mod

### ISSUE THREAD

**Issue by kutuzovpuzov** [DragonSurvivalTeam/DragonSurvival#221]
### ■ Your Discord ID

kutuzka_kukuruzka#0432

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.28

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

Incompatibility with Better Combat mod.

### ■ To Reproduce

I played with a modpack where 94 mods are in. If I try to add one more, I get the crash-log, where the problem caused by bettercombat and dragonsurvival incompatibility. If I delete DS from my modpack and add some new mods, minecraft starts working. (start with more than 94 mods.)

@Redirect conflict. Skipping bettercombat.mixins.json:PlayerEntityMixin->@Redirect::getMainHandStack_Redirect(Lnet/minecraft/world/entity/player/Player;)Lnet/minecraft/world/item/ItemStack; with priority 1000, already redirected by dragonsurvival.mixins.json:MixinPlayerEntity->@Redirect::getDragonSword(Lnet/minecraft/world/entity/player/Player;)Lnet/minecraft/world/item/ItemStack; with priority 1000

### ■ Expected behavior

I'd like to play them together.

### ■ Crash Report

[tlauncher_10_21_2022_17_27_52.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9839976/tlauncher_10_21_2022_17_27_52.log)

**Comment by BlackAures1** [comment]
Don't you think that bettercombat is a **bit** of a bad mod that should be combined with our mod? We physically can't make compatibility with this without breaking our own mod and spending a ton of time on it.

**Comment by BlackAures1** [comment]
Alas, there is no way I can do this without a programmer and I don't want to bother the authors of Better Combat. I'm not a coder, I'm an artist.

**Comment by MarioSMB** [comment]
I brought it up with the Better Combat developer here https://github.com/ZsoltMolnarrr/BetterCombat/issues/139#issuecomment-1385242683  
They mentioned a mod named [Figura](https://www.curseforge.com/minecraft/mc-mods/figura), it may be worth reaching out to them to find a more compatible way to handle replacing the player model, as this may benefit support for other mods as well.  
Hope that helps!

**Comment by BlackAures1** [comment]
Alas, this is impossible for me. I'm an artist, not a programmer, but the whole thing sounds like a complete rewrite of our rendering for the sake of compatibility with 1 mod. BetterCombat is a good mod, but such compatibility is not worth the effort.

**Comment by MarioSMB** [comment]
I guess it depends on just how many mods a cleaner method of rendering would allow to function, but since the focus is indeed on just the one mod I can understand your stance on the situation.  
It is unfortunate but hopefully this can be revisited someday in the future. Thanks for your time.
