### ISSUE TITLE
[1.16.5 Forge Bug]: Geckolib crash

### ISSUE THREAD

**Issue by SirPup2** [DragonSurvivalTeam/DragonSurvival#222]
### ■ Your Discord ID

Jake (SirPup)#1001

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Crash upon hovering mouse over Dragon Types

### ■ To Reproduce

1. Right-Click a Dragon Altar to make the Selection Menu Appear
2. Hover mouse over any of the dragon types (Ex. Fire Dragon, Forest Dragon, Sea Dragon)
3. Instant Crash

### ■ Expected behavior

Being able to select the wanted dragon type in the selection menu.

### ■ Crash Report

[crash-2022-10-26_04.05.27-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9868409/crash-2022-10-26_04.05.27-client.txt)

**Comment by SirPup2** [comment]
Sorry for the name changes, correcting it cause I pressed the wrong one

**Comment by xuisositi** [comment]
i have the same problem!!! :(

**Comment by joeyjumper94** [comment]
if you are having the same problem as https://github.com/DragonSurvivalTeam/DragonSurvival/issues/224 try downdating geckolib to [geckolib-forge-1.16.5-3.0.97.jar](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/4036059)

**Comment by xuisositi** [comment]
after installing geckolib-forge-1.16.5.-3.0.97.jar, you can already go to the dragon selection menu, but when you click on the dragon type, it immediately crash

**Comment by BlackAures1** [comment]
[xuisositi](https://github.com/xuisositi), make sure you don't have any of the mods on the [incompatibility list](https://dragons-survival.fandom.com/wiki/Start_and_Setting#Incompatibility) installed

**Comment by xuisositi** [comment]
no other mods installed except tl_skin_cape_forge_1.16.5-1.19.jar but it installs by itself due to TLauncher.

**Comment by BlackAures1** [comment]
Make sure you do everything exactly as described in the [installation instructions](https://dragons-survival.fandom.com/wiki/Start_and_Setting#%E2%96%A0_Forge_Installation)

**Comment by SirPup2** [comment]
> if you are having the same problem as #224 try downdating geckolib to [geckolib-forge-1.16.5-3.0.97.jar](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/4036059)

This fixed it for me, Thank you
