### ISSUE TITLE
[1.18.2 Forge Bug]: Geckolib crash

### ISSUE THREAD

**Issue by xuisositi** [DragonSurvivalTeam/DragonSurvival#223]
### ■ Your Discord ID

egorka666why#5922

### ■ Dragon Survival version

dragonsurvival_dragoneditor-1.18.2-1.4.28.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

дракон не показывается, только его тень
![image](https://user-images.githubusercontent.com/59812434/198381408-ef311372-a455-4df6-8020-4247d50d6200.png)

кстати, после попытки скрина, ноутбук завис намертво. 

### ■ To Reproduce

захожу на версию forge или же forge optifine, дракон все равно не показывается. 

### ■ Expected behavior

дракон по идее должен показываться.

**Comment by BlackAures1** [comment]
![image](https://user-images.githubusercontent.com/43911230/198745478-b4918a83-15d8-4105-aa3a-7e5978ec120f.png)

**Comment by xuisositi** [comment]
это все равно не работает :(

**Comment by BlackAures1** [comment]
Краш репорт пришли. Я не умею читать их на расстоянии) Всё работает, если всё по [инструкции](https://dragons-survival.fandom.com/wiki/Start_and_Setting#%E2%96%A0_Forge_Installation) устанавливать.
