### ISSUE TITLE
[1.18.2 Forge Bug]: Magic section of UI and part of the dragon tab in inventory dissapeared

### ISSUE THREAD

**Issue by imnotrealicanproveit** [DragonSurvivalTeam/DragonSurvival#225]
### ■ Your Discord ID

Peaceful Chaos#4760

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.28.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

I was playing on the "Play as a Dragon" 1.18.2 modpack, after flying around and playing for a while I had added xaero's minimap mod for teleporting and the minimap. I was in a desert pyramid, fighting all the boss zombies at the end of the dungeon when I kept dying over and over from them, and teleporting back. I got a bit frustrated and went into creative a few times to try and clear them out and destroy the spawners, but at some point in this dying, turning to creative, and teleporting loop my magic UI bar disappeared and while it's still functional, makes the game much harder to play. For some reason the dragon head at the top of the dragon tab disappeared as well?

### ■ To Reproduce

Haven't been able to reproduce.

### ■ Expected behavior

I have attempted to recreate the issue, and to fix it by turning into a human and back to a dragon - but none of it worked. I didn't expect the UI to just vanish and assumed it would stay put regardless.

**Comment by imnotrealicanproveit** [comment]
I'd like to say I'm sorry for wasting time, I found out there was a random toggle UI button? I wish it was more obvious in the keybinds menu as I couldn't find it when I searched, could you perhaps relabel it?

**Comment by BlackAures1** [comment]
I think the huge inscription right on the button is clear enough. 

![image](https://user-images.githubusercontent.com/43911230/198417726-b340bddc-7f8c-4407-8458-8a27ee870bf3.png)
![image](https://user-images.githubusercontent.com/43911230/198417733-6a28a1d9-86f3-4c0b-a1e0-328ac777406b.png)

**Comment by imnotrealicanproveit** [comment]
it was the button that makes the bottom right magic UI disappear, not the inventory screen.

**Comment by BlackAures1** [comment]
Ah, it just exists in the control settings
