### ISSUE TITLE
[1.18.2 Forge Bug]: Mod Loading error

### ISSUE THREAD

**Issue by Coralliafluff** [DragonSurvivalTeam/DragonSurvival#227]
### ■ Your Discord ID

Corallia#7804

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.30.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

I was having issues on another modpack and made a fresh installation with only DS and Geckolib to troubleshoot, and with only those two mods installed DS claims something about "Class not found" during "Render Level stage event"

I do not code Java so i am not sure what the issues is, if it is a fault on my own or if something truly wonky has happened.

### ■ To Reproduce

I honestly do not know how to reproduce this, every time i try to launch the modpack the game crashes

### ■ Expected behavior

I expected the game to launch

### ■ Crash Report

[crash-2022-11-01_19.20.03-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9913020/crash-2022-11-01_19.20.03-fml.txt)

**Comment by Horeak** [comment]
Update to a forge version that is at least number 40.1.67 or newer.
