### ISSUE TITLE
[1.16.5 Forge Bug]: 

### ISSUE THREAD

**Issue by h0sk1** [DragonSurvivalTeam/DragonSurvival#233]
### ■ Your Discord ID

Хоски#9385

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Баг при изменении в конфигах. Я отключила слабости лесному и морскому дракону, то есть, выкрутила их на ноль. Лесному дракону отключила эффект стресса, а морскому - эффект сухости на суше. Проблема в том, что если этим драконам отключить их слабости, то у них начнутся отображаться визуальные эффекты, будто дракон находится в состоянии стресса (если говорить о лесном), или в состоянии нехватки влаги (если говорить о морском). От лесного вечно исходит серый дым, а от морского вечно летят чешуйки.
![image](https://user-images.githubusercontent.com/111293659/205061604-a13fa330-f268-4ebd-9dd9-261c2d4aa593.png)
![изображение_2022-12-01_171508914](https://user-images.githubusercontent.com/111293659/205062111-1b9bb66f-ffa9-4253-86bb-e823fa633479.png)

### ■ To Reproduce

Для лесного дракона:
1. Захожу в Server config
2. Захожу в Penalties
3. Захожу в Forest
4. Выставляю значение Ticks Before Stressed на 0
5. Захожу в игру в режим выживания, на драконе постоянно висит эффект черных частиц.
Для морского дракона:
1. Захожу в Server config
2. Захожу в Penalties
3. Захожу в Sea
4. Выставляю значение Ticks Without Water на 0
5. Захожу в игру в режим выживания, на драконе постоянно висит эффект частиц шелушащихся чешуек.

### ■ Expected behavior

Ожидала, что не будет исходить никаких частиц от дракона при отключении их слабостей в конфигах.

**Comment by BlackAures1** [comment]
Как я уже говорила нужно наоборот повышать эти значения до максимальных (100000). Конфиг для отключения дебафов находится в другом месте: 

![image](https://user-images.githubusercontent.com/43911230/205205049-66ca5727-c378-4009-989f-fcc88abe1571.png)
