### ISSUE TITLE
[Compatibility]: 1.18.2 modpack weirdness

### ISSUE THREAD

**Issue by LoneWolf137** [DragonSurvivalTeam/DragonSurvival#234]
### ■ Your Discord ID

Lone Wolf #9200

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.36, happens with every 1.18.2 version.

### ■ Minecraft version

1.18

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

i have been on this the last day putting the mods of this modpack in one by one and i am just confused. i dont know wich mod it is that causes this, but the game just doesnt even load. At this point i am just very interessed in what the error is.

### ■ To Reproduce

1. add dragon survival to the 1.18.2 create + modpack
2. delete pyrotastic-1.18.2+2.0.3 as that also breaks with dragons survival
3. try starting the pack
4. crash

### ■ Crash Report

[crash-2022-12-03_23.42.54-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10147492/crash-2022-12-03_23.42.54-fml.txt)

**Comment by BlackAures1** [comment]
https://dragons-survival.fandom.com/wiki/Start_and_Setting Make sure that you completely follow the installation instructions and the other points.

**Comment by BlackAures1** [comment]
Delete Waterlogged Redstone
