### ISSUE TITLE
CRash Whenever you try to turn into a dragon[1.16.5 Forge Bug]: 

### ISSUE THREAD

**Issue by Dc061509** [DragonSurvivalTeam/DragonSurvival#239]
### ■ Your Discord ID

DemonTheNotable#0573

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I try to turn into any dragon and the game just crashes

### ■ To Reproduce

Not without restarting

### ■ Expected behavior

I expected to turn into a dragon

**Comment by BlackAures1** [comment]
Someday people will learn to read the installation instructions before writing a bug report....

GECKOLIB
https://dragons-survival.fandom.com/wiki/Start_and_Setting#%E2%96%A0_Forge_Installation
