### ISSUE TITLE
[Compatibility]: More Player Models overrides Dragon Survival PoV

### ISSUE THREAD

**Issue by Umbreeunix** [DragonSurvivalTeam/DragonSurvival#240]
### ■ Your Discord ID

Umbreeunix#6904

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.5.38.jar

### ■ Minecraft version

1.18

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

Running Dragon Survival alongside More Player Models results in the 1st perosn PoV being forcibly set to the default height. (2 blocks) It does this regardless of dragon species, growth stage, or size, and More Player Models doesn't offer an option to disable this in their config. (the PoV and Compatibility options do not solve the problem)

The result is animations for flight and jump snapping up to camera height, and a lot of camera jittering in general. The effect is lessened in 3rd person PoV.

This results in flight/jump animations snapping up and a lot of camera jittering. Effect is lessened in 3rd person PoV.

### ■ To Reproduce

Install:
1. DragonSurvival_DragonEditor-1.18.2-1.5.38.jar
2. geckolib-forge-1.18-3.0.57.jar
3. MorePlayerModels-1.18.2.20220801.jar
4. forge-1.18.2-40.1.86

### ■ Crash Report

N/A

**Comment by Umbreeunix** [comment]
Note: Apparently this has been a consistent issue with More Player Models for years, and is likely a problem on their end rather than an issue with the Dragon Survival mod.

**Comment by BlackAures1** [comment]
I think you need to write to the developers of those mods to add a config to disable features that break your game.

**Comment by Umbreeunix** [comment]
I will very soon, so hopefully it can get addressed. I mainly wrote here to give a heads up that this happens.

**Comment by seelderr** [comment]
Very old, closing as stale.
