### ISSUE TITLE
[Compatibility]: Corail tombstone Crashes after claiming inventory if there is any Claw tool.

### ISSUE THREAD

**Issue by 5stigma** [DragonSurvivalTeam/DragonSurvival#241]
### ■ Your Discord ID

Sstigma#8343

### ■ Dragon Survival version

Corail tombstone Crashes after claiming inventory if there are items equipped on the claw slot.

### ■ Minecraft version

1.18

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

When you die as a dragon with any tool compatible with Claw slot, and try to claim your grave the game crashes instantly.

a temporary solution would be: disable Auto-equipped in client-config for Corail tombstone

### ■ To Reproduce

1.- Install Corail Tombstone, DragonSurvival and GeckoLib.
2.- Obtain any tool compatible with the Claw slot (it doesn't matter if the item is in the inventory or in the Claw slot).
3.- KILL
4.- Go to claim your grave and use the key.
5.- CRRRRAAAASHHHH!! :'D

### ■ Crash Report

[crash-2022-12-24_15.44.19-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10299202/crash-2022-12-24_15.44.19-server.txt)

**Comment by BlackAures1** [comment]
Better use this mod - https://www.curseforge.com/minecraft/mc-mods/gravestone-mod 
It doesn't crash ^^

**Comment by 5stigma** [comment]
Yes, I know, but I like this one :'D .
Thanks, either way, I also opened an issue on the Corail Tombstone mod.

[https://github.com/Corail31/tombstone_lite/issues/122](url)

**Comment by BlackAures1** [comment]
This problem has been around for a very long time, I'm not sure it can be fixed quickly.

**Comment by 5stigma** [comment]
In these Christmas times, hope is the last to die.
Ok no, but thanks for your suggestion.
Happy holidays!!

**Comment by BlackAures1** [comment]
Is this compatibility promised by Horeak or what does it have to do with him?
