### ISSUE TITLE
[1.18.2 Forge Bug]: Broken air indicator

### ISSUE THREAD

**Issue by Bergimus** [DragonSurvivalTeam/DragonSurvival#242]
### ■ Your Discord ID

Bergimus#7114

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.5.38.jar (in curseforge it 1.4.38)

geckolib-forge-1.18-3.0.57.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Visual bug: sea dragons have an underwater air indicator, although it shouldn't be. People have 2 such indicators at once. The rest of the dragons are fine.

![2022-12-26_23 04 52](https://user-images.githubusercontent.com/102684537/209577181-7eaf156f-e283-4889-859c-bf792043a06d.png)
![2022-12-26_23 05 25](https://user-images.githubusercontent.com/102684537/209577184-544c7bfd-1164-4f6c-a053-a2f126af2de6.png)

### ■ To Reproduce

Simply jump into the water as human or sea dragon and see.

### ■ Expected behavior

Sea dragons shouldn't see air indicator in water, and humans shouldn't see this indicator twice.

**Comment by Horeak** [comment]
Partially fixed for now.
