### ISSUE TITLE
[1.18.2 Forge Bug]: Inverted magic sources

### ISSUE THREAD

**Issue by Bergimus** [DragonSurvivalTeam/DragonSurvival#244]
### ■ Your Discord ID

Bergimus#7114

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.5.38.jar (in curseforge it 1.4.38)

geckolib-forge-1.18-3.0.57.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Sea dragons gets damage with drowning sounds when standing on the sea source of magic. Other magic sources are fine. This happens regardless of whether it is charged or not.

### ■ To Reproduce

1. Put all the magic sources on the ground
2. Turn into sea dragon
3. Stand or walk on all of them
4. See half-heart damage every half of second and hear drowning sounds only on sea source
5. Charge all of sources with elder dragon heart
6. See that nothing changed

### ■ Expected behavior

All other types of dragons doesn't gets damage from their magic sources

**Comment by CvoidWyvern** [comment]
Noticed this same issue on this version, and that the other sources wouldn't damage sea dragons. Maybe some check was inverted.

**Comment by Bergimus** [comment]
I also noticed the fact that dragons can use all sources of magic except their own
