### ISSUE TITLE
[1.18.2 Forge Bug]: Unless Every Emote is Bound to a Key, Pressing the fn Key Will Make You Emote Even Though fn isn't Bound to Anything

### ISSUE THREAD

**Issue by Doublehelix13** [DragonSurvivalTeam/DragonSurvival#245]
### ■ Your Discord ID

Nova#5865

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.38

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

When I press F5 to go into third-person while playing as a dragon, I cannot go back into first-person no matter how many times I press F5.  It just keeps switching between front and back view in third-person.  I have to turn into a human to go back into first-person.

I also do an emote whenever I press F5 as a dragon, which is really annoying.

Edit:  After more testing, I found that the real problem was that pressing the fn key causes me to do an emote while playing as a dragon.  I do not have the fn key bound to any emote or anything else in-game.  If I bind the emote the fn key makes me do (I think it's the hugging and sitting emote) to some key other than fn, then pressing fn makes me do a different emote.  The only way around this that I've found is to bind every single emote to some key.  This prevents fn from making you emote and allows you to switch perspectives normally.  

I am using a Mac and on Mac, F1, F2, F3, and so on by default do things like adjust monitor brightness, change volume, etc.  To use them for other things like open the debug menu with F3 or change perspective with F5 while playing Minecraft, you must press the fn key as well.  This normally doesn't affect gameplay, at least for me it doesn't.  In this case, however, since pressing fn makes me do an emote and you can't go into first person while emoting, this makes it impossible to switch back to first person after using F3, F5, or any of the other F keys unless, as stated above, that every emote is bound to some other key.

I believe this happens with the 1.16.5 version of the game as well, though in that version doing an emote must not have prevented you from going into first person, so it didn't cause much trouble and I didn't think much of it.

### ■ To Reproduce

1. Turn into any kind of dragon.
2. Press F5 to go into third-person mode
3. Press F5 repeatedly to try to switch back to first-person mode

Edit:
1. Play a fresh instance with this mod and Geckolib installed on a Mac
2. Press fn
3. You will do an emote even with fn not bound to anything in-game and with every emote not bound to a key.

### ■ Expected behavior

Be able to switch back to first-person mode as you do while playing as a human.

Edit:  Pressing the fn key should not make you emote or do anything in-game.

### ■ Crash Report

N/A

**Comment by Umbreeunix** [comment]
If you do an emote every time you hit F5, what's likely happening is the emote is locking you out of 1st person PoV (which is something it does innately I believe). You'll want to stop emoting by either hit the air, sprint, etc., and then try hitting F5. It should let you go back to 1st person again.

Also I'd check your emote keybinds to make sure nothing was accidentally bound to the F5 key.

**Comment by BlackAures1** [comment]
I don't have a problem like that. Yes, I can't turn on the first-person view while playing the emotion, but you can cancel it simply by pressing the shift key. I don't see any problems with switching before and after.

**Comment by Doublehelix13** [comment]
I do not have any emotes bound to any key and yet for some reason the fn key, which I have to press to use F5 since I am on a Mac, makes me do an emote.  When I open the chat, open the dragon emotes menu, and click on "Keybinds", it shows every emote as "Not Bound".  I've also looked at the regular keybinds menu and don't see anything, for Dragon Survival or anything else, bound to the fn key, nor any Dragon Survival keybinds related to emoting in that menu.  That's why I can't go back into first person, even if I press shift to stop emoting.  I figured out what emote the fn key makes me do and bound it to another key, but then the fn key just makes me do a different emote.  I can't bind every emote to a key to try to make fn work; there's like 50 of them.  So the real question here is why in the world is the fn key making me do an emote when it isn't bound to anything?

**Comment by Doublehelix13** [comment]
It turns out that binding every emote to the same key allows fn to work and I can switch back to first person, so at least there's a workaround.  I still think that it's a bug that the fn key makes you do an emote when none of the emotes are bound to a key.

**Comment by seelderr** [comment]
This is very old. Going to close as stale for now.
