### ISSUE TITLE
[Compatibility]: server Apotheosis issue

### ISSUE THREAD

**Issue by MutantMiner300** [DragonSurvivalTeam/DragonSurvival#247]
### ■ Your Discord ID

Mootant#5859

### ■ Dragon Survival version

[Play as Dragon-1.14-RU_PL_ZH_EN]

### ■ Minecraft version

1.18

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

 Apotheosis versions don't "match" even though both are version 5.3.6. server boots up just fine, nobody can join. 

### ■ To Reproduce

use forge server version 40.2.0, install all mods from the pack except rubidium, rubidium_extras, oculus, Fancymenu and shutupexperimentalsettings on the server.

I use Bisecthosting but I have no idea if that will help

**Comment by BlackAures1** [comment]
logs

**Comment by MutantMiner300** [comment]
client side:
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10385822/latest.log)

Server side:
[latest(server).log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10385837/latest.server.log)

**Comment by BlackAures1** [comment]
Have you tried removing apotheosis?

**Comment by MutantMiner300** [comment]
no, I didn't. I dodn't know how much the pack relies on it
