### ISSUE TITLE
[Compatibility]: Cause of tombstone compatibility issue mentioned in #241

### ISSUE THREAD

**Issue by FirDragon** [DragonSurvivalTeam/DragonSurvival#249]
### ■ Your Discord ID

Srinater#8587

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.33 or laster

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

(translated from google) I have the same problem as #241 in my server, and the same crash file. Server crashes when users try to get drops from tombstones. From the crash file it can be seen that [CorailTombstone] failed trying to be compatible with [DragonSurvival]. [CorailTombstone] Attempts to get the [Claw and Fang] item using the [DragonStateHandler.getClawInventory] method. But it was renamed to [getClawToolData] after [DragonSurvival-1.18.2-1.5.33]. This caused [CorailTombstone] to crash because it couldn't find the [getClawInventory] method. I achieved compatibility by modifying the [CorailTombstone] jar. Is it possible to keep the [getClawInventory] method for compatibility with other mods?
* The modification from [getClawInventory] to [getClawToolData] comes from commit 2d2c843eb6783c50bcccb1a9388594749975cdaf

### ■ To Reproduce

Server crashes when user tries to get a drop from [CorailTombstone]'s tombstone(same problem as #241)

### ■ Expected behavior

Successfully obtained the item in the tombstone

**Comment by BlackAures1** [comment]
The Corail developer, for some unknown reason (https://github.com/Corail31/tombstone_lite/issues/122), is mad at us and there is no way I personally can fix this problem without breaking our own code, so sorry. If you need a tombstone mod, use https://www.curseforge.com/minecraft/mc-mods/gravestone-mod

**Comment by FirDragon** [comment]
> The Corail developer, for some unknown reason ([Corail31/tombstone_lite#122](https://github.com/Corail31/tombstone_lite/issues/122)), is mad at us and there is no way I personally can fix this problem without breaking our own code, so sorry. If you need a tombstone mod, use https://www.curseforge.com/minecraft/mc-mods/gravestone-mod

Sorry, I didn't notice this [issue]. I'm also working and often too busy to care about other things.-w-

**Comment by BlackAures1** [comment]
You don't have to know about it. It's okay. I just warned you :3

**Comment by Corail31** [comment]
@FirDragon even if the people here are just blaming to hide their ignorance and spreading rumors, you can still open an issue on my github, but it was tested to work with their latest version of 27th july 2024.
Also, note that my compatibility can't crash even if they change their code, so you're probably using an old version of Corail Tombstone (before they changed their capability).

**Comment by seelderr** [comment]
I'm thrilled by your increased interest in dragon survival @Corail31, but unfortunately for you I'm not closing these issues because we don't care about compatibility with your mod, I'm closing them because they are stale issues on old versions of the mod that are no longer being developed. I'd be happy to assist in fixing up any compatibility issues that arise in the version we are doing active development on (1.21) and _potentially_ port them down to 1.19/1.20 if they are trivial enough fixes. But again, your mod is closed source so it can be hard to figure out how to fix some of these issues.
