### ISSUE TITLE
[1.18.2 Forge Bug]:  (Modpack) Game crash after entering the Nether and rejoining the game

### ISSUE THREAD

**Issue by Anchewei** [DragonSurvivalTeam/DragonSurvival#253]
### ■ Your Discord ID

Anchewei#5871

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.40.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I'm playing with the modpack (Play as Dragon 1.14) as a sea dragon.
When I enter the Nether, everything is fine, but once I quit the game as usual and rejoined the world again, the game crashed when it was still loading the world.
[updated] Changing the personal in another world and back to the crashed one can solve the problem.

### ■ To Reproduce

(This problem may be not repeatable)
1. Enter the Nether
2. Quit the game
3. Region the world

### ■ Expected behavior

The game should not crash.

### ■ Crash Report

[crash-2023-01-14_16.40.28-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10417938/crash-2023-01-14_16.40.28-server.txt)

**Comment by BlackAures1** [comment]
Was this an isolated incident or can you repeat this error regularly?
