### ISSUE TITLE
[1.18.2 Forge Bug]: Dragon Survival breaks Cooking for Blockheads recipes 

### ISSUE THREAD

**Issue by Era4721** [DragonSurvivalTeam/DragonSurvival#255]
### ■ Your Discord ID

Era (SoNER)#9578

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.40.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I want to report a compatibility problem

### ■ Describe the bug

After adding the mod, the functionality of the Cooking for Blockheads blocks breaks (even with the recipes still existing in JEI, with the ingredients in hand, none will show in the stove top or cooking block)

### ■ To Reproduce

1) Install "Cooking for Blockheads" along with the Dragon Survival mod 
2) Try to make food with the CoB blocks

### ■ Expected behavior

Recipes should show up, and result in food items when interacted with, but the recipes themselves do not show up

**Comment by Era4721** [comment]
Apparently this might be the dragon type food evaluation mechanic (even as a human), but I don't see any config options to disable it (or parts of it)

**Comment by BlackAures1** [comment]
I've tested it and I don't see a problem.
![image](https://user-images.githubusercontent.com/43911230/214272430-8ab4a701-b8fd-4e1b-8811-3fb75fea6363.png)
![image](https://user-images.githubusercontent.com/43911230/214272013-f570e4a6-4a96-4b30-8e1a-bb379600cfc8.png)
