### ISSUE TITLE
[1.16.5 Forge Bug]: Astral Engineering modpack incompat

### ISSUE THREAD

**Issue by DestinyPlayer** [DragonSurvivalTeam/DragonSurvival#258]
### ■ Your Discord ID

DestinyPlayer#0787

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7.jar
geckolib-forge-1.16.5-3.0.93.jar
Forge - 36.2.34

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I wanted to try and add this mod to [Astral Engineering](https://www.curseforge.com/minecraft/modpacks/astral-engineering). I checked, and it's literally only this mod that breaks, when I remove it everything else functions.

When I try to generate a world with this mod active, it freezes on world generation, ending with this error and then stopping, not even generating a crash report. It says it does, but the crash-reports folder doesn't even pop into existence.
```
java.lang.IllegalStateException: No server set.
	at appeng.core.worlddata.WorldData.instance(WorldData.java:92)
	at appeng.core.AppEng.serverStopped(AppEng.java:218)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:124)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[09:30:49] [Server thread/ERROR] [minecraft/MinecraftServer]: java.lang.IllegalStateException: No server set.
```

I have tried several versions of GeckoLib, 93, 94, 96 and none of them worked.

### ■ To Reproduce

1. Install Astral Engineering 2.4.4
2. Add Dragon Survival 0.10.7 to it
3. Add GeckoLib 3.0.93 to it.
4. Launch game
5. Try to create a world
6. Wait
7. Game freezes, Minecraft Log is stuck on the aforementioned error.

### ■ Expected behavior

1. Install Astral Engineering 2.4.4
2. Add Dragon Survival 0.10.7 to it
3. Add GeckoLib 3.0.93 to it.
4. Launch game
5. Try to create a world
6. Wait
7. World gets created and I am loaded into it.

### ■ Crash Report

Fails to generate a Crash Report, so here's the Minecraft Log.
https://www.dropbox.com/s/g2xr2prwvwjbcrf/Dragon%20Survival%20Crash%20Log.txt?dl=0

**Comment by BlackAures1** [comment]
In general, I do not engage in advice on fixing someone else's modpack and can only suggest possible problems:
1. You installed DS incorrectly, forgot to delete old configs or something else.
2. In the modpack is a mod from the list of incompatible.
3. modpack uses new version of Gekkolib and some of the mod requires new version.

About points 1 and 2 you can read [here](https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update#--1165)

**Comment by DestinyPlayer** [comment]
Unfortunately, 1 and 3 are unlikely to be true.

With Gekkolib, I actually checked that the modpack still runs without Dragon Suvrival, so it does actually work with the version of Gekkolib I've installed for your mod.

With the mod itself, I checked that everything stated in the installation instructions has been done, Forge is beyond the recommended version, configs have been purged at least three times, I've checked several versions of Gekkolib, nothing.

In which case, I have to assume that the culprit is some unknown mod that isn't in the incompatibilities list. Guess it's the ol' "check it one by one" dance again.

Hopefully I'll be able to get back to you with what might be causing it more specifically.

**Comment by BlackAures1** [comment]
I would be grateful if you tell me which mod it is, because I certainly do not have the desire to check all the mods myself. In the logs indicated that there is a conflict with the food and dragon food tooltips.

**Comment by DestinyPlayer** [comment]
Okay, I've managed to narrow it down to what mod causes it. It's ChemLib ver. 1.16.5-1

https://paste.ee/p/s4j5Z - This here is a log from an instance that ONLY has:

chemlib-1.16.5-1.jar
DragonSurvival_DragonEditor-1.16.5-0.10.7.jar
geckolib-forge-1.16.5-3.0.97.jar

Running on:
Java 1.8.0_311
Forge 36.2.34

**Comment by DestinyPlayer** [comment]
In addition, I just tested chemlib-1.16.5-2.jar and apparently the issue has already been fixed on their side.

**Comment by BlackAures1** [comment]
I take it the "problem" is solved.
