### ISSUE TITLE
[1.16.5 Forge Bug]: Dragon Profile Reset

### ISSUE THREAD

**Issue by Sha7ique** [DragonSurvivalTeam/DragonSurvival#260]
### ■ Your Discord ID

Shalique#1467

### ■ Dragon Survival version

DragonSurvival 1.16.5-0.10.7

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

All of your dragons reset abilities and growth. In addition, items in the dragon inventory disappear.
This issue occurs when you are an adult dragon. Then, change into a human and relog afterward. 

### ■ To Reproduce

Yes. To repeat this error grow yourself into the adult stage. Next, change into a human. And relog after that. If needed, I can provide a recording of the bug.

### ■ Expected behavior

This wasn't expected. After discovering this issue, a couple of attempts were made to fix this bug however, the same result occurred.

### ■ Crash Report

None.

**Comment by BlackAures1** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update#-configuration
![image](https://user-images.githubusercontent.com/43911230/219319762-66807532-e376-416f-95b3-5daec087532e.png)
