### ISSUE TITLE
[1.18.2 Forge Bug]: Incorrect values of spell duration in config descriptions

### ISSUE THREAD

**Issue by toyi85** [DragonSurvivalTeam/DragonSurvival#261]
### ■ Your Discord ID

toyi85#7946

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.40

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Tested in singleplayer and LAN local server, the duration of all the buff skills is being calculated in ticks instead of seconds, so Tough Skin for example, that should last 60 minutes (3600 seconds), is lasting 3 minutes. The config file cannot help to fix it because the limit value is 10,000, and that is 8.3 minutes, still to short.

I also noticed the game didn't open the dragon altar interface when I first joined the world, I thought it was a new feature but checking the config the value says "startWithDragonChoice = true", so it seems to be a bug as well.

### ■ To Reproduce

Start a new world in SP and wait for the choice interface, it will not appear. Become any dragon breed and use the signature buff spell. Check the duration.

### ■ Expected behavior

I expected long lasting buffs, 10 minutes for the shortest (being forest dragon's "Hunter"), I got 30 seconds of that buff.

**Comment by BlackAures1** [comment]
![image](https://user-images.githubusercontent.com/43911230/228690518-10ece611-8802-4a9e-bcb6-f91740010425.png)
duplicate + info

**Comment by Umbreeunix** [comment]
To expand on that more, some of the cooldown configs are being read in ticks, while others have the 600 second=1 minute cooldown. Something seems to have messed up a lot of them, as none of the buff abilities seem to have the correct values.
