### ISSUE TITLE
[1.16.5 Forge Bug]: 

### ISSUE THREAD

**Issue by MadRenegade45** [DragonSurvivalTeam/DragonSurvival#262]
### ■ Your Discord ID

MadRenegade#2009

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

The game crash when I try to open the dragon editor and the dragon altar.
So I use the command, but I am invisible.

### ■ To Reproduce

1. Try to opens a dragon altar, or use the command in the chat, or try to go in the dragon editor by opening the inventory.
2. And the game should crash

### ■ Expected behavior

Make the game stop crash.

### ■ Crash Report

[crash-2023-02-21_11.55.56-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10792920/crash-2023-02-21_11.55.56-client.txt)
[crash-2023-02-21_10.50.24-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10792921/crash-2023-02-21_10.50.24-client.txt)
[crash-2023-02-21_10.48.36-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10792922/crash-2023-02-21_10.48.36-client.txt)
[crash-2023-02-21_10.35.39-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10792923/crash-2023-02-21_10.35.39-client.txt)
[crash-2023-02-21_10.32.23-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/10792924/crash-2023-02-21_10.32.23-client.txt)

**Comment by BlackAures1** [comment]
Simply read the installation instructions.

**Comment by MadRenegade45** [comment]
Thanks it work now, I just got the wrong version of geckolib 😅.
