### ISSUE TITLE
[1.18.2 Forge Bug]: Items randomly stop stacking.

### ISSUE THREAD

**Issue by NotAPotter** [DragonSurvivalTeam/DragonSurvival#263]
### ■ Your Discord ID

PonyPon#2838

### ■ Dragon Survival version

[DragonSurvival-1.18.2-1.5.40.jar]

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Items seemingly at random stop stacking and won't restack when you add them to inventory, even with the sorting button. They can also show up in the hotbar even if ones are already in your inventory.

### ■ To Reproduce

There's no specific way that this happens, just anytime while gathering some of the same item.

### ■ Expected behavior

I expect items that are stackable to stack, and items in the inventory to be gathered there rather in the hotbar.

**Comment by BlackAures1** [comment]
It's a bug with the item gui mod and its library. They don't update their mod for a long time and I will probably delete it.
