### ISSUE TITLE
[1.16.5 Forge Bug]: Profile Reset

### ISSUE THREAD

**Issue by Sha7ique** [DragonSurvivalTeam/DragonSurvival#264]
### ■ Your Discord ID

Shalique#1467

### ■ Dragon Survival version

DragonSurvival 1.16.5-0.10.7

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Notes:
Issue #1: saveAbilities fail to save abilities when set to true while saveGrowth is set to false
Issue #2: Everything gets reset when relogging as human
Issue #3: Items in dragon slots get deleted when relogging as human

This is a continuation of the bug that was previously reported by me.

### ■ To Reproduce

Replicating Issue #1: Set saveAbilities to true and saveGrowth to false.
Replicating Issue #2: Set your growth stage and upgrade skills. Then relog as human.
Replicating Issue #3: Put any item in either dragon slot and relog as human.

### ■ Expected behavior

I expected the abilities to save when saveAbilities was set to true though saveGrowth was set to false. However, that didn't happen. As for the rest of the issues, I don't even know. Server configurations were doubled checked by me and the server owner.

**Comment by BlackAures1** [comment]
Why duplicate bugs that already have a report? They won't be fixed any faster because of that.

**Comment by Sha7ique** [comment]
> Why duplicate bugs that already have a report? They won't be fixed any faster because of that. And 1 bug 1 report.

Previous bug I reported you responded with a screenshot of configs for dragonsurvival. I included a bit more detail in this one to show it wasn't because we failed to check configurations. Part of the issue was that the configs failed to follow through with some of the code.
