### ISSUE TITLE
[1.18.2 Forge Bug]: foldWingsOnLand Server Setting Doesn't Work 

### ISSUE THREAD

**Issue by Umbreeunix** [DragonSurvivalTeam/DragonSurvival#266]
### ■ Your Discord ID

Umbreeunix#6904

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.40.jar
geckolib-forge-1.18-3.0.57.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Landing while foldWingsOnLand is set to true has no effect on a dragon's wings. Their wings will remain open regardless of what dragon you are or what method you use to land.

### ■ To Reproduce

1. Set foldWingsOnLand to true in server settings
2. Fly around and land
3. Wings will remain open after landing, even if you remain motionless

### ■ Expected behavior

Landing with foldWingsOnLand set to true will have the wings fold properly without having to input the command manually.

**Comment by Umbreeunix** [comment]
**Some clarifications after further testing:**
- _this bug seems to only effect Survival mode_
- _for some reason, "foldWingsOnLand=true" seems to work perfectly fine in Creative 
- _in Survival, the wings only fold when I'm forced to land due to low stamina/hunger_

It might be easier to set the wings to a shorter duration (5-10 seconds) that only counts down when a dragon touches the ground, but resets if they get back in the air before the timer reaches 0. (at which point the dragon 'folds its wings' and the flight effect ends) I'm not sure though, as I'm sadly not a programmer.

**Comment by BlackAures1** [comment]
foldWingsOnLand works very badly, so it is disabled by default.

**Comment by FirDragon** [comment]
It has been fixed and will be applied in the new version.
