### ISSUE TITLE
[1.18.2 Forge Bug]: The dragon's appearance is not saved after using the altar.

### ISSUE THREAD

**Issue by FirDragon** [DragonSurvivalTeam/DragonSurvival#267]
### ■ Your Discord ID

Srinater#8587

### ■ Dragon Survival version

1.18.2-github current latest version https://github.com/DragonSurvivalTeam/DragonSurvival/commit/8dd9ea720ada84d282e07f6240e09e8fe228a959

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

I tried to reproduce this problem, but I failed. It can always be modified successfully. Or maybe my approach is wrong.

### ■ To Reproduce

1. Open the altar UI
2. Modify the appearance of the dragon
3. Replicate the appearance to all growth stages
4. Select the second card slot
5. Perform operations 2 and 3 again
6. Save and use the appearance
7. Open the altar again, select the first card slot
8. Save and use the appearance
There seems to be no issues throughout the steps

### ■ Expected behavior

Successfully reproduce the bug.

**Comment by BlackAures1** [comment]
![Screenshot_20230307-150826_Browser](https://user-images.githubusercontent.com/43911230/223416227-dbcfc48e-5343-4747-a14d-027915165c14.jpg)

**Comment by FirDragon** [comment]
I'd be happy to help you, I'm trying to find the cause of this problem but I don't have a way to trigger it yet. qwq

**Comment by FirDragon** [comment]
I followed the above steps to test, but did not reach the effect of the bug. xwx

**Comment by BlackAures1** [comment]
You need to delete the dragon-survival folder where the customization is saved. So that the mod is installed on a clean version of the game. After that, when you try to save the appearance of the player rolls back 1 appearance. That is, here you have created appearance 1, it is not saved, you went to the altar and created appearance 2, it is also not saved, but appeared appearance 1.

**Comment by FirDragon** [comment]
thanks i will try.
