### ISSUE TITLE
[1.18.2 Forge Bug]: Saturation still bugged (cont. Issue #246)

### ISSUE THREAD

**Issue by Umbreeunix** [DragonSurvivalTeam/DragonSurvival#269]
### ■ Your Discord ID

Umbreeunix#6904

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.40.jar
geckolib-forge-1.18-3.0.57.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Eating from your dragon's diet now gives the correct food values, even after eating the wrong things, but still doesn't provide Saturation. So the hunger bar instantly depletes unless your dragon keeps constantly eating.

### ■ To Reproduce

1. Eat something that's outside your dragon's diet
2. Wait for hunger effect to pass, then eat the correct food
3. Your belly will be filled by the correct amount but you'll receive no saturation
4. Die to reset this bug

### ■ Expected behavior

Eating food part of your diet provides correct food values AND saturation, even after eating the wrong foods..

**Comment by FirDragon** [comment]
This problem has been fixed in the 1.18.x branch on github, but because there are some other problems on this branch, there is no release version yet.

**Comment by FirDragon** [comment]
https://user-images.githubusercontent.com/45531183/223906557-651edd3f-aa72-4be8-9f4e-f9cecf70e027.mp4

**Comment by Umbreeunix** [comment]
> This problem has been fixed in the 1.18.x branch on github, but because there are some other problems on this branch, there is no release version yet.

Oh my bad! I hadn't noticed that and, after some of my own testing, I see that the bug has been completely fixed with the newest release. 

I'm very sorry, I'll close this issue since it's been resolved. Thank you for the reply. ^^)b
