### ISSUE TITLE
[1.18.2 Forge Bug]: No ocean Monuments

### ISSUE THREAD

**Issue by LatiasandLatios** [DragonSurvivalTeam/DragonSurvival#270]
### ■ Your Discord ID

Latias/Gogoat#1205

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.41.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

I tried searching for ages to find an ocean monument to find guardians and found none. Whenever i use the /locate command to force find a location the game hangs. This leads me to believe that the map generation wont spawn any ocean monuments. I can use that same command to find other generated structures. If this is intentional then please provide a description on where to find guardians to complete the kill quest/find prismarine. Also unable to force spawn any monuments using /structure_gel

### ■ To Reproduce

type with cheats active
/locate minecraft:monument

### ■ Expected behavior

you get a location of the nearest monument

### ■ Crash Report

Game doesnt crash just is stuck perpetually in "waiting for server"

**Comment by BlackAures1** [comment]
fixed
