### ISSUE TITLE
[1.18.2 Forge Bug]: Texture Missing for Sea Dragon Claws Ability

### ISSUE THREAD

**Issue by Umbreeunix** [DragonSurvivalTeam/DragonSurvival#272]
### ■ Your Discord ID

Umbreeunix#6904

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.41.jar
geckolib-forge-1.18-3.0.57.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

The texture for Sea Dragon claws on the ability menu go missing after reaching the Adult growth stage. I'm not sure if this is a conflict with other mods, I haven't tested Dragon Survival itself for this bug.

I also noticed two Sea Dragon texture files in the [Forest Dragon's](https://github.com/DragonSurvivalTeam/DragonSurvival/tree/v1.18.x/src/main/resources/assets/dragonsurvival/textures/skills/forest) skill folder, 'sea_claws_and_teeth_6.png' and 'sea_claws_and_teeth_7.png'. Despite the names, both are duplicates of a Forest Dragon claw skill texture. I don't know if this could be causing a conflict, but I thought I should mention it.

**Broken texture in game:**
![image](https://user-images.githubusercontent.com/80364214/225128877-7000374c-767b-4a0d-af70-776a4af523ee.png)

### ■ To Reproduce

1. Spawn/set species to Sea Dragon
2. Grow to the adult stage (and possibly get to level 40-50)
3. Check abilities and find the claw texture missing

### ■ Expected behavior

Checking Abilities has the textures for each of the Sea Dragon's skills rendering properly.

**Comment by Umbreeunix** [comment]
**Something else to note in the Ability texture files:**
The 'claws_and_teeth' textures for the Sea Dragon also don't follow the same number format that Cave and Forest do. The textures go from 1-7 instead of 0-6. Not only that, but the Sea Dragon has no 'inactive' texture for its claws/teeth. (the one that's greyed out) Instead there's an extra level with a purple colored shovel.

Still not sure if this could be contributing to textures being missing in game but I just wanted to give a heads up just in case.

**Comment by Umbreeunix** [comment]
Okay after rigorous testing I understand this issue more:

What's happening is Dragon Survival is trying to pull textures that match modded tool ores, but it doesn't have them. So it comes up as a missing texture instead. (Example: Sea Dragon equips a silver shovel, the texture comes back as missing because Dragon Survival doesn't have a Silver shovel texture in its ability files)

It might be a good idea to set a default texture or create a custom texture that would apply ALL modded tools.

**Comment by BlackAures1** [comment]
Do you only have this happen with a modified tool and only with a sea dragon?

**Comment by Umbreeunix** [comment]
From what I've seen, this happens to Cave Dragon pickaxe and Sea Dragon shovel. I haven't tested Forest Dragons.

And yes, textures are only missing when equipping a modded tool in the Claw Slot, vanilla Minecraft tools bring up the correct textures.

**Comment by FirDragon** [comment]
Thanks for the tip, this issue will be fixed soon
