### ISSUE TITLE
[1.18.2 Forge Bug]:  dragon mission book is lost among gravesite deaths cant find the book is this a bug? cant continue quests

### ISSUE THREAD

**Issue by berserkervalk209** [DragonSurvivalTeam/DragonSurvival#273]
### ■ Your Discord ID

Berserkervalk209#6443

### ■ Dragon Survival version

Play as Dragon-1.15_RU_PL_ZH_EN.zip

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

 dragon mission book is lost among gravesite deaths can't find the book in inventory anymore. is this a bug? is it lost in one of the death graves at the nether world area? cant continue quests might restart seed if worst comes to worse.

### ■ To Reproduce

dragon mission book is lost among gravesite deaths can't find the book in inventory anymore. is this a bug? is it lost in one of the death graves at the nether world area? cant continue quests might restart seed if worst comes to worse.

### ■ Expected behavior

dragon mission book is lost among gravesite deaths can't find the book in inventory anymore. is this a bug? is it lost in one of the death graves at the nether world area? cant continue quests might restart seed if worst comes to worse.

### ■ Crash Report

no memory

**Comment by BlackAures1** [comment]
Quests can be opened via the J button

**Comment by berserkervalk209** [comment]
thanks found it







On Thursday, March 23, 2023 at 05:46:50 AM PDT, Viktoria Ershova ***@***.***> wrote: 







Closed #273 as completed.
