### ISSUE TITLE
[1.16.5 Forge Bug]: Unable to select human race, crashes hovering over the option. 

### ISSUE THREAD

**Issue by BeyondTheHidden** [DragonSurvivalTeam/DragonSurvival#277]
### ■ Your Discord ID

BeyondTheHidden#1199

### ■ Dragon Survival version

DragonSurvival_DragonEditorUpdate 0.10.7 (server +) 1.16.5 !!! WORK ONLY WITH 3.0.93 GeckoLib !!!

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Whenever I hover over the human option in the selection screen it crashes immediately. This happens if im a human or dragon.

### ■ To Reproduce

It has happened every time I have tried consistently.

### ■ Expected behavior

To be able to turn back into a human.

### ■ Crash Report

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world

**Comment by BlackAures1** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update
![213123123цукцук](https://user-images.githubusercontent.com/43911230/233215109-2d778a3b-69c1-4108-83b2-40679418f7d7.png)
