### ISSUE TITLE
[1.18.2 Forge Bug]: Game crashes upon opening

### ISSUE THREAD

**Issue by TuffCat** [DragonSurvivalTeam/DragonSurvival#282]
### ■ Your Discord ID

embee#5457

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.42

The geckolib version as well:
geckolib-forge-1.19.3-4.0.6

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

When clicking play, the game tries to open but immediately crashes.

### ■ To Reproduce

Download the 1.4.42 of DS, download the 4.0.6 in 1.19.3 version of Geckolib, install the stable version of forge 1.18.2, 40.0.2, put DS and geckolib into the mods folder, and try to run 1.18.2 forge in the default minecraft launcher.

### ■ Expected behavior

I expect the game to be able to run.

### ■ Crash Report

[crash-2023-05-07_12.37.38-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/11415535/crash-2023-05-07_12.37.38-client.txt)

**Comment by FirDragon** [comment]
You may need to download version 1.18.2 of geckolib instead of 1.19.3.
