### ISSUE TITLE
[1.18.2 Forge Bug]: Severe memory leak due to constant initialisation of classes.

### ISSUE THREAD

**Issue by Whanos** [DragonSurvivalTeam/DragonSurvival#293]
### ■ Your Discord ID

protocol#6464

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.42.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

The mod has a serious memory leak in the code - causing the mod to allocate many gigabytes of data, only ever being cleared by the GC. This is due to hundreds of thousands of copies of classes being instantiated.

The bug is due to [this class](https://github.com/DragonSurvivalTeam/DragonSurvival/blob/82102535c31ca7e19f03ce3f928ec69f2f5e9d2f/src/main/java/by/dragonsurvivalteam/dragonsurvival/client/skin_editor_system/objects/LayerSettings.java) being instantiated [hundreds of thousands of times.](https://cdn.gls.cx/165a696b16579eef)

Said class is instantiated by [this code](https://github.com/DragonSurvivalTeam/DragonSurvival/blob/82102535c31ca7e19f03ce3f928ec69f2f5e9d2f/src/main/java/by/dragonsurvivalteam/dragonsurvival/client/skin_editor_system/objects/SkinPreset.java#L64-L104) seemingly [many times every single tick](https://cdn.gls.cx/38d668b7ee6f7e1b) , meaning that you are [instantiating an insane amount of the same class.](https://cdn.gls.cx/d87c967f9b584048)

Ultimately, the issue is seemingly caused by [this class.](https://github.com/DragonSurvivalTeam/DragonSurvival/blob/82102535c31ca7e19f03ce3f928ec69f2f5e9d2f/src/main/java/by/dragonsurvivalteam/dragonsurvival/common/capability/DragonStateHandler.java)

I **strongly** suggest [looking at this section of code](https://github.com/DragonSurvivalTeam/DragonSurvival/blob/82102535c31ca7e19f03ce3f928ec69f2f5e9d2f/src/main/java/by/dragonsurvivalteam/dragonsurvival/common/capability/DragonStateHandler.java#L36C8-L48) and caching this data, or at least severely reduce the amount of times you instantiate said data.

It appears one of your developers possibly knew about the severity of this issue [four months ago.](https://github.com/DragonSurvivalTeam/DragonSurvival/blame/82102535c31ca7e19f03ce3f928ec69f2f5e9d2f/src/main/java/by/dragonsurvivalteam/dragonsurvival/common/capability/DragonStateHandler.java#L38)

This causes serious repeating performance issues on servers with limited RAM, as combined the mod can use almost 4GB of RAM at its peak - before the unused classes get wiped out of the heap by the GC.

### ■ To Reproduce

1) Install the mod onto a forge server (I have not tested on single-player).
2) Become a dragon.
3) Profile the game [after enabling JMX.](https://docs.oracle.com/javadb/10.10.1.2/adminguide/radminjmxenabledisable.html) using VisualVM or similar.
4) [Watch your memory allocation graph go wild.](https://cdn.gls.cx/1b230d524bb034e3)

### ■ Expected behavior

It not leaking memory.

**Comment by FirDragon** [comment]
Thank you very much for your issue, I will try to solve this problem as soon as possible.

**Comment by BlackAures1** [comment]
I will also complete this with one message from the discord server. Yesterday I tried to make a quick fix for this problem, but alas, it requires more complicated work. Thank you very much for your very detailed report.
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/e384d4d3-915b-4554-a5fb-d38e9f24290d)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/ddb2cd3d-6fc6-459a-bd97-c5c8c80a75a5)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/f8f40c12-3e56-4cf8-9b30-1a2cea82711f)
