### ISSUE TITLE
[1.18.2 Forge Bug]: Claw items do not obey any death related enchantments

### ISSUE THREAD

**Issue by joeyjumper94** [DragonSurvivalTeam/DragonSurvival#294]
### ■ Your Discord ID

joey_#3699

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.42.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

items attached to dragon claws do not obey death related enchantments
items with curse of vanishing are dropping
items with soulbound from corail tombstone's soulbound are dropping

### ■ To Reproduce

to replicate curse of vanishing
give yourself a tool that can be attached to dragon claws,
enchant it with minecraft:vanishing_curse
attach it to your claws
die
the item has dropped instead of vanishing

to replicate the issue with corail tombstone's soulbound enchantment, you need the mod corail tombstone
give yourself a tool that can be attached to dragon claws,
enchant it with tombstone:soulbound
attach it to your claws
die
the item has dropped into a grave rather than staying on your claws

### ■ Expected behavior

items that have minecraft:vanishing_curse are supposed to disappear when you die
and items that have tombstone:soulbound are supposed to not drop when you die

**Comment by FirDragon** [comment]
Thanks, this is a known issue.

**Comment by seelderr** [comment]
Closing due to staleness and out of support version

**Comment by Corail31** [comment]
@joeyjumper94 The only reason is because their drops really too late in the drop event (it should be in highest priority) so, their mod is probably incompatible with lots of soulbound enchantment. If you open an issue on my github, i could provide a second check when this mod is present in lower priority of the event).

**Comment by seelderr** [comment]
003c3295
