### ISSUE TITLE
[1.18.2 Forge Bug]: Play as Dragon - Game Crashed then turned into a human.

### ISSUE THREAD

**Issue by MoonRabbt** [DragonSurvivalTeam/DragonSurvival#297]
### ■ Your Discord ID

MoonRabbit#5374

### ■ Dragon Survival version

Mod version: DragonSurvival-1.18.2-1.5.42.jar

Modpack version: Play as Dragon-1.15_RU_PL_ZH_EN.zip

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I opened the modpack to continue playing, my game crashed. I reopened it and the game was perfectly working, except that I turned into a human. I tried using the dragon alter to turn back into a dragon, but all my abilities and age were reset to 0.

My items, levels, and armor were all fine, so it's not like I died. The only items that disappeared were the tools in my dragon tab hotbar thing.

### ■ To Reproduce

Not repeatable, just happened randomly.

### ■ Expected behavior

Stay a dragon.

### ■ Crash Report

[crash-2023-05-16_15.49.20-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/11492121/crash-2023-05-16_15.49.20-server.txt)

**Comment by FirDragon** [comment]
Can you describe in detail what you were doing at the time?

**Comment by FirDragon** [comment]
before the crash.

**Comment by FirDragon** [comment]
Can you still access that archive?The villager stepped on a crop block, and the drop failed to generate, and the coordinates were around 1350.50, 68.00, -684.81

**Comment by FirDragon** [comment]
Can you help me find out what kind of crop it is?

**Comment by MoonRabbt** [comment]
In detail what I was doing before I logged off was making sails for the create windmill. So I was gathering wool and cutting trees. I was also testing and trying to figure out how to use the create mod so I had some of the basic starting items around. 

The coords are directly over a grass block with a seed on the ground. I'm assuming it was a wheat plant before the villager stepped on it. The villagers' farm is only 16 blocks x away from the windmill I was working on if that matters any. I'm not sure if it was because I was loading that area for so long while building or if it was because of the build itself.
