### ISSUE TITLE
[1.18.2 Forge Bug]: FPS drop

### ISSUE THREAD

**Issue by StrunVul** [DragonSurvivalTeam/DragonSurvival#300]
### ■ Dragon Survival version

Any version.

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Why rendering of dragon model still making FPS drop? Even without other mods this mod making drop FPS. Annoying to play in multiplayer, because when you see other player in dragon form FPS drop too, and if more players, then more down FPS.
Anyway even in single player this happens too when you look down and see your body, or open inventory or in third person mode.
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/98702339/2d56838e-a1ee-4c33-b846-0d8898f1d1e0)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/98702339/bb350d50-a094-4878-9fa4-d49c994594c5)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/98702339/32f0d6f4-e9bd-4335-af85-12fe0482b1d8)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/98702339/00e7a87f-5f78-4e18-92d1-296efa67ebff)
To more see changes, i turn on V-Sync
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/98702339/4f0bb502-faf9-4030-aeec-6514373a99c4)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/98702339/e40aa5d6-2e53-4c59-bc7f-789a5af1c4c1)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/98702339/cdb2abfa-c82e-40fd-8a51-a9082482f5d9)

### ■ To Reproduce

Just change view in third person with opened F3 and it's will be visible. Or open inventory or look down.

### ■ Expected behavior

Expected to make a nice adventure, but it lagging adventure.

**Comment by FirDragon** [comment]
The reason is described in #293

**Comment by FirDragon** [comment]
Repair is being verified

**Comment by StrunVul** [comment]
> Repair is being verified

And how fixing going?

**Comment by BlackAures1** [comment]
> > Repair is being verified
> 
> And how fixing going?

This is a very complicated and old bug. We can't fix it with a couple lines of code and it needs more time to work. Keep an eye out for patches.

**Comment by StrunVul** [comment]
> > > Repair is being verified
> > 
> > 
> > And how fixing going?
> 
> This is a very complicated and old bug. We can't fix it with a couple lines of code and it needs more time to work. Keep an eye out for patches.
Okay, then we everyone will wait that fix.
