### ISSUE TITLE
[1.19.2 Forge Bug]: saveAllAbilities

### ISSUE THREAD

**Issue by Fedricknun** [DragonSurvivalTeam/DragonSurvival#319]
### ■ Your Discord ID or other contacts

Federico4#0254

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival 1.5.47 - 1.19.2 

### ■ Single game or server?

Local network (LAN, Hamachi, etc.)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

#Whether to save passives skills when changing dragon type
		saveAllAbilities = true [Not working lan trying with 4 people]

#Should the growth stage of a dragon be saved even when you change. Does not affect the saving progress of magic (use saveAllAbilities). The author does not approve of weredragons, but if you insist...
	saveGrowthStage = true [Not working too even with patch fixes lan]

### ■ Expected behavior

SaveAllAbilities = Saving abilities after getting back as human.

saveGrowthStage = saving the size of the dragon after getting back as human.

### ■ Crash Report File and Logs

Nothing only fps drops but no crash.

**Comment by FirDragon** [comment]
Thanks for your submission, can you elaborate on what happens when saveAllAbilities is turned on?

**Comment by SiverDX** [comment]
Saving growth is currently not implemented:
https://github.com/DragonSurvivalTeam/DragonSurvival/blob/d198ff06fd04019cd3cb5650a9d98d4ff7db97ad/src/main/java/by/dragonsurvivalteam/dragonsurvival/common/capability/DragonStateHandler.java#L310

**Comment by Fedricknun** [comment]
Weird for me is not working Saving abilities?
and for Saving growth sad is not implemented.

**Comment by SiverDX** [comment]
Did you switch to human, leave the world and then join back?
NBT data for the dragon currently only gets saved if... you're a dragon

Meaning if you switch to human and leave the world it's gone
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22003703/67dd965c-8ef7-4638-bc9a-6edd7609c2fb)

**Comment by FirDragon** [comment]
I'm going to bed, I'll fix it tomorrow

**Comment by SiverDX** [comment]
You have a lot of DragonStateHandlers
Most of them have size 0.0, seem to be empty / unused

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22003703/5b89b66d-715b-431e-9ad8-ee0216b760c5)

There are two different DragonStateHandlers which interact with `setSize` e. g. though (and have an up-to-date value)

**Comment by FirDragon** [comment]
> 你创建了很多 DragonStateHandlers 其中大部分的大小为 0.0，似乎是空的/未使用的
> 
> ![图像](https://user-images.githubusercontent.com/22003703/243842672-5b89b66d-715b-431e-9ad8-ee0216b760c5.png)
> 
> 有两个不同的 DragonStateHandlers 与`setSize`eg 交互（并且具有最新值） （全部在 Singeplayer 上）

Yes, #300 did emergency mitigations, but still need to continue to optimize

**Comment by FirDragon** [comment]
> 

This issue has been fixed, as for saveGrowthStage, it needs to be put on hold for a while, because there are other fixes in progress

**Comment by SiverDX** [comment]
You're attaching capabilities to mobs and Item Entities:
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22003703/f476cfd1-97e7-4edb-a869-906cb4233dfd)

In `Capabilities` - `attachCapabilities` you should maybe check if `event.getObject()` returns a `Player`

**Comment by FirDragon** [comment]
yes, that's the question

**Comment by FirDragon** [comment]
It has many calling sources
I can't make sure that changing all of them to if(has)+get will not cause new problems, so I use lazy loading to alleviate it temporarily.

**Comment by FirDragon** [comment]
I'm also new to this project, so I'd better make major changes after I fully understand

**Comment by FirDragon** [comment]
At least it looks like it was returning null instead of new
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/45531183/6bc70d65-608b-4748-a828-57740b5119aa)

**Comment by SiverDX** [comment]
Not sure what you mean with that, the warning is there because it never returns `null`

```  java
return entity != null ? DragonStateProvider.getCap(entity).orElse(new DragonStateHandler()) : new DragonStateHandler();
```

---

Could maybe introduce a smaller state with just `lastPos` and `lastAfflicted` for entities which are not Players

---

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L86

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#LL112C10-L112C10

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L143

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L161

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L170

You could check for players here first to avoid the call  to the capability, since they are only relevant for Dragons

**Comment by FirDragon** [comment]
I guess it used to return null, but for some reason, it has now become new, and I dare not go back directly, because I don't know why it was changed to this at the time.

**Comment by FirDragon** [comment]
I can only do some fixes that I'm sure won't produce problems

**Comment by FirDragon** [comment]
> 

I will fix these first

**Comment by FirDragon** [comment]
> Not sure what you mean with that, the warning is there because it never returns `null`
> 
> ```java
> return entity != null ? DragonStateProvider.getCap(entity).orElse(new DragonStateHandler()) : new DragonStateHandler();
> ```
> 
> or do you mean how it was in a previous version?
> 
> Could maybe introduce a smaller state with just `lastPos` and `lastAfflicted` for entities which are not Players
> 
> https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L86
> 
> https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L112
> 
> https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L143
> 
> https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L161
> 
> https://github.com/DragonSurvivalTeam/DragonSurvival/blob/7872adde6148eb820f0e8779251e36f1265daa77/src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinLivingEntity.java#L170
> 
> You could check for players here first to avoid the call to the capability, since they are only relevant for Dragons

I will fix these first

**Comment by FirDragon** [comment]
Thanks for your willingness to spend time on this

**Comment by Fedricknun** [comment]
Got banned without a reason need to ask why? without any report and msg if is possible to understand what was the problem thanks.

Please i need to understand if it was the thing i say about dont support Stabx mod is racist want to know.

**Comment by Fedricknun** [comment]
And phone number too?

**Comment by Fedricknun** [comment]
I joined that discord because I liked her mod, and maybe I shouldn't have because they don't have a good community, it wasn't my intention to offend anyone just to prevent other people from going into that discord unprepared. Honestly the comments on that discord were racist but if not I apologize.

**Comment by Fedricknun** [comment]
I Dont talk about this MOD.

**Comment by BlackAures1** [comment]
DeepL to help if you don't understand Russian. 
Для тех кто не понимает что происходит: автор этого багрепорта хотел устроить драму на моём сервере, связанную с каким-то рандомным разработчиком малоизвестного мода, чтобы привлечь к нему внимание. Он был забанен у меня на сервере за этот акт рекламы, но начал писать спам на других площадках, в том числе и тут.

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/cebf6ebc-c8f7-4fa0-a393-e4fe923fa2cd)

Зачем вы удалили ваши замечательные сообщения? Давайте обсудим это, если вы не понимаете за что вас забанили.
 
1. Любые публичные заявления о другом человеке без пруффов это **клевета**. Я ненавижу клевету. Вы опубликовали своё сообщение на нескольких серверах и не удосужились объяснить это. Только после того как вас забанили, вы связались по какой-то причине не со мной, а со случайными людьми на моём сервере. 

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/458e7d3b-6352-42f6-88d9-1282852bde56)

2. Ваши отношения с Stabx guns не имеет к нашему сообществу никакого отношения. Вы рандомный человек, который оставил рандомное заявление о другом рандомном человеке, которого даже нет на нашем сервере. Этого мода также нет на нашем сервере и мы без понятия о ком вы кричали. Другие пользователи проверили ваше заявление и это было правдой, но почему они должны сами искать доказательства ваших слов и беспокоиться об этом? Вот скриншот из сервера Stabx guns, в котором говорится об Анти-ЛГБТ. **Dragon Survival и я не имеем в этому никакого отношения.**

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/f4bbb08d-0d5a-4ee4-a51a-cb92305a43c2)

3. Ваше сообщение больше похоже на черный пиар или культуру отмены. Мой сервер не место для такого дешевого развлечения. Stabx guns это маленький мод от [маленького разработчика](https://legacy.curseforge.com/members/stabilizer_king/projects), до которого никому нет дела, но своими криками вы привлекаете ему аудиторию и рекламируете его. Это то чего вы хотели добиться? Если да, то ваш бан у меня заслуженный, а если нет, то вы просто глупец, но это простительно.

4. Я проверил другие общие сервера на которых вы писали (вас везде забанили теперь?). Другие люди также сказали вам прекратить этот пустой спам.

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/e6096ab8-ec9e-4b57-92fd-4fc1f1a5e129)

5. Какое отношение этот  багрепорт имеет к той драме, которую вы пытаетесь сейчас создать? Вам нужно публичное внимание? Вы могли просто написать мне в личные сообщения с объяснениями (мои сообщения открыты).

**Comment by Fedricknun** [comment]
ачем вы удалили ваши замечательные сообщения? Давайте обсудим это, если вы не понимаете за что вас забанили.                   
I Wanted to express better my msg of all of this stuff im not very good at english.

Ваши отношения с Stabx guns не имеет к нашему сообществу никакого отношения. Вы рандомный человек, который оставил рандомное заявление о другом рандомном человеке, которого даже нет на нашем сервере. Этого мода также нет на нашем сервере и мы без понятия о ком вы кричали. Другие пользователи проверили ваше заявление и это было правдой, но почему они должны сами искать доказательства ваших слов и беспокоиться об этом? Вот скриншот из сервера Stabx guns, в котором говорится об Анти-ЛГБТ. Dragon Survival и я не имеем в этому никакого отношения

Yes I know I was wrong about sending the text on your server with the name of the mod was only to get a lot of people to avoid the discord of that mod who are like me feel insulted.

Ваше сообщение больше похоже на черный пиар или культуру отмены. Мой сервер не место для такого дешевого развлечения. Stabx guns это маленький мод от [маленького разработчика](https://legacy.curseforge.com/members/stabilizer_king/projects), до которого никому нет дела, но своими криками вы привлекаете ему аудиторию и рекламируете его. Это то чего вы хотели добиться? Если да, то ваш бан у меня заслуженный, а если нет, то вы просто глупец, но это простительно.

I Don't wanted To publish  Stab Guns it was not my intention human's do sometimes mistake and yes mine is a real big one

Я проверил другие общие сервера на которых вы писали (вас везде забанили теперь?). Другие люди также сказали вам прекратить этот пустой спам.

No, the servers i just sent msg was only three where I explained the mistake of saying the mod name i had really good intention, Not banned Some servers U think I spammed was only to give some bugs report and fixes of course not these three ones.

Какое отношение этот багрепорт имеет к той драме, которую вы пытаетесь сейчас создать? Вам нужно публичное внимание? Вы могли просто написать мне в личные сообщения с объяснениями (мои сообщения открыты).

I Can't send msg to u on discord if I am not on the same server I was trying to contact u maybe u setting for chat exclusive only for friends and server.

**Comment by Fedricknun** [comment]
And yes I read all of it on your discord with a VPN the only method to see what happened, I apologize for all of it, Maybe i read wrong yesterday, but there was something about me hate Russia? If not I'm on medical recovery with some medicine making my brain feel unstable.


Thanks for the answer I wish there was another method to avoid all of this.
