### ISSUE TITLE
[1.19.2 Forge Bug]: claw tool breaking also deletes selected hotbar item

### ISSUE THREAD

**Issue by cloakable** [DragonSurvivalTeam/DragonSurvival#331]
### ■ Your Discord ID or other contacts

cloakable

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.48.jar

### ■ Single game or server?

Local network (LAN, Hamachi, etc.)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

When a tool in the bite/claws slots breaks, it deletes itself (expected) but also whatever is in the active hotbar slot (not expected).

### ■ Expected behavior

The claws/bite tool to break and vanish, while the hotbar remains unaffected.

**Comment by SiverDX** [comment]
Fixed in the latest update (DragonSurvival-1.19.2-1.5.50.jar) for 1.19.2
