### ISSUE TITLE
[1.19.2 Forge Bug]: Lightning bolt from Storm Breathe and Ball Lightning works only on slabs

### ISSUE THREAD

**Issue by M1TRO11** [DragonSurvivalTeam/DragonSurvival#333]
### ■ Your Discord ID or other contacts

m1trofanov

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.49 + Play as Dragon Gothic Edition-15.06.2023

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

First I tested Storm Breathe and Ball Lightning in creative and never seen lightning. Then I thoght that chance is too small and put some fat monster (Warden) in cobblestone wall enclosure and it worked multiple times! I tested it again on other mobs around and lightning won't appear. Then I decided to place a lot of slabs around (because cobble walls have 1.5 blocks height) and it worked. Breathe and Ball summoned lightnings when target block was slab even without hitting mobs .
To reproduce:
1. Set weather to thunder
2. Activate Storm Breathe or Ball Lightning and take aim at any default block and lightning will not work
3. Place some fences/walls/slabs and keep them on target and lightning will work

### ■ Expected behavior

Lightning will work not only on slabs

**Comment by BlackAures1** [comment]
The fact that the breath calls lightning only on mobs - it's normal. The fact that lightning appears on half-blocks is a bug.

**Comment by M1TRO11** [comment]
It's not only on mobs, if I breathe at slabs without mobs lightning also called

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/b93f5d99-78cd-4f5f-aa16-319107534729)

**Comment by M1TRO11** [comment]
I mean its not working at mobs at all, only on slabs and walls (and mobs on it)
