### ISSUE TITLE
[1.16.5 Forge Bug]: Game crash when right-clicking on the altar and invisible dragon models.

### ISSUE THREAD

**Issue by TheSummoner777** [DragonSurvivalTeam/DragonSurvival#338]
### ■ Your Discord ID

ZveroBoy#9044

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

I'm trying to turn into a Dragon but every time I click the altar it crashes.
Also, dragon models are not displayed when transforming using the console command.

### ■ To Reproduce

put the altar on the ground, then right-click on it and hover over any dragon icon with the cursor.

### ■ Expected behavior

it will simply turn me into the selected dragon and will not fly out, and dragon models will also be visible.

### ■ Crash Report

[crash-2023-06-30_14.14.36-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/11915962/crash-2023-06-30_14.14.36-client.txt)

**Comment by BlackAures1** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/4beaf94b-2766-4520-8123-b4888482021e)
