### ISSUE TITLE
[1.16.5 Forge Bug]: LAN lose all of my level and growup (doesn't show up in dedicated)

### ISSUE THREAD

**Issue by xiaolanjun233** [DragonSurvivalTeam/DragonSurvival#339]
### ■ Your Discord ID

xiaolan#0000

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

i play in my friends server
but when i change to human and go other worlds
i will lose all of my level and growup

### ■ To Reproduce

get dragon level
and change to human
go other worlds
and change to dragon
no any xp now

### ■ Expected behavior

fix it

**Comment by seelderr** [comment]
1.16 is no longer in active development, closing as stale.
