### ISSUE TITLE
[1.19.2 Forge Bug]: Some additional glowing parts are not rendered in the editor

### ISSUE THREAD

**Issue by Glorybringer04** [DragonSurvivalTeam/DragonSurvival#340]
### ■ Your Discord ID or other contacts

glorybringer04

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-3.0.0.jar + Play as Dragon Gothic Edition

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

I am trying to customize a dragon (water dragon), however, the extra options; Lower Stars, Upper Stars, Lower Glow, Upper Glow, and Back Glow, do not have a glow option. When the glow option is selected in the color picker screen the patterns disappear, and they don't show in either the customization screen or the open world.

I just open the customization screen and selected the above patterns, and selected glow.

### ■ Expected behavior

I expected the patterns to glow

### ■ Crash Report File and Logs

not a crash just a bug

**Comment by BlackAures1** [comment]
Have you tried saving the result twice? There are problems with that now. Open the altar and apply the appearance changes again.

**Comment by Glorybringer04** [comment]
I have saved it twice, and while that does seem to fix other skins not showing, the glow patterns simply don't appear at all (if I don't select glow they appear, but if I do they don't render.)

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/c23ca946-7dd0-4e5d-9038-a6a2cf263cf0)
Why do you have such a strange version listed?  I'm fine with the glow on the modpack.

**Comment by Glorybringer04** [comment]
I think might i have originally listed the mod wrong.
I looked again and the version I'm running is DragonSurvival-1.19.2-1.5.52.jar
