### ISSUE TITLE
[1.19.2 Forge Bug]: Unable to Start Server on Bisect Hosting (openjdk required)

### ISSUE THREAD

**Issue by DehlakDrake** [DragonSurvivalTeam/DragonSurvival#342]
### ■ Your Discord ID or other contacts

dehlak

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.53 + Play As Dragon: Gothic Edition-09.07.2023 (both the latest versions as of this post)

### ■ Single game or server?

Dedicated Server or Host Sites

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

I have been trying to start a Play As Dragon: Gothic Edition server on Bisect Hosting, but I keep running into an error that results in the server failing to start.

The issue seems to start at this (line 672 in the attached latest.log):
> [09Jul2023 15:09:38.708] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: /usr/lib/jvm/jdk-17.0.1/lib/libawt_xawt.so: libXext.so.6: cannot open shared object file: No such file or directory

The server was set up to run the latest version of Forge 1.19.2 (v43.2.14) and Java 17.0.1 as seen in the first few lines of the log.

This is a new setup of the modpack (no old files from previous versions).

### ■ Expected behavior

Server startup completion.

### ■ Crash Report File and Logs

[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/11995506/latest.log)

**Comment by SiverDX** [comment]
The java installation of your server hosting service is missing libraries (see headless jdk) 
Might be intended, might be not - dunno

**Comment by DehlakDrake** [comment]
Any way to solve it from my side via FTP? (i.e. what are/where to obtain the missing libraries, etc.)

**Comment by BlackAures1** [comment]
Work it out with your hosting company. It's their problem that they are using the wrong version of java. 
They need this https://learn.microsoft.com/en-us/java/openjdk/download

**Comment by DehlakDrake** [comment]
My apologies for re-opening the issue, but I did some follow-up after the last comment.

After discussing with and trying some things out with the Bisect Hosting support team, I learned the following:
- Bisect Hosting uses **Java 17** and **Linux** to run their servers.
- They host their servers on nodes, so changing the Java version used on one server would require them to change it for all others on the same node. Ultimately, it would be impractical for them to force OpenJDK 17 when Java 17 works fine everything else.

The server starts up fine when only the Dragon Survival mod is removed.
Please read the latest.log given above and determine whether or not something is actually going wonky mod-side. The errors are the same throughout all startup attempts with the mod enabled, so that log is still representative of the issue described above.

**Comment by SiverDX** [comment]
[DragonSurvival-1.19.2-test.zip](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12011173/DragonSurvival-1.19.2-test.zip)

You can try it with that, removed some color related code for treasure blocks
cant test it myself since im not at home and not using bisect

**Comment by DehlakDrake** [comment]
Thanks! Happy to report that the mod now loads successfully on the server!

Should I wait until an official mod update, or is this test version safe enough to use as we wait for the update?

**Comment by SiverDX** [comment]
at the moment treasure blocks will be missing some particle effects / animations and there will be no screen darkening when sleeping on them

**Comment by BlackAures1** [comment]
> at the moment treasure blocks will be missing some particle effects / animations and there will be no screen darkening when sleeping on them

Are these the only features that openjdk required? If so, I wouldn't mind removing them officially or replacing them. Not needing openjdk is more important than a few visuals.

**Comment by SiverDX** [comment]
You can replace them with different logic it's more about the usage of the java AWT (graphics) library that should probably be replaced with minecraft native variants (e.g. getting a color value etc)

it's not used much, I removed the calls that run on the server side for now 

client you will need a full jdk (doesn't have to openjdk btw it's just one variant) as those include sound, control and graphic libraries which will always be needed on the client so I kept the usage in there for now

**Comment by seelderr** [comment]
Fixed as per above
