### ISSUE TITLE
[Compatibility]: Farmers Delight

### ISSUE THREAD

**Issue by GlaciaImca** [DragonSurvivalTeam/DragonSurvival#346]
### ■ Your Discord ID

imuka

### ■ Dragon Survival version

DragonSurvival-1.19.2-1.5.54

### ■ Minecraft version

1.18

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

Consuming a soup item from farmers delight as a dragon does not consume the soup, and instead just spawns another bowl while leaving the soup in your inentory.

### ■ To Reproduce

1) Make a soup item with a bowl from farmers delight or any of its submods.
2) Cosume as dragon, does not mater if its valid food or not
3) Soup will remain, but you get its effects and a free bowl.

**Comment by BlackAures1** [comment]
There are many types of food from mods that use a non-vanilla food system and I don't know how to make a blacklist work for every item from every mod that comes up with some of its own tricks.

**Comment by SiverDX** [comment]
Not sure about this, doesn't happen for me (neither in a larger modpack nor with just the two mods)

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22003703/a7729cf3-a0aa-49c7-9840-e7a37e387684)

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22003703/a6741403-dd2c-48ca-9134-1e382f017791)

**Comment by BlackAures1** [comment]
I've come across quite a few mods that aren't covered by the DS config. Some kinds of juices from overweight farming, infinite ham from apotheosis
