### ISSUE TITLE
[1.19.2 Forge Bug]: 

### ISSUE THREAD

**Issue by AefRal** [DragonSurvivalTeam/DragonSurvival#350]
### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.53

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

Not a bug.

My niece is playing this pack "Play as Dragon Gothic Edition".
She's gotten really frustrated because she can't use the Eyes of 
Ender to find the stronghold. She's listed evidence that it should 
be possible to get to the End, but can't find anything to get her there.
I've even checked the quest book thinking there'd be something like 
an Ender Cake or some custom portal block, or even a questline to get there.
Even tried a few key words in JEI. 

Is there a way to reach the End in this pack?
Or another way to find the Stronghold?

### ■ Expected behavior

Reaching The End.

**Comment by BlackAures1** [comment]
Are you having a problem finding the portal or with the activation?

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/7cd72af2-9522-451a-88fa-e664109b62b0)

**Comment by AefRal** [comment]
Finding it. As the regular eyes didn't work. And we're both new to End
Remastered.
Was there a quest about that mod that I missed?

**Comment by BlackAures1** [comment]
Yeah. In the travel section.

**Comment by AefRal** [comment]
Thank you.
