### ISSUE TITLE
[1.19.2 Forge Bug]: Crash from dragon altar choice

### ISSUE THREAD

**Issue by Reshy** [DragonSurvivalTeam/DragonSurvival#352]
### ■ Your Discord ID or other contacts

_reshy

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.56.jar

Custom Modpack

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Crashed when attempting to automatically open Dragon Altar choice upon loading in.

### ■ Expected behavior

Crashing shouldn't occur from dragon choice.

### ■ Crash Report File and Logs

https://pastebin.com/RUm7k6kT

**Comment by BlackAures1** [comment]
Separately from modpack gekkolib + dragon survival crashes?

**Comment by SiverDX** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/blob/1bc99a19e8009f595c13042a37ddc594f3436f1d/src/main/java/by/dragonsurvivalteam/dragonsurvival/client/handlers/DragonAltarHandler.java#L11

the dist parameter is not safe

![grafik](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22003703/6b764889-b541-4a80-a2da-e68558e48530)

`openingAltar` should have an additional check like ` && tickEvent.side.isClient()`

**Comment by BlackAures1** [comment]
Can you send a pull-request for this or send the code here?

**Comment by SiverDX** [comment]
its in https://github.com/DragonSurvivalTeam/DragonSurvival/pull/349
