### ISSUE TITLE
[1.19.2 Forge Bug]:  editing numeric server configs crash

### ISSUE THREAD

**Issue by Halibut111** [DragonSurvivalTeam/DragonSurvival#355]
### ■ Your Discord ID or other contacts

Kronic#8249

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.57

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

when editing numeric server configs(such as starting health and speed bonus), crashes to desktop once the new value has been entered.

### ■ Expected behavior

being able to disable block movement speed bonuses and edit health values.

### ■ Crash Report File and Logs

[crash-2023-08-12_13.43.13-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12328078/crash-2023-08-12_13.43.13-client.txt)

**Comment by BlackAures1** [comment]
Does the bug appear on the latest version?

**Comment by Halibut111** [comment]
I will have to check, I don't have my high-end computer with me at the
moment.

**Comment by seelderr** [comment]
Will close as this is stale
