### ISSUE TITLE
[1.18.2 Forge Bug]: Custom skin has a discolored bit on the tail?

### ISSUE THREAD

**Issue by xXDJBaconXx** [DragonSurvivalTeam/DragonSurvival#357]
### ■ Your Discord ID

djbacon

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.47.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

It appears as though my custom skin isn't working as intended for some reason.
A bit of the right side of the tail is darker than the left side, even though they are supposed to be the same colors.
I did try to resubmit it earlier just in case, I also tried to make sure the images actually had a transparent background, but it still has the weird dark lines.
(Pictures attached below, just the newborn since they should all be basically the same)

![Discolored](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/73858669/f1e3e7b2-5802-4fc1-ab32-7878f2385222)
![xX_DJBacon_Xx_newborn](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/73858669/6c98c154-0060-4401-b377-0aaccdea11f5)
![xX_DJBacon_Xx_newborn_glow](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/73858669/5c13b635-e144-4b87-8bbd-77cfc982439b)

(Sorry if this isn't important enough, but I wasn't really sure if there was a more appropriate place to throw this lol)

### ■ To Reproduce

Have the skin, log into a game (single or multi-player), and peek at the end of the tail.

### ■ Expected behavior

Expected both sides of the tail bits to be the same color and for both to glow.

**Comment by BlackAures1** [comment]
It's technically impossible. There is just a bug in your skin, which has nothing to do with the mod.

your skin
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/091851da-4317-4cc5-bd8f-da2fa4a9da5f)

your skin no glow
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/c0212a0b-802e-4359-ba13-f389a368a1e9)

your skin full glow
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/ed2f6b8e-3d37-43bf-b049-cd3b9c072016)
