### ISSUE TITLE
[1.18.2 Forge Bug]: food duplication

### ISSUE THREAD

**Issue by GD3000MTG** [DragonSurvivalTeam/DragonSurvival#358]
### ■ Your Discord ID

GD3000

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.47

### ■ Single game or server?

Forge Server or host 

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

there is a bug between sophisticated backpacks and dragon survival where the autofeed upgrade duplicates the food eaten but idk which side this bug is on. either this side or the backpack side. for the single game or server i think its both https://youtu.be/fR4WK0s1_mo this video shows the bug

### ■ To Reproduce

well as a dragon just have a backpack with the autofeed upgrade and fly around and get autofed 

### ■ Expected behavior

you get extra food when reproducing this bug

### ■ Crash Report

causes no crash

**Comment by SiverDX** [comment]
Doesn't seem to happen on 1.19.2, so either there was a fix in Dragon Survival, Sophisticated Backpacks or some other mod in my modpack influences the behaviour (don't think so though) (Singleplayer)

**Comment by GD3000MTG** [comment]
seems to only happen in 1.18.2 and i think before but im not gonna test that theory as my custom modpack is in 1.18.2

**Comment by GD3000MTG** [comment]
Issue solved it was the huge packets mod that was causing the issue

**Comment by BlackAures1** [comment]
Can you provide a link to huge packets?

**Comment by GD3000MTG** [comment]
no mod in my pack was needing the mod anyway

**Comment by BlackAures1** [comment]
I want the link just for reference. I don't know which mod you are referring to.

**Comment by GD3000MTG** [comment]
https://www.curseforge.com/minecraft/mc-mods/huge-packets
