### ISSUE TITLE
cannot fly as dragon 

### ISSUE THREAD

**Issue by anonymusdennis** [DragonSurvivalTeam/DragonSurvival#36]
Hello there i like this mod alot ist balanced and fun in the same way so i thought i would iclude it into my modpack..... but now i can't fly anymore .... How is this happening i talked to te enderdragon used the / dragon command but whatever i try i keep falling like a stone 

here are my mods : its on a github page , iknow but thats all i have:
[https://github.com/anonymusdennis/sausagesmoothie](https://github.com/anonymusdennis/sausagesmoothie)
thanks a lot 
your anonymusdennis....

p.s. immersive engineering keeps babbeling in the console ("Removing concrete feet").... idk if thats the problem...

somehow also creative flight isnt working correctly... 

If i fly in creative and then turn the flight mode of my dragn on it seems to somehow works but i think this mod is made for survival

**Comment by BlackAures1** [comment]
Hello! 
1) In the clean version you have everything works fine with the mod and the problem occurs only in the modpack?
2) Issue the wings of a dragon can be through the command /dragon sea 3 true
3) Wings can be automatically issued from birth in the config file
4) Flight mode is enabled on G (the default). 
5) Mohist core does not allow to use issuing wings and dropping down through End. This is a problem with the kernel itself and has nothing to do with the modification.

**Comment by anonymusdennis** [comment]
thanks a lot how do i fix mohist core?

**Comment by anonymusdennis** [comment]
could mohist core also make the creative flight harder or maybe the real fight mod....

**Comment by BlackAures1** [comment]
We solved the problem on our server with the help of the configuration file:
1) "End void teleports to overworld" = false
2) "Dragons start with wings" = true
There are no other solutions to this problem.

**Comment by anonymusdennis** [comment]
in which config file ???
