### ISSUE TITLE
[1.19.2 Forge Bug]: occultism:datura and other food mechanics broken

### ISSUE THREAD

**Issue by ChakatStormCloud** [DragonSurvivalTeam/DragonSurvival#370]
### ■ Your Discord ID or other contacts

Discord: ChakatStormCloud

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.43
occultism-1.19.2-1.87.1

and any other mod that uses effects on FoodProperties

### ■ Single game or server?

Dedicated Server or Host Sites

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Food items that are used by other mods to trigger events or give effects, have their effects blocked by the dragon food system.
And there is no way to add them to the config that preserves the mods effects.

example: Occultism Demon Dream Fruit, required to start the mod, is prevented from functioning.

### ■ Expected behavior

A config section to add items to a whitelist that makes them use the item's normal FoodProperties, instead of one generated by DragonSurvival.

**Comment by BlackAures1** [comment]
should be fixed with the new KeepEffect config
