### ISSUE TITLE
[1.18.2 Forge Bug]: music-player crash

### ISSUE THREAD

**Issue by EliManthey** [DragonSurvivalTeam/DragonSurvival#371]
### ■ Your Discord ID

novacon

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.48

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

added this mod and a few others to ATM7 and my game crashes whenever I attempt to become a dragon. I can choose human and everything works fine but if I choose a dragon type or try to use an altar later the game crashes like this

### ■ To Reproduce

this is my modlist. I can also provide a zip of the modified ATM7 curseforge pack for reproduction if required. 

![modslist 1](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/6109442/d40b93c6-f674-4f8c-85c9-0b7a67b4ee14)
![modslist 2](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/6109442/0aeb6cee-30b6-4c64-9224-2fb479bba805)

### ■ Expected behavior

I was just trying to launch the game but it crashed when I clicked the save button on the default sea dragon.

### ■ Crash Report

[crash-2023-09-13_17.12.39-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12602296/crash-2023-09-13_17.12.39-client.txt)

**Comment by BlackAures1** [comment]
try without oculus/rubidium

**Comment by EliManthey** [comment]
removed oculus and rubidium. same crash


[crash-2023-09-13_19.08.46-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12602635/crash-2023-09-13_19.08.46-client.txt)

**Comment by BlackAures1** [comment]
send log too

**Comment by Bluebaron2** [comment]
Hi i dont know if this will be any help but ive been testing this pain of a crash for the last 5 hours in a very bizarre case, we have a server up and running and everyone's imported the exact same files however one of these guys crashes instantly when ever he sees a dragon player. i removed all the mods save a few each time from scratch on his end and found the mods that add custom renders etc (create flywheel, security craft (camera renders), Ars Nouveau) will cause this issue and that for some reason his minecraft launch loads the mixins at different times compared to ours, as well as different amount. 

eg mine and the others will solve the conflict between security craft and ars nouveau first then the conflict between dragon survival and better combat. his skips security craft and ars entirely and goes for dragon survival and better combat. (i have tried with and without starlight and rubidium). 

 Honestly i have no clue for this issue but ill post his crash logs hope this helps at least a little. (it is to note mahou tuskai has alot of issues in 1.18.2 with create and rubidium and its rendering) i have 3 crash logs of his atm and can get the rest from when we were testing mod by mod if you would like.

**Comment by Bluebaron2** [comment]
[crash-2023-09-25_15.47.23-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12718626/crash-2023-09-25_15.47.23-client.txt)
[crash-2023-09-25_18.07.08-client.txt](https://github.com/Drago
[crash-2023-09-25_19.10.26-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12718629/crash-2023-09-25_19.10.26-client.txt)
nSurvivalTeam/DragonSurvival/files/12718628/crash-2023-09-25_18.07.08-client.txt)

**Comment by Bluebaron2** [comment]
[crash-2023-09-25_19.10.26-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12718636/crash-2023-09-25_19.10.26-client.txt)

[crash-2023-09-25_18.07.08-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12718640/crash-2023-09-25_18.07.08-client.txt)

[crash-2023-09-25_15.47.23-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12718641/crash-2023-09-25_15.47.23-client.txt)

**Comment by Bluebaron2** [comment]
as for the mod list of the initial pack we are on.  
[modlist.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12718673/modlist.txt)

**Comment by EliManthey** [comment]
this looks like the exact same issue.

**Comment by BlackAures1** [comment]
This error is most likely caused by incompatibility with this mod. Thanks for the investigation, scottycool64
https://www.curseforge.com/minecraft/mc-mods/music-player

**Comment by seelderr** [comment]
I tested with just music-player and DS on 1.19.2, and there seem to be no issues. It is possible there is some mix of mods that causes the incompatibility, but it will be extremely hard to fix until we can isolate further. Going to close as WNF for now.
