### ISSUE TITLE
[1.18.2 Forge Bug]: Large dragon door models are invalid; turn into missing texture blocks

### ISSUE THREAD

**Issue by drown3d** [DragonSurvivalTeam/DragonSurvival#372]
### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.48.jar

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Yes

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

Game can't load large dragon door models, causing them to become cubes with missing textures. Small dragon doors seem to be unaffected.

### ■ To Reproduce

1. Place any large dragon door in the world.

### ■ Expected behavior

The doors should appear to have a proper model and texture.

**Comment by Doppelgangergang** [comment]
Can confirm this bug exists when using DragonSurvival-1.18.2-1.5.48.jar from CurseForge. All mods except for geckolib (dependency) is removed.

Creating a resource pack incorporating JSON data from this commit does fix the issue though.

https://github.com/DragonSurvivalTeam/DragonSurvival/commit/53116561fb624b317c670763777b1354de1a243a

**Comment by BlackAures1** [comment]
This version is already fixed on the github, but not yet published. Wait for the public fix

**Comment by BlackAures1** [comment]
fixed in latest
