### ISSUE TITLE
[LICENSE ISSUES]

### ISSUE THREAD

**Issue by User-green** [DragonSurvivalTeam/DragonSurvival#375]
### ■ Your Discord ID

User_green

### ■ Dragon Survival version

From https://github.com/DragonSurvivalTeam/DragonSurvival/commit/87a958389a73832545fe04281b006d04e748ae3a

To https://github.com/DragonSurvivalTeam/DragonSurvival/commit/427a5303f7d1a5eec30916e4e5c9dac520e965b9

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

Hello. I noticed that your current license has some problems. 

> Allowed use of content: private use, modification, distribution, view and fork repository,
>      making pull request or suggestions to improve the project. Other uses are negotiated with the author separately.
>      The author retains full rights to the project. 
> 

> Only "Minecraft Mod: Dragons Survival"
>      participants are free to make changes may freely modify, distribute and use all project
>      content except for the creation of third-party projects using any Dragon Survival content.
>      List of participants "Minecraft Mod: Dragons Survival" on the GitHub:

This two paragraph are in contradiction with each other. First allows `modification, distribution` and the second one denies anyone, except `"Minecraft Mod: Dragons Survival"` members. 

Additionally, there is no definition who 
> "Minecraft Mod: Dragons Survival" participants
are, witch makes it even bore bizarre. 

Dobble additionally, there is no sign-off clause in the current license, so any contributor, who made contribution after Jan 17, 2022 mow can object of his/her contribution been used. 

Triple additionally, any code written until Jan 17, 2022 can still be used under the terms of Apache 2 license, due to the fact that laws does not have reverse power. 

### ■ To Reproduce

N/A

### ■ Expected behavior

Considering what I understood from reading your current license, I'd expect that you want to prevent other people useing content that you made in other mods. 

Considering said above, would suggest that you are to license all none-code (images, animations, etc) assets made by you (BlackAures1) for this mod under CreativeCommons Attribution-NonCommercial-NoDerivatives 4.0 International license, witch, in short, states:

> This license requires that reusers give credit to the creator. It allows reusers to copy and distribute the material in any medium or format in unadapted form and for noncommercial purposes only. 

I should, however, note I am not shore if this one can be applied to code. 

Also, I do strongly suggest that you include sign-off for any contributions, and ask current contributes to sign off, so you will not have problems with this later.

Also, as a person, who strongly supports Free Software movement, I strongly recommend useing GNU GPLv3  as primary license for the code, if at all possible. Thats not like somebody is going to steal a part of your mod's code, and than use it somewere else as-is, you should know better than me that it doesn't work like that.

**Comment by User-green** [comment]
Also.
Да, я говорю по-русски.
Да, я тот пират которого вы забанили. 
Да, мне не нравится ваша политика относительно авторского права.
Да, я полез в лицензию мода, так как меня до сих не отпускает, что меня забанили. 
Но нет, мне нравится сам мод.
И нет, я не намерен как-либо нарушать вашу лицензию, так как это всё ещё лицензия публичного пользования, хоть и крайне ограниченая, а не противная всему живому и мёртвому "Microsoft Corp., All rights reserved". 

P.S. Разрешите всё же кастомные шаблоны.

**Comment by BlackAures1** [comment]
Для сторонних читателей: этот человек весьма активно и настойчиво (в какой-то мере даже агрессивно, учитывая что это дошло до гитхаба спустя много месяцев) пропагандировал пиратство, прикрываясь благородством и чем-то в таком духе.

Да, я знаю что у лицензии есть проблемы, но вы и сами в описании "проблем" допустили много ошибок. Тот же список участников указан в лицензии. 
Да, мне пофиг на то что вам нравится/не нравится в том что касается чужой интеллектуальной собственности, о, "пират во втором поколении".
Да, я strongly recommend тебе создавать свой контент и распространять его как душа пожелает, а не ходить по чужим  дворам и попрошайничать.

Ага, конечно, так я и поверила что вы заглянули в проект просто так.

**Comment by User-green** [comment]
> Для сторонних читателей: этот человек весьма активно и настойчиво (в какой-то мере даже агрессивно, учитывая что это дошло до гитхаба спустя много месяцев) пропагандировал пиратство, прикрываясь благородством и чем-то в таком духе.
> 
> Да, я знаю что у лицензии есть проблемы, но вы и сами в описании "проблем" допустили много ошибок. Тот же список участников указан в лицензии. 
> Да, мне пофиг на то что вам нравится/не нравится в том что касается чужой интеллектуальной собственности, о, "пират во втором поколении".
> Да, я strongly recommend тебе создавать свой контент и распространять его как душа пожелает, а не ходить по чужим  дворам и попрошайничать.
> 
> Ага, конечно, так я и поверила что вы заглянули в проект просто так. 
> 

Как хотите. Я на баг указал, вы делайте что хотите, благо, это на геймплей не влияет. Github не место для срачей, в конце-концов. 

К слову, можно открить issue по текстурам для меканизмовской брони, или это не сюда? Там Mekasuit и их антирадиационный костюм не совсем правильно отображаются.

**Comment by BlackAures1** [comment]
Хотели бы именно о проблеме сообщить не стали  бы устраивать эту драму с "Да, я тот бедный несчастный кого вы забанили"

**Comment by User-green** [comment]
> Хотели бы именно о проблеме сообщить не стали  бы устраивать эту драму с "Да, я тот бедный несчастный кого вы забанили"

Да, был не прав, не стоило этого делать. Следовало ждать сообщения в дисе.
