### ISSUE TITLE
[1.19.2 Forge Bug]: Disappearing tail in multiplayer

### ISSUE THREAD

**Issue by BlackAures1** [DragonSurvivalTeam/DragonSurvival#377]
### ■ Your Discord ID or other contacts

blackaures

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-27.10.2023 and 90% of the older versions

### ■ Single game or server?

Dedicated Server or Host Sites

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

It's time for me to write bug reports for the convenience of all project participants, instead of Trello and private messages. 

This bug is very old and appears when enableTailPhysics = true.
This can happen in any dragon player, but only in multiplayer.
I assume the problem is due to problems in calculating the math and the tail is getting 0 molang values.

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/ea75024d-d461-426b-b0a2-3a5dc7aee9f7)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/51c22004-1b0c-41a5-946b-4fe5d76a4f14)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/3cb0427c-45c5-4d74-81c0-1da1b524b3b3)

This config was included so that swimming animations and some other animations related to more varied player movement could be seen. An example of how the config affects the dragon's movement in the sea - https://www.youtube.com/watch?v=lPG6ZnOVqwo

### ■ Expected behavior

1. **Run local or dedicated server.** This problem does not appear in the single-player game
2. **enableTailPhysics = true** in client config. Turning off the config hides the problem, but it also deprives the player of awesome molang animations.
3. Play with a friend for an hour or less.
4. Get a missing tail at some random point in the game

### ■ Crash Report File and Logs

No crash

**Comment by seelderr** [comment]
Fixed in 1.21
