### ISSUE TITLE
[1.19.2 Forge Bug]: 

### ISSUE THREAD

**Issue by GossHarag** [DragonSurvivalTeam/DragonSurvival#378]
### ■ Your Discord ID or other contacts

gossharag1188

### ■ Dragon Survival version and Modpack version (if have)

Play as Dragon Gothic Edition-10.08.2023
[crash-2023-11-09_01.46.39-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13304672/crash-2023-11-09_01.46.39-client.txt)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

Whenever I try to open a world with this modpack, it loads the world but instantly crashes when it tries to join the world

1. I open the world
2. Wait for it to load
3. Crash upon joining the world

### ■ Expected behavior

I expected it to load normally

**Comment by SiverDX** [comment]
you definitely didn't install the modpack (properly or at all)
also your https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks and https://www.curseforge.com/minecraft/mc-mods/sophisticated-core versions are out-of-sync

**Comment by GossHarag** [comment]
I downloaded sophisticated backpacks with the rest of the modpack directly from Curseforge.
