### ISSUE TITLE
[1.19.2 Forge Bug]: Dragon selection is broken

### ISSUE THREAD

**Issue by Fingernailsss** [DragonSurvivalTeam/DragonSurvival#379]
### ■ Your Discord ID or other contacts

_fingernails or fingernails.xe@gmail.com

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.58

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Dragon selection is broken

1: Create a new world

2: Wait for menu to appear

3: Click on "Cave Dragon"

4: Crash

### ■ Expected behavior

To open customization options.

### ■ Crash Report File and Logs

[crash-2023-11-10_21.51.01-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13324230/crash-2023-11-10_21.51.01-client.txt)
[crash-2023-11-10_21.55.07-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13324231/crash-2023-11-10_21.55.07-client.txt)
[crash-2023-11-10_22.05.55-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13324232/crash-2023-11-10_22.05.55-client.txt)

**Comment by BlackAures1** [comment]
1. Install the latest version of the mod
2.  Make sure you install the mod correctly and check - "Mod doesn't work!" section https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update
