### ISSUE TITLE
[1.19.2 Forge Bug (FPS began to drop)]:

### ISSUE THREAD

**Issue by Lanostry** [DragonSurvivalTeam/DragonSurvival#381]
### ■ Your Discord ID or other contacts

Lanostry#0215

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-10.11.2023_GLOBAL_UPDATE_READ_PATCH_NOTE

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

In a single player game, I used resource puck to check the skin, after that I grew the dragon to its maximum size and began to fly on it, dive down, then the game began to freeze.  If I reduced the size of the dragon, the lag disappeared, i don't know if this problem exists on the server

### ■ Expected behavior

FPS begins to drop, flying causes discomfort, it depends on the size of the dragon

### ■ Crash Report File and Logs

there was no game crash

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/spark
https://spark.lucko.me/docs/Command-Usage

run these and do stuff which causes lag
if fps lag (=> client) : `/sparkc profiler start --timeout 60`
if server lag (this also applies to singelplayer): `/spark profiler start --timeout 60`

**Comment by BlackAures1** [comment]
I tested this on the modpack in single player and didn't notice any issues.

- **off entity shadows**
https://spark.lucko.me/Pa5t2Bg75Z /spark profiler start --timeout 30 --thread * (off shaders, off entity shadows, human)
https://spark.lucko.me/DkUc5xEsRt /sparkс profiler start --timeout 30 --thread * (off shaders, off entity shadows, human)

https://spark.lucko.me/ZYgIuJgrMf /spark profiler start --timeout 30 --thread * (on shaders, off entity shadows, human)
https://spark.lucko.me/jEu6CcCwtY /sparkc profiler start --timeout 30 --thread * (on shaders, off entity shadows, human)

https://spark.lucko.me/1iVwMFv3Gr /spark profiler start --timeout 30 --thread * (on shaders, off entity shadows + newborn dragon form)
https://spark.lucko.me/BfGaDVWnl9 /spark profiler start --timeout 30 --thread * (on shaders, off entity shadows + adult dragon form)

https://spark.lucko.me/ZeHeHOLHbL /sparkc profiler start --timeout 30 --thread * (off shaders, off entity shadows + adult dragon form)

- **on entity shadows**
 https://spark.lucko.me/NLK54qmYeE /sparkс profiler start --timeout 30 --thread * (off shaders, on entity shadows + adult dragon form)
https://spark.lucko.me/L4KZdk0W0Y /sparkс profiler start --timeout 30 --thread * (on shaders, on entity shadows + adult dragon form) 

https://spark.lucko.me/YoO72DV5sd /sparkс profiler start --timeout 30 --thread * (on shaders, on entity shadows + newborn dragon form) 
https://spark.lucko.me/Rniga68yVG /sparkc profiler start --timeout 30 --thread *  (on shaders, on entity shadows + young dragon form)

**Comment by Lanostry** [comment]
https://spark.lucko.me/FhvMckWEK3
