### ISSUE TITLE
[1.19.2 Forge Bug]: 

### ISSUE THREAD

**Issue by BearInMindOffical** [DragonSurvivalTeam/DragonSurvival#384]
### ■ Your Discord ID or other contacts

熊楚心#7195

### ■ Dragon Survival version and Modpack version (if have)

only DragonSurvival-1.19.2-23.11.2023 and geckolib-forge-1.19-3.1.40.

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Stuck at this screen and then crashed.
![屏幕截图 2023-11-24 113937](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/148528361/a711f638-86b3-4401-9e85-c562803c875f)
With crash report.
But it's fine using this version to open a server.
And this issue doesn't exist at DragonSurvival-1.19.2-1.5.58.

### ■ Expected behavior

Plz fix it. I like this mod very much, thx.

### ■ Crash Report File and Logs

[CrashReport-11-24-2023_11.40.48_AM.zip](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13454986/CrashReport-11-24-2023_11.40.48_AM.zip)

**Comment by BlackAures1** [comment]
This is due to the Chinese/vpn and trying to download skins from [gitcode](https://gitcode.net/api/v4/projects/mirrors%2FDragonSurvivalTeam%2FDragonSurvival/repository/tree?ref=master&path=src/test/resources&per_page=100&page=1)

**Comment by BearInMindOffical** [comment]
copy that =(
thx

**Comment by BlackAures1** [comment]
We'll try to fix it

**Comment by BearInMindOffical** [comment]
thank you

**Comment by seelderr** [comment]
Fixed as per above
