### ISSUE TITLE
no aparece el dragon

### ISSUE THREAD

**Issue by kitsuzzzz** [DragonSurvivalTeam/DragonSurvival#392]
### ■ Your Discord ID

alecczzz

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

cuando empiezo el mundo no me aparece la configuracion para convertirme en dragon desde ya y cuando uso el comando para convertirme en uno no aparece el dragon es invisible 

### ■ To Reproduce

intente en varios mundos para ver si era un error de ese mundo pero me paso en todos

### ■ Expected behavior

tal vez que apareciera el dragon y no sea invisible

**Comment by BlackAures1** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/1.-Installation,-Configure,-Update#--1165
