### ISSUE TITLE
[Compatibility]: Gothic Edition crashes on world generation.

### ISSUE THREAD

**Issue by thewwizardd** [DragonSurvivalTeam/DragonSurvival#393]
### ■ Your Discord ID

thewwizard

### ■ Dragon Survival version

Play as Dragon Gothic Edition-10.08.2023.zip

### ■ Minecraft version

1.18

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Description of incompatibility

1. A mod in the Gothic Edition of _Play as Dragon_ causes my game to crash. I have no issue running the standard edition of _Play as Dragon_, and the Gothic Edition starts up as normal, but trying to create a new world results in a game crash and an Exit Code 6.

### ■ To Reproduce

1) Install Play as Dragon: Gothic Edition (10/8/2023 release)
2) Launch Game
3) Singleplayer mode
4) Click on any pre-existing partially-created world, or create a new world
5) Wait about 15-20 seconds while your cursor spins
6) Crash, return to launcher, displaying an Exit Code 6.

### ■ Crash Report

[crash-2023-12-04_21.10.14-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13555517/crash-2023-12-04_21.10.14-fml.txt)

**Comment by SiverDX** [comment]
according to the log you're missing adaptive_performance_tweaks_player_1.19.2-6.8.0.jar

considering that's the case you might be missing other stuff as well

**Comment by BlackAures1** [comment]
I guess there's absolutely nothing I can do to help you with that. Maybe a new update will help. What exactly is the problem antivirus is showing with the another_furniture-forge mod? I can get the developer to fix the problem

**Comment by thewwizardd** [comment]
Odd. I'll keep troubleshooting and working through the modlist to see if I find anything there. Running the modpack without my antivirus active results in the same crash, but installing the modpack without the antivirus gives me the 1.19 panorama background, plus I can access things like resource packs and shaders from the menu. Macs aren't the best for gaming in general, so I'm not too surprised by all of this; no sweat. I'll be okay with my single player dragon mode

**Comment by BlackAures1** [comment]
If you have progress, send a new crash report.

**Comment by seelderr** [comment]
Stale issue, going to close as WNF
