### ISSUE TITLE
[1.18.2 Forge Bug]: While add to modpack with TFC, dragon player can't restore hungry by eating any kinds of food.

### ISSUE THREAD

**Issue by YakumoUUZ** [DragonSurvivalTeam/DragonSurvival#398]
### ■ Your Discord ID

yakumo_uuz#3602

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.48.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

While add to modpack with TFC(TerraFirmaCraft: The Next Generation), dragon player can't restore hungry by eating any kinds of food.

### ■ To Reproduce

Just add TFC(TerraFirmaCraft-Forge-1.18.2-2.2.32) and DS, then eating any kinds of food (no matter coal for cave or fish for sea)

### ■ Expected behavior

Hunger doesn't restore.

**Comment by seelderr** [comment]
This is a compatibility issue on an old version, marking as WNF
