### ISSUE TITLE
[1.19.2 Forge Bug]: 

### ISSUE THREAD

**Issue by QuasarMoon** [DragonSurvivalTeam/DragonSurvival#401]
### ■ Your Discord ID or other contacts

quasarmoon#0465

### ■ Dragon Survival version and Modpack version (if have)

Dragon survival- 1.20.1-24.12.2023

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

crashes on loading

### ■ Expected behavior

loads

### ■ Crash Report File and Logs

[crash-2023-12-28_21.22.50-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13790735/crash-2023-12-28_21.22.50-client.txt)

**Comment by BlackAures1** [comment]
take a screenshot of the mods folder
It's a geckolib problem
