### ISSUE TITLE
[1.16.5 Forge Bug]: 

### ISSUE THREAD

**Issue by Figggggg** [DragonSurvivalTeam/DragonSurvival#403]
### ■ Your Discord ID

Paps#0258

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.7

### ■ Single game or server?

Doesn't matter (I can't go past the error screen at the start of Minecraft)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I only play with DS and Geckolib (Default)

### ■ Describe the bug

When launching Minecraft 1.16.5 (Geckolib is 3.0.93), I can't even get to the menu because of the error screen which is: "Dragon Survival (dragonsurvival) encountered an error during the sided_setup event phase".

### ■ To Reproduce

Try to boot up minecraft Forge 1.16.5 (forge version: 36.2.39).

### ■ Expected behavior

I go to the minecraft menu screen instead of the error window.

### ■ Crash Report

[crash-2023-12-31_14.39.38-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13801174/crash-2023-12-31_14.39.38-fml.txt)
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13801175/latest.log)

**Comment by Figggggg** [comment]
Already fixed it, for future people out there: delete not only the ".toml" files from the config folder, but also the whole "dragon survival" folder from the ".minecraft" folder.

**Comment by BlackAures1** [comment]
just like it says on the wiki
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/8090cf39-42b0-4b69-99bf-f72d2f0409eb)
