### ISSUE TITLE
[1.19.2 Forge Bug]: Fletcher trading

### ISSUE THREAD

**Issue by W-Wiemer** [DragonSurvivalTeam/DragonSurvival#411]
### ■ Your Discord ID or other contacts

0ompaloompa.

### ■ Dragon Survival version and Modpack version (if have)

Play as Dragon Gothic Edition-3.01.2024 -1.19.2

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

Everytime you trade with the villager that has the profession as Fletcher it dies once you reach his second stage of trading.
Both in single player and multiplayer

### ■ Expected behavior

Villager dies after first stage of trade is complete

### ■ Crash Report File and Logs

![Fletcher](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/156101074/4052b91a-b985-45bc-b9e1-3cd559bc2da6)

Not a crash report but its text.
"Caught Ticking entity (name of villager) at position (coordinates). It has been killed"

**Comment by BlackAures1** [comment]
use [easy villager](https://www.curseforge.com/minecraft/mc-mods/easy-villagers) block to trade

**Comment by W-Wiemer** [comment]
Still dosnt work. The text still comes and the villager dosnt "upgrade" Now he just dosnt die, but still bugged

**Comment by BlackAures1** [comment]
CURSEFORGE\Instances\Play as Dragon Gothic Edition (2)\config\custom trades [fletcher.json](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13883931/fletcher.json)
Thanks for the heads up, I found what the problem is. Replace this file with the one I sent you above in the path given. If you play on a server, it's easy enough to install this only on the server (client do not need). Keep in mind that you need to kill previous Fletchers to prevent this bug from happening.

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/34012d17-5dd6-49ad-8af5-206bc5b2d51c)

**Comment by W-Wiemer** [comment]
Thankyou, Do you btw know why when I use the easy villagers mod and I have lets say Weaponsmith into the trading station, And Max out the first trade. It dosnt "upgrade" either, And the villagers never reset their trades? Do They need to have access to sunlight or something?? Ive tried everything so far and I cant get them to reset their trades It should reset twice a minecraft day.

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/e38b82b9-135a-441e-b2fb-d96bdb71f0f5)
I didn't have a problem with it. Are you still experiencing this problem?

**Comment by W-Wiemer** [comment]
No I guess it was a server side lag issue.
Can you answer me a last thing tho? 
I dont know if this is a problem on the server im playing on or the client. Since I have the same problem on singleplayer aswell.

Can you check why all of the different villagers has the same trades? 
Like all armor I make has exactly the same enchants on the items. 
And Weapons smith Also exactly the same, Its quite sad when trading is the only way to obtain diamond armor and tools :(

**Comment by BlackAures1** [comment]
You can change the enchantment through Apotheosis

**Comment by BlackAures1** [comment]
And you can get diamonds thinks in chests

**Comment by W-Wiemer** [comment]
Im kinda new to this pack so thankyou for all your help, What is Apotheosis? 
And do you know if the creator of the pack has done like a wiki on it? 
I love the pack, but its hard to figure out xD

**Comment by BlackAures1** [comment]
The modpack wiki is 300 quests written by me in two languages that contains about 13,000 words. I will soon release an update on this modpack with fixes, but if you installed the modpack really correctly, you should have the quests available now. This github is mainly made for the Dragon Survival mod. You should post questions about the modpack in [discord](http://discord.gg/8SsB8ar).

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/a1f026ac-80df-4ada-b28a-62f90a325310)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/90982ee5-0031-493d-ac30-e0483dd04c15)

**Comment by W-Wiemer** [comment]
Ah thankyou so much!. I didnt know you made this. Well nice job! I have a few questions Id like answered but Ill ask them in the discord so I dont take up more of ur time! Thanks again!
