### ISSUE TITLE
[1.19.2 Forge Bug]: 

### ISSUE THREAD

**Issue by LiekkiL** [DragonSurvivalTeam/DragonSurvival#419]
### ■ Your Discord ID or other contacts

liekkil

### ■ Dragon Survival version and Modpack version (if have)

Play as Dragon Gothic Edition -13.01.2024

### ■ Single game or server?

Dedicated Server or Host Sites

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

On playing via lan and port forwarding to friends, we decided to just make a proper server as to not have to constantly change ports. Though upon making a server, importing the world file it all loaded up fine until all apotheosis items, ingots and numerous other items dropped from the inventory stating "You can't use this item." Further more block interactions from Anvils, furnaces etc are met with, "You can't use this block." Inventories did transfer over properly as well as quests, chunks etc. 

Policy seems to be unaffected by being op, in creative etc.

### ■ Expected behavior

Players retain inventory (Partially worked) Able to interact with blocks and items etc.

### ■ Crash Report File and Logs

No crash reports or logs give info on refusal to access blocks or items.

**Comment by BlackAures1** [comment]
reinstall the server. Be sure to migrate all files. This is a problem of incorrect modpack installation.
