### ISSUE TITLE
[Compatibility]: DS and Immersive Portals

### ISSUE THREAD

**Issue by DomezTheDragon** [DragonSurvivalTeam/DragonSurvival#420]
### ■ Your Discord ID

859832646979813396

### ■ Dragon Survival version

DragonSurvival-1.18.2-1.5.48

### ■ Minecraft version

1.18

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Description of incompatibility

basically, if i am a dragon and i go into a overworld-nether immersive portal, the game freezes and crashes, doesnt happen with overworld-overworld portals or similar

### ■ To Reproduce

have dragon survival and immersive portals 1.4.20 1.18.2

### ■ Crash Report

[crash-2024-01-27_15.52.12-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14073824/crash-2024-01-27_15.52.12-client.txt)

**Comment by SiverDX** [comment]
does that also happen with this version https://github.com/DragonSurvivalTeam/DragonSurvival/pull/368

**Comment by DomezTheDragon** [comment]
not sure, havent tested

**Comment by SiverDX** [comment]
you do realize that that's a 1.18.2 version, right

**Comment by DomezTheDragon** [comment]
your saying that like it wasnt obvious from the start

**Comment by seelderr** [comment]
1.18.2 is on minimal support right now, going to close as WNF
