### ISSUE TITLE
[1.19.2 Forge Bug]: 

### ISSUE THREAD

**Issue by AlexTheFixer** [DragonSurvivalTeam/DragonSurvival#423]
### ■ Your Discord ID or other contacts

Yrtree

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-16.01.2024

### ■ Single game or server?

Dedicated Server or Host Sites

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

1. Go to Cast magic
Does not work, no cast bar appears and issue with casting all spells.

### ■ Expected behavior

Expected: Spell to cast

**Comment by SiverDX** [comment]
check for keybind conflicts

**Comment by AlexTheFixer** [comment]
> check for keybind conflicts

Thank you for the suggestion however, I am 100% sure that is not the issue due to it working in the singleplayer on the same instance.
