### ISSUE TITLE
[1.20.1 Forge Bug]: Significant amount of tick lag caused by Dragon Survival in singleplayer and playing as a human

### ISSUE THREAD

**Issue by StardustPassingBy** [DragonSurvivalTeam/DragonSurvival#426]
### ■ Your Discord ID or other contacts

strutting.little.egotist on Discord

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.20.1-09.01.2024 on Minecraft 1.20.1, version 47.2.0 of Forge

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Dragon Survival seems to cause significant tick lag, even while playing singleplayer as a human and not (to my knowledge) engaging with any Dragon Survival mechanics. I have done a fresh instance of Minecraft with nothing but spark, geckolib, and Dragon Survival installed, and still have the same issue. Running the Spark profiler consistently shows it taking up 3-6% of the render thread, seemingly mostly due to recurring checks related to the overlay and to flight cooldown.

Screenshot from Spark on the clean install:
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/157174598/d7a2ca77-8867-4123-8f17-13cdc8b74c0e)

### ■ Expected behavior

I would expect Dragon Survival to be mostly in the background when its mechanics are not being utilized.

### ■ Crash Report File and Logs

Spark log on my modpack: https://spark.lucko.me/fuJYW9VIcz

Spark log on the fresh install: https://spark.lucko.me/f8ZG2lY9he

Both are from singleplayer worlds where I am playing as a human and just running around on the overworld.

Also attaching the latest and debug logs for both versions below:

[cleanlatest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14118106/cleanlatest.log)
[cleandebug.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14118107/cleandebug.log)
[modpacklatest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14118118/modpacklatest.log)
[modpackdebug.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14118117/modpackdebug.log)

**Comment by SiverDX** [comment]
the gui one is higher because it replaces the vanilla food gui rendering
so it's not like some big performance impact there (there is also a client config to disable that behaviour)
