### ISSUE TITLE
[1.20.1 COMPAT ISSUE] Classic Bars & Dragon Survival

### ISSUE THREAD

**Issue by fourthhouse** [DragonSurvivalTeam/DragonSurvival#428]
### ■ Your Discord ID

water_wind_

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024.jar

### ■ Minecraft version

1.18

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

Classic Bars is a extremely popular mod that changes the HUD to a bar-style appearance, as seen in my screenshot. When dragon survival is in the modpack, the player will see two hunger bars. Can you please add an option to disable the appearance of the hunger bar so that there will only be one? I can confirm it is this mod causing the double hunger bar because I spent hours picking at my 400-mod modpack to narrow it down and it only occurs when this mod is added. If you can eventually make this fix, I would be so appreciative! 
![2024-02-06_19 22 07](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/56618632/d52f693f-abfa-43fb-851e-62bb65fa6b2c)

### ■ To Reproduce

Download 1.20.1 curseforge 47.2.20 and then install the mods dragon survival and classic bars, then open a game and see you will have two hunger bars

**Comment by SiverDX** [comment]
check client config

**Comment by fourthhouse** [comment]
It was in the client config, idk why i checked server but not client for this. Thanks! Problem solved.
