### ISSUE TITLE
[1.19.2 Forge Bug]: game not launching

### ISSUE THREAD

**Issue by Phoenixfire5400** [DragonSurvivalTeam/DragonSurvival#431]
### ■ Your Discord ID or other contacts

Phoenix_6850

### ■ Dragon Survival version and Modpack version (if have)

play as dragon gothic edition-26.01.2024

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

I've been trying to play the newest version of PADGE but when I go to launch the game itself, it crashes and shows this crash popup
![image_2024-02-16_173700112](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/160290957/fa016727-08c0-4a8d-bf30-295225362072)

### ■ Expected behavior

expected the game to properly start up

### ■ Crash Report File and Logs

log
[2024-02-16-4.log.gz](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14317139/2024-02-16-4.log.gz)
[hs_err_pid14312.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14317153/hs_err_pid14312.log)

**Comment by SiverDX** [comment]
update your amd graphics driver

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/ec6f961b-677e-476c-b594-5f1e10f46763)
