### ISSUE TITLE
[1.20.1 Forge]:  Respawn Bug

### ISSUE THREAD

**Issue by HakeT2Lab** [DragonSurvivalTeam/DragonSurvival#435]
### ■ Your Discord ID or other contacts

ItzalGaming#4212

### ■ Dragon Survival version and Modpack version (if have)

Fresh Modpack with only dragon survival and it's dependency.  Does not seem to matter if forge or neoforge is used
 
-DragonSurvival 1.20.1
-geckolib-neoforge 1.20.1-4.4.2

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Upon creating a new world and choosing a dragon, and running /kill results in player not being able to respawn with the button being blacked out. doing so as a human does not have this issue.

In addition, starting a world in creative and choosing a dragon shows and the entity name "entity.dragonsurvival.dummy_dragon" above player, /kill also results in the above issue. 

### ■ Expected behavior

Expected player respawn.

### ■ Crash Report File and Logs

[Creative.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14395904/Creative.log)
[Survival.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14395905/Survival.log)

**Comment by seelderr** [comment]
Fixed as per above commits
