### ISSUE TITLE
[Play as Dragon]: 1.19.2 Gothic Edition

### ISSUE THREAD

**Issue by DriftingDruid** [DragonSurvivalTeam/DragonSurvival#439]
### ■ Your Discord ID

DriftingDruid#4746

### ■ Modpack version

Play as Dragon Gothic Edition - 1.19.2 
26.1.2024

### ■ Forge/Neoforge version

CurseForge v.0.244.5-16323

### ■ Single game or server?

Single-player (Default)

### ■ Describe the problem

i keep getting a skin glitch that happens when my dragon grows or shrinks a growth stage, it changes the skin to a growth stage that's of a different skin set than the one i have currently equipped. happens no matter the dragon type or skin set selected 
![2024-03-02_12 54 56](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/938450cf-0238-460b-ae30-0e3bfabb6984)
![2024-03-02_12 55 00](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/c0443af6-2cdb-4879-8da2-b9fe42a59ad5)
![2024-03-02_12 55 03](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/d71795e6-2fe4-41f0-803b-278bf79d7da3)
![2024-03-02_12 55 11](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/6b872ddc-1d5e-4931-99b3-ad1fea0c46bd)
![2024-03-02_12 55 15](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/50db5d63-aea3-43b0-bdfb-c70654fbb9b1)
![2024-03-02_12 54 07](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/26641959-4333-4c3e-b42b-62eadf4c8c96)
![2024-03-02_12 54 15](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/6925ae51-2166-49a2-a68f-a0cb9b3c90f9)
![2024-03-02_12 54 18](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/b25ab316-55fd-4a80-be50-313d2aaaf270)
![2024-03-02_12 54 35](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/ba8e89bc-b694-480b-8a2e-1a65de525c5f)
![2024-03-02_12 54 43](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/161977165/d996457c-59eb-456f-8c30-5c60efd170be)

**Comment by DriftingDruid** [comment]
saved customizations file, if this helps 
[saved_customizations.json](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14644354/saved_customizations.json)

**Comment by BlackAures1** [comment]
I can't replicate this bug
