### ISSUE TITLE
[1.16.5 Bug]: Growup and skill saving and DRAGON ALTAR CHAT COMMANDS.

### ISSUE THREAD

**Issue by UnhingedNerd** [DragonSurvivalTeam/DragonSurvival#440]
### ■ Your Discord ID

99Mustang

### ■ Dragon Survival version

DragonSurvival_DragonEditorUpdate 0.10.7 (server +) 1.16.5 

### ■ Single game or server?

Local network (LAN, Hamachi, etc.)

### ■ Describe the bug

1- Turn into a dragon, turn back human and turn into dragon again. All your progress will be lost, both age and size and gained xp (made sure the config was set to save growup stage)

2- Insert dragon-altar or dragon-editor on chat command while in human form. Nothing will happen

### ■ Crash Report File and Logs

None

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/703448ea-7284-4e5c-ac77-75514963e5f2)
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki#-faq
