### ISSUE TITLE
[1.20.1 Enhancement]: Realcamera compatibility

### ISSUE THREAD

**Issue by Riazamurai** [DragonSurvivalTeam/DragonSurvival#447]
### ■ Your Discord ID or other contacts

riazamurai

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024

### ■ Forge/Neoforge version

forge-1.20.1-47.2.21

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

The real camera mod is only enabled when the gui is opened, 
I would like to see a setting added to config to unfix the camera.

**Comment by seelderr** [comment]
I'm not sure what is being asked here. Going to close for now, feel free to reopen if you have more information.
