### ISSUE TITLE
[1.20.1 Bug]: Incompatibility with GeckoLibOculusCompat'Forge-1.0.1.jar

### ISSUE THREAD

**Issue by DestinyPlayer** [DragonSurvivalTeam/DragonSurvival#450]
### ■ Your Discord ID or other contacts

destinyplayer - Discord

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024.jar

### ■ Forge/Neoforge version

Forge 47.2.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

> Full modlist:
> - DragonSurvival-1.20.1-09.01.2024.jar
> - geckolib-forge-1.20.1-4.4.4.jar
> - GeckoLibOculusCompat-Forge-1.0.1.jar

I installed GeckoLibIrisCompat (the Oculus/Forge version) to try and prevent any potential animation issues, as mentioned in the mod's own description, and then suddenly found out that it seems to be hard-incompatible with Dragon Survival, crashing immediately on startup. I went down to explicitly installing only GeckoLib, DragonSurvival and GeckoLibOculusCompat to check for anything else and, in the end, it seems that there is indeed a problem.

Honestly I don't really expect any fix, I just noticed that it does not seem to be mentioned anywhere in the wiki and wanted to bring it to the devs' attention if it is some sort of hard incompatibility that cannot be fixed, so that it can be added to the incompatibilities list.

### ■ Crash Report File and Logs

[crash-2024-03-25_11.46.31-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14741031/crash-2024-03-25_11.46.31-fml.txt)

**Comment by SiverDX** [comment]
that "fix" was dead on arrival and is not needed
