### ISSUE TITLE
[1.20.1 Bug]: Crashing Server

### ISSUE THREAD

**Issue by NikKeY7** [DragonSurvivalTeam/DragonSurvival#451]
### ■ Your Discord ID or other contacts

nikkey_080203

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024

### ■ Forge/Neoforge version

Forge 47.2.21

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

Server crashed, because mod try to Invoke the client class on the dedicated server.

### ■ Crash Report File and Logs

[crash-2024-03-30_17.05.25-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14812769/crash-2024-03-30_17.05.25-fml.txt)

**Comment by seelderr** [comment]
Can't repro, probably is fixed in a later version of 1.20.1
