### ISSUE TITLE
[1.20.1 Bug]: Alex's Caves Incompatibility

### ISSUE THREAD

**Issue by Maagick** [DragonSurvivalTeam/DragonSurvival#452]
### ■ Your Discord ID or other contacts

casseve

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024.jar

### ■ Forge/Neoforge version

Forge 47.2.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I am 2 blocks tall even as a newborn dragon. I can still fit in 1 block tall spaces but my head goes inside of the wall so I can't see anything. My body is below me. I know it's a mod conflict because the mod by itself doesn't have this issue but I can't figure out which one it is.

### ■ Crash Report File and Logs

https://mclo.gs/ifh8F7w

**Comment by Maagick** [comment]
It's Alex's Caves, removing that mod fixes the issue. Not sure why it's causing that.

**Comment by seelderr** [comment]
Duplicates #444
