### ISSUE TITLE
[1.19.2 Bug]: Cannot disable athletics ability for default blocks via server config

### ISSUE THREAD

**Issue by lool8421** [DragonSurvivalTeam/DragonSurvival#454]
### ■ Your Discord ID or other contacts

Discord: lool8421

### ■ Dragon Survival version

DragonSurvival-1.19.2-02.03.2024_stable.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Let's say i want to turn forest dragon into an ender dragon (because those seem to be the most similar i guess)

the line in the config file that would change the block-specific speedups from athletics ability (2nd repeatable passive skill) would look somewhat like this:

`forestSpeedupBlocks = ["minecraft:end_stone", "minecraft:obsidian", "minecraft:purpur_block"]`

However instead of granting speedups only on those blocks, the ability grants bonus speed when standing on the listed blocks AND default blocks, rather than listed ones only, so i still get speed III on grass or leaves when it's intended to only happen when standing on top of end blocks

On the other hand, mana regen blocks work just as intended, using the following config line actually overwrites the default settings (although it still takes sunlight or being on fire as a favorable condition which cannot be turned off), maybe it could be used as a clue to resolving that issue depending on how the code is written

`forestDragonManaBlocks = ["dragonsurvival:forest_source_of_magic", "minecraft:end_stone", "minecraft:obsidian", "minecraft:purpur_block"]`

testing: separated from other mods for the sake of making sure it is the mod itself, it still applies

in-game config displays configured blocks properly and the world managed to load as intended, so the syntax was actually correct, but still getting speed III on grass even though it's not supposed to

### ■ Crash Report File and Logs

when creating the world for the first time (didn't change defaultconfig):
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14890880/latest.log)

when loading the world for the second time:
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14890910/latest.log)

**Comment by seelderr** [comment]
Fixed in 1.21
