### ISSUE TITLE
[1.19.2 Bug]: Forest dragon breath "grows" iron bars

### ISSUE THREAD

**Issue by Dustfinity** [DragonSurvivalTeam/DragonSurvival#455]
### ■ Your Discord ID or other contacts

Dustfinity

### ■ Dragon Survival version

Play as Dragon Gothic Edition - 1.19.2 - 26.01.2024

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I Went down a tower with a spiral staircase, it had 3 passageways and to get through you need to go through iron gates, there were spawn blocks behind them. I was playing as a forest dragon, used the breath attack on the gates to hit the zombies behind and after a while the gates grew, expanded. I believe this has something to do with the plant growth passive of the breath.

**Comment by seelderr** [comment]
This is probably an incompatibility issue. But with the info here it would be extremely hard to track down and fix. Going to close for now.
