### ISSUE TITLE
[1.20.1 Bug]: Sea Dragon Eye Color Incorrectly applied on Right Eye

### ISSUE THREAD

**Issue by Marxon1134** [DragonSurvivalTeam/DragonSurvival#460]
### ■ Your Discord ID or other contacts

marxon1134

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024

### ■ Forge/Neoforge version

Forge 47.2.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Hue values for eye color are not properly applied for the right eye of sea dragons as seen in the image here, changing the color causes different scaling in the hue value.
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/20647096/fd5deb84-2210-4a51-a575-28a4746c44f9)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/20647096/82f7fdaa-6cda-4447-9593-7d7998514204)

### ■ Crash Report File and Logs

[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15180523/latest.log)

**Comment by Psither** [comment]
Sea dragons normally have different colored eyes.  One is normally blue, and the other purple.
