### ISSUE TITLE
[1.19.2 Bug]:  Charged effect chaining to caster

### ISSUE THREAD

**Issue by HakeT2Lab** [DragonSurvivalTeam/DragonSurvival#466]
### ■ Your Discord ID or other contacts

ItzalGaming

### ■ Dragon Survival version

Play as Dragon Gothic Edition - 09.05.2024

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Water Dragons can have the charged effect transferred to them from another entity, causing great vision impermeant. 

![2024-05-09_09 15 07](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/31541398/8bc9ad56-f259-4b3a-a106-20ec8632b34e)
![2024-05-09_09 15 00](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/31541398/7098a438-dd12-4e55-8f64-7eca461d48b4)

**Comment by BlackAures1** [comment]
There will be a config to fix this in the next update.
