### ISSUE TITLE
Lava completely invisible with any shader active, including the "internal" shader included with optifine.

### ISSUE THREAD

**Issue by DiscobolusCoyote** [DragonSurvivalTeam/DragonSurvival#47]
I quite badly wish to use this mod for my private server, but this issue is gonna make the game unplayable; is this an issue on my part somehow, or a glitch?

**Comment by BlackAures1** [comment]
The solution to most problems is in discord. 
![image](https://user-images.githubusercontent.com/43911230/124479380-e1f65f80-ddae-11eb-97bf-4ed64abc1af8.png)

**Comment by DiscobolusCoyote** [comment]
Thanks for the quick response. I did some more testing and found that it only occurs while playing a cave dragon, so it's not dangerous at least.
