### ISSUE TITLE
View obstructed by body in first person 1.15.

### ISSUE THREAD

**Issue by BlueYoshi68** [DragonSurvivalTeam/DragonSurvival#48]
I cant update to 1.16 due to other mods not being up to date, but while I'm in first person in 1.15, I cant see a damn thing cause my own body gets in my way. Is there a fix for this?

**Comment by ContraDergtion** [comment]
Can you please post a list of all mods you are currently using?

**Comment by Arcaryx** [comment]
This is an issue from the 1.15 versions, it was fixed in 1.16, but 1.15 is no longer supported.

**Comment by BlackAures1** [comment]
We have not supported version 1.15 for a long time and do not plan to update it ourselves in the future.

**Comment by BlueYoshi68** [comment]
well i figured it out, something to do with Ice and Fire, any ideas or am I damned to chose between one or the other

**Comment by Arcaryx** [comment]
If removing Ice and Fire fixes it, then this is probably a different issue than I was thinking of.

**Comment by BlueYoshi68** [comment]
yeah removing ice and fire fixed it. What do?

**Comment by Arcaryx** [comment]
1.16 will be the next forge LTS version, similar to 1.12
Basically for forge modding, 1.15 doesn't exist. It's just a stepping stone to 1.16

**Comment by BlueYoshi68** [comment]
well, that kinda sucks, cause the Mine and SLash mod (which is why I'm even using this shitty version to begin with) has "no plans to update to 1.16, but it's such a unique mod.
