### ISSUE TITLE
[1.20.1 Bug]: Game crashes when viewing your corpse from Corpse Mod if you died as a dragon

### ISSUE THREAD

**Issue by LassieGirl22** [DragonSurvivalTeam/DragonSurvival#488]
### ■ Your Discord ID or other contacts

landydoodles

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.05.2024__ALPHA.jar

### ■ Forge/Neoforge version

Forge 47.2.0

### ■ Single game or server?

Host site

### ■ Describe the bug

When playing with both Dragon Survival and the Corpse Mod (corpse-forge-1.20.1-1.0.12.jar) if you die as a dragon and return to the corpse to pick up the drops, you enter a crash loop once you load the chunk. I spoke with the Corpse mod creator and he said to bring it to your attention.

### ■ Crash Report File and Logs

https://gist.github.com/LassieGirl22/80d4b0507fe0bc29cc719cd61642e6ac

**Comment by seelderr** [comment]
Compat fixes not planned for 1.20.1 and lower
