### ISSUE TITLE
uhmm help XD

### ISSUE THREAD

**Issue by Lavinia120** [DragonSurvivalTeam/DragonSurvival#49]
I get errors when I want to play Dragon mod 
![Screenshot_11](https://user-images.githubusercontent.com/88888615/129356501-ef8fce85-49b3-400d-a956-37a1b75dff6c.png)
[crash-2021-08-13_14.55.40-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/6982357/crash-2021-08-13_14.55.40-fml.txt)

**Comment by Claycorp** [comment]
If the game still crashes please reopen this issue with a new crashlog as there could be multiple issues similar to this one. I just don't have the time to scour the whole code base after just joining the team to find them all.
