### ISSUE TITLE
[1.19.2 Bug]: Abilities UI Too big

### ISSUE THREAD

**Issue by TLCPlusPlus** [DragonSurvivalTeam/DragonSurvival#491]
### ■ Your Discord ID or other contacts

void.dragon

### ■ Dragon Survival version

DragonSurvival-GLOBAL_UPDATE-1.19.2-17.05.2024_beta_fix.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

![2024-05-17_11 09 19](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/4108374/bb25e0b6-9509-4295-a9be-8cef661c2a1c)

No matter what GUI Scale I use, its still too big.

**Comment by BlackAures1** [comment]
gothic modpack has an outdated texture pack. Wait for modpack update.
