### ISSUE TITLE
[1.19.2 Bug]: Dragon Editor "crystal lizard" accessory bugged on Sea Dragons

### ISSUE THREAD

**Issue by Kegami-Derg** [DragonSurvivalTeam/DragonSurvival#492]
### ■ Your Discord ID or other contacts

Kegami

### ■ Dragon Survival version

DragonSurival-1.19.2-17.05.2024_beta_fix

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

There is two options for "crystal lizard" in the dragon editor for sea dragons. If using the plus button go through accessories, it gets stuck on "crystal lizard" as well.

![unknown_2024 05 17-14 34](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/169824730/95400ccd-983b-4e41-9864-03883dff963f)

**Comment by BlackAures1** [comment]
Thanks, I'll fix that now.
