### ISSUE TITLE
[1.19.2 Bug]: Ore Excavation mod does not work when using tools inside the claw slot

### ISSUE THREAD

**Issue by HakeT2Lab** [DragonSurvivalTeam/DragonSurvival#493]
### ■ Your Discord ID or other contacts

ItzalGaming#4212

### ■ Dragon Survival version

DragonSurvival-BodyTypes-1.19.2-18.05.2024_beta_hotfix 

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

When in claw slot, silk touch only applies to block mined and is not used on those vein mined. I assume this also effects other enchantments.

**Comment by BlackAures1** [comment]
What kind of vein mining are we talking about?

**Comment by HakeT2Lab** [comment]
It is the one that is in the gothic modpack, ore excavator.

**Comment by BlackAures1** [comment]
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/d91a7005-87c1-49e6-99af-617bf2953c02)
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/074cec89-e686-436f-9626-8bf14eb809e3)

**Comment by seelderr** [comment]
Compat fixes are not planned for 1.20.1 and lower
