### ISSUE TITLE
[1.19.2 Bug]: Dragon Editor - Color Picker displaying incorrectly.

### ISSUE THREAD

**Issue by Hiirome** [DragonSurvivalTeam/DragonSurvival#496]
### ■ Your Discord ID or other contacts

Hiirome

### ■ Dragon Survival version

DragonSurvival-GLOBAL_UPDATE-1.19.2-18.05.2024_beta_hotfix2.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

When i'm on the Dragon Editor, and try to change the color of a part, the color Picker display incorectly, as shown in the screenshot below.

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22660018/bf042586-9607-4491-bcd6-33903758ddf7)

This is only a visual bug, it doesn't keep me from picking the color, but not seeing the bars and sliders correctly makes this a bit more complicated.
Also, when the mouse stops hovering on the color picker, the non regular appearence of the color picker briefly flickers before the picker is closed.

I am on a fresh install of the Play as Dragon : Gothic Edition, installed via the Curseforge Launcher, every settings have been left by default.

**Comment by seelderr** [comment]
I believe this is fixed in 1.19.2. The CL just needs to be pulled down.
