### ISSUE TITLE
[1.19.2 Bug]: Skills crossing over from Survival to multiplayer world

### ISSUE THREAD

**Issue by RainyDays1889** [DragonSurvivalTeam/DragonSurvival#501]
### ■ Your Discord ID or other contacts

rainydays1889

### ■ Dragon Survival version

DragonSurvival-1.19.2.03.2024_stable

### ■ Single game or server?

Local network (LAN, Hamachi, etc.)

### ■ Describe the bug

I'm playing on a multiplayer server with many mods, i cannot find any conflicting mods but unsure.
1. hop into a multiplayer server, chose dragon
2. hop out of multiplayer server and create a single player world
3. play in single player world and upgrade skills all the way up
4. go back into multiplayer and the skills transfer over

### ■ Crash Report File and Logs

no crash

**Comment by seelderr** [comment]
Retested. This seems to be fixed in a later version.
