### ISSUE TITLE
[1.20.1 Bug]: 

### ISSUE THREAD

**Issue by StrykerTheDragonOC** [DragonSurvivalTeam/DragonSurvival#502]
### ■ Dragon Survival version

1.20.1 latest

### ■ Forge/Neoforge version

47.2.32

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Cold Sweat Incompatibility.

### ■ Crash Report File and Logs

https://mclo.gs/As1BVa5 <---

**Comment by SiverDX** [comment]
related to https://www.curseforge.com/minecraft/mc-mods/dragon-survival-compatibility
new version should be up in bit to make the game load
