### ISSUE TITLE
[1.19.2 Bug]: 

### ISSUE THREAD

**Issue by xXPseudoNymphXx** [DragonSurvivalTeam/DragonSurvival#503]
### ■ Your Discord ID or other contacts

xxpseudonymphxx (TempestFlare) 

### ■ Dragon Survival version

DragonSurvival-GLOBAL_UPDATE-1.19.2-18.05.24_beta_hotfix2.jar

### ■ Single game or server?

Host site

### ■ Describe the bug

 
Not sure if you are already aware, but I already notice some issues with the new body types. At least with Northern, maybe similar issues for other types:
- Camera jumps a lot when running across different blocks of certain types (I noticed it happening a lot when in dungeons). Camera seems like it automatically jumps between normal and crouch position, or something similar.

- When flying up, we can glitch through tiles as if we reapers. All ages of Dragons are able to do this.

**Comment by seelderr** [comment]
I split this into two new issues: #505 and #506. Please try to report one issue at a time next time.
