### ISSUE TITLE
[1.20.1 Bug]: Startup crash with FarmersDelight-1.2.4 (?) mod and some addons are installed

### ISSUE THREAD

**Issue by SomeoneYouKonw** [DragonSurvivalTeam/DragonSurvival#504]
### ■ Your Discord ID or other contacts

exodusframe

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.05.2024

### ■ Forge/Neoforge version

Neoforge 47.1.105

### ■ Single game or server?

Single-player, Dedecatedserver

### ■ Describe the bug

Hello.

Today, when updateing my 1.20.1 modpack, I noticed that Dragon Survival-ALPHA is criticly incompadable with one (or more, depending on the other mods installed, it seems) of this addons for FarmersDelight-1.2.4, causing minecraft to crash during early initialisation phases. Here the list of addons:

nethersdelight-1.20.1-4.0
Delightful-1.20.1-3.5.3
nether-s-exoticism-1.20.1-1.2.7
nethers_exorcism-0.3.1D

### ■ Crash Report File and Logs

Crashreport have not been generated; this particular crash has appered on full modpack, but is fully reprodusable on clean setup; this crash seem to be caused by nethersdelight-4.0, other suspects were not present in this instant

[debug.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15442696/debug.log)
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15442697/latest.log)

**Comment by seelderr** [comment]
there seems to be something pretty wrong with nether-s-exoticism. i did fix some compatibility issues with nethersdelight, delightful, and farmers delight though. leaving this comment here so i know to mark this as fixed when the next round of patches comes through.

**Comment by SomeoneYouKonw** [comment]
The full modlist as following:
[server-mods.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15483688/server-mods.txt)
[client-mods.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15483768/client-mods.txt)

**Comment by seelderr** [comment]
This is now fixed in changelist e34e018
