### ISSUE TITLE
[1.19.2 Bug] : skin fetcher goes haywire on offline

### ISSUE THREAD

**Issue by Zdex007** [DragonSurvivalTeam/DragonSurvival#508]
### ■ Your Discord ID or other contacts

_zdex007_6993

### ■ Dragon Survival version

1.19.2-25.05.2024

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I’m offline and it keeps wanting to fetch a custom skin database.

### ■ Crash Report File and Logs

[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15504743/latest.log)

**Comment by BlackAures1** [comment]
I'll supplement for programmers: when you're offline, logs can get a lot of spam from failed attempts to load a skin. This needs to be fixed.

**Comment by Zhusiyuan354** [comment]
Want to add an option to allow players to manually switch between offline or online modes, I'll mention it in a future feedback.
