### ISSUE TITLE
Upgrade to 1.17.1 and higher

### ISSUE THREAD

**Issue by BruteTigrex** [DragonSurvivalTeam/DragonSurvival#51]
Do you plan to update the mod to the versions above, if so, when?

**Comment by Claycorp** [comment]
It will get updated to whatever versions possible but that means it requires [GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib) to be updated to the same game version for Forge too.

GeckoLib isn't making a 1.17 Forge version so it will depend on whatever it updates to next for Forge. (likely 1.18 as many people are going to do minimal support for 1.17 in Forge)
