### ISSUE TITLE
[1.20.1 Bug]: Point Blank incompatibility

### ISSUE THREAD

**Issue by UndeadVoxel** [DragonSurvivalTeam/DragonSurvival#510]
### ■ Your Discord ID or other contacts

un.deadvoxel (ΔᵉᵃᵈVᵒˣᵉˡ🇪🇪#2022)

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.05.2024_ALPHA

### ■ Forge/Neoforge version

Forge 47.2.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Everything is installed as required, modpack contains only three mods - Dragon survival, geckolib (forge 1.20.1 ver 4.4.4) and Vic's Point Blank (forge 1.20.1 ver 1.4.2). Game crashes instantly after launch.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/15522499/latest.log)

**Comment by SomeoneYouKonw** [comment]
Crap. Prob this is the same bug I have reported as #507, because I have Point Blank too! And removeing farmerdelight in my situation did not fix issue consistantly!

**Comment by seelderr** [comment]
This is now fixed in commit e34e018
