### ISSUE TITLE
[1.19.2 Bug]: The BallLightningEntity of the Sea Dragon causes the server to crash when there is a high density of monsters.

### ISSUE THREAD

**Issue by BKcatmoon** [DragonSurvivalTeam/DragonSurvival#516]
### ■ Your Discord ID or other contacts

bkcatmoon

### ■ Dragon Survival version

Dragon Survival-1.19.2-13.06.2024

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

[crash-2024-06-13_23.48.44-server.txt](https://github.com/user-attachments/files/15832592/crash-2024-06-13_23.48.44-server.txt)

**Comment by BlackAures1** [comment]
send the full file, not a copy of a piece.

**Comment by BKcatmoon** [comment]
I have updated the file.

**Comment by seelderr** [comment]
We know the root cause of this bug. It is due to a monster reflecting the projectile and therefore taking ownership of it. The code expects the owner of the ball to always be a player, so everything crashes. Will get fixed soon.

**Comment by BKcatmoon** [comment]
> 我們知道這個錯誤的根本原因。這是由於怪物反射了彈體並因此獲得了它的所有權。該代碼期望球的所有者始終是一名玩家，因此一切都會崩潰。很快就會修好。

ty

**Comment by Zeracronius** [comment]
I just had this error "brick" a save. I guess i was unlucky enough to have the lightningball go into lingering mode after being reflected and then get saved. This meant that every time i loaded the save, it would immediately crash again.
Managed to recover it by removing the lightning ball entity with save editing.
Glad to hear you've got a fix in the works!

**Comment by SiverDX** [comment]
if you encounter issues like this you can use https://www.curseforge.com/minecraft/mc-mods/neruina
it will stop your game from crashing when an entity encounters problems while ticking
