### ISSUE TITLE
[1.19.2 Bug]: The night vision of the sea dragon works out of water and does not run out

### ISSUE THREAD

**Issue by Raw206** [DragonSurvivalTeam/DragonSurvival#519]
### ■ Your Discord ID or other contacts

@aist7

### ■ Dragon Survival version

DragonSurvival-1.19.2-13.06.2024-all

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

There is a bug that causes the night vision of the sea dragon to work out of water and infinitely
Steps to try to replicate:
1-You must have a slow internet with high ping, more than 500ms|700ms
2-Create a small waterfall
3-Run it through as fast as you can
After a few attempts the above will occur
Exiting and returning to the server temporarily solves the problem

**Comment by seelderr** [comment]
We are only fixing critical issues with 1.19.2/1.20.1 at this time, this doesn't meet the bug bar.
