### ISSUE TITLE
First Person Mod conflicts with Dragon Survival.

### ISSUE THREAD

**Issue by BlueYoshi68** [DragonSurvivalTeam/DragonSurvival#52]
It doesn't cause a crash, but when both of these are installed, you can see your dragon body ontop of the one that dragon survival already provides, obstructing your view. Which is a shame cause the first person mod really adds something to the default experience and i'd really like to include both of these in my pack.

Both are on 1.16.5

**Comment by AlexiyOrlov** [comment]
I added an option to turn off the first person model in the new version.
