### ISSUE TITLE
[1.20.1 Bug]: Conflict with Some Assembly Required mod

### ISSUE THREAD

**Issue by 974148693** [DragonSurvivalTeam/DragonSurvival#522]
### ■ Your Discord ID or other contacts

pinky payload#9154

### ■ Dragon Survival version

DragonSurvival-1.20.1-11.06.2024

### ■ Forge/Neoforge version

1.20.1,Forge 47.2.32

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I am playing DS with Some Assembly Required mod in singleplayer,and i disabled Dragonfoods in serverconfig.
Sandwiches from this mod doesn't restore any hunger,i ate them just like ate air.
other food working good.

**Comment by seelderr** [comment]
Compatibility fixes are not planned for 1.20.1 and lower
