### ISSUE TITLE
[1.19.2 Bug]: No distinction between server and client

### ISSUE THREAD

**Issue by BKcatmoon** [DragonSurvivalTeam/DragonSurvival#524]
### ■ Your Discord ID or other contacts

bkcatmoon

### ■ Dragon Survival version

DragonSurvival-1.19.2-13.06.2024

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

When I started the server, I encountered an issue mentioning client-side code in the module. It might be that the module doesn't distinguish between client-side and server-side components. This hasn't caused major problems as my friends and I can still play normally, but I feel it's important to report this.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/15847714/latest.log)

**Comment by seelderr** [comment]
This is a problem throughout the codebase. I'm looking into doing a pass where I distinguish what code is actually needed on the client vs server the 1.21 refactor and correctly annotating it, but it is a long process and is pretty low impact to the user.

**Comment by BlackAures1** [comment]
> This is a problem throughout the codebase. I'm looking into doing a pass where I distinguish what code is actually needed on the client vs server the 1.21 refactor and correctly annotating it, but it is a long process and is pretty low impact to the user.

close?
