### ISSUE TITLE
[1.20.1 Bug]: royal hunt  crash

### ISSUE THREAD

**Issue by Shishiqyu** [DragonSurvivalTeam/DragonSurvival#535]
### ■ Your Discord ID or other contacts

shishiq

### ■ Dragon Survival version

dragonsurvival-1.20.1-16.06.2024

### ■ Forge/Neoforge version

Neoforge - 1.20.1

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

If there is a shooter near the dragon player and player gets royal hunt status, game crashes.
Video demonstrating the bug: https://youtu.be/RCsrthSkgjI

### ■ Crash Report File and Logs

[crash-2024-06-17_22.21.21-client.txt](https://github.com/user-attachments/files/15876409/crash-2024-06-17_22.21.21-client.txt)
[crash-2024-06-17_22.24.39-client.txt](https://github.com/user-attachments/files/15876410/crash-2024-06-17_22.24.39-client.txt)
[crash-2024-06-17_22.25.39-client.txt](https://github.com/user-attachments/files/15876411/crash-2024-06-17_22.25.39-client.txt)

**Comment by seelderr** [comment]
fixed in next patch
