### ISSUE TITLE
[1.20.1 Bug]: Entity Type Name Above Player

### ISSUE THREAD

**Issue by LootDust** [DragonSurvivalTeam/DragonSurvival#537]
### ■ Your Discord ID or other contacts

Crode#3322

### ■ Dragon Survival version

DragonSurvival-1.20.1-16.06.2024
GeckoLib-1.20.1-4.4.6

### ■ Forge/Neoforge version

Forge 47.2.20

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

When I created a new world and chose to be a dragon, a hologram written "entity.dragonsurvival.dummy_dragon" appered above my player character. I first noticed this bug in my own modpacks and I tried to find out which mod causes this. It turns out that thr bug is made by DragonSurvival itself while I disabled all other mods except DS and GeckoLib. 
Btw, this situation was also found in DragonSurvival-1.20.1-11.06.2024. I cleared config files and it solved, but this does not work again this time.

**Comment by BlackAures1** [comment]
Install Neoforge instead Forge
