### ISSUE TITLE
[1.20.1 Bug]: java.lang.NullPointerException: Cannot invoke

### ISSUE THREAD

**Issue by Cue15** [DragonSurvivalTeam/DragonSurvival#550]
### ■ Your Discord ID or other contacts

seniorwaffles.6335

### ■ Dragon Survival version

dragonsurvival-1.20.1-16.06.2024

### ■ Forge/Neoforge version

Forge - 47.3.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I have read the wiki and installed DS correctly. In my singleplayer world, I got the Evil Dragon effect and eventually knights with their dogs started spawning (I don't know what they're called). Wave 2 came, and my world crashed with the crash report attached below, talking about an EntityRender being null. Now, whenever I log onto that world, it immediately crashes again with the same crash report.
I did not look what level of the evil dragon effect I had, all I remember is seeing a group of 15-20 knights and the crossbow people spawn in. Everything else worked just fine until the (raid party? knight army? sorry!) came.

### ■ Crash Report File and Logs

[crash-2024-06-22_18.23.42-client.txt](https://github.com/user-attachments/files/15941972/crash-2024-06-22_18.23.42-client.txt)

**Comment by seelderr** [comment]
this is fixed in the next patch, will be out shortly
