### ISSUE TITLE
[1.20.1 Bug]: Crash when jumping while Trapped

### ISSUE THREAD

**Issue by MetaflameDragon** [DragonSurvivalTeam/DragonSurvival#553]
### ■ Your Discord ID or other contacts

Reply directly on GitHub

### ■ Dragon Survival version

dragonsurvival-1.20.1-25.06.2024.jar

### ■ Forge/Neoforge version

NeoForge 47.1.106

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Jumping with the Trapped status effect crashes the game.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/15972976/latest.log)

**Comment by MetaflameDragon** [comment]
This seems to be caused by canceling the jumpEvent, which is not cancelable.

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/1.20.1/src/main/java/by/dragonsurvivalteam/dragonsurvival/common/handlers/EventHandler.java#L248

**Comment by seelderr** [comment]
54bebf0
