### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by DragonFan12** [DragonSurvivalTeam/DragonSurvival#56]
It used to load just fine and now it doesnt load please help?

![Minecraft Launcher 2021_09_11 21_19_56](https://user-images.githubusercontent.com/90527697/132959133-7aab0e25-26d6-4a68-bb71-197e3cb145f8.png)

[crash-2021-09-11_21.19.33-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/7148392/crash-2021-09-11_21.19.33-client.txt)

**Comment by BlackAures1** [comment]
Update your version of Forge and Dragon Survival. If you've changed anything in the config, make sure you haven't made any errors in it.

**Comment by DragonFan12** [comment]
I have somehow managed to fix it but thanks for the help if it happens
again I will use your advice for sure thanks!
