### ISSUE TITLE
[1.20.1 Bug]: Incompatibility with Mowzies Mobs

### ISSUE THREAD

**Issue by TrueBlueFlare** [DragonSurvivalTeam/DragonSurvival#560]
### ■ Your Discord ID or other contacts

trueblueflare#0

### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all

### ■ Forge/Neoforge version

Forge - 47.3.1

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Incompatibility with Mowzies Mobs. The game crashes when using items from Mowzies Mobs right-click functionality, such as The Axe of a Thousand Metals or the Ice Crystal.
[Link to incompatible mod.](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)

### ■ Crash Report File and Logs

[crash-2024-06-27_17.37.06-client.txt](https://github.com/user-attachments/files/16023100/crash-2024-06-27_17.37.06-client.txt)
[latest.log](https://github.com/user-attachments/files/16023103/latest.log)

**Comment by seelderr** [comment]
#561

**Comment by TrueBlueFlare** [comment]
Nice, time to wait for this fix to release on CF I guess so I can re-add it to my pack
