### ISSUE TITLE
[1.20.1 Bug]: Ticking Entity Crash when specific player logs in to server

### ISSUE THREAD

**Issue by SyntaxError73** [DragonSurvivalTeam/DragonSurvival#569]
### ■ Your Discord ID or other contacts

@peridoodle

### ■ Dragon Survival version

DragonSurvival - 1.20.1-27.06.2024-all

### ■ Forge/Neoforge version

Forge - 47.2.0

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

A certain dragon player crashes the server when logging in to the modded server, causing all other players including the affected player to disconnect. It seems to be a ticking entity error. Could the dragon player entity be affected? This only happens with one player of my server and none of the others.

I am the HOST of the server. I can attach the modpack I use for my server as well.

https://drive.google.com/file/d/1WSvhgdN-4aUZXfDYPT9rWwcAtceDmdbK/view?usp=sharing < Modpack Link

### ■ Crash Report File and Logs

[crash-2024-07-04_23.01.10-server.txt](https://github.com/user-attachments/files/16103345/crash-2024-07-04_23.01.10-server.txt)

This also mentions the Bola for some reason.

**Comment by SyntaxError73** [comment]
New information. The player who crashed the server was fighting horsemen when the server crashed.

**Comment by Psither** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/issues/554
