### ISSUE TITLE
[1.20.1 Bug]: Silk touch still drops dragon dust

### ISSUE THREAD

**Issue by MetaflameDragon** [DragonSurvivalTeam/DragonSurvival#572]
### ■ Your Discord ID or other contacts

Reply directly on GitHub

### ■ Dragon Survival version

dragonsurvival-1.20.1-21.06.2024

### ■ Forge/Neoforge version

Forge 47.3.0

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

Elder Dragon Dust drops from ores even when mining them with silk touch. This can lead to infinite renewability. Tested with Deepslate Lapis and Redstone.

**Comment by seelderr** [comment]
Fixed in 2150f52
