### ISSUE TITLE
[1.19.2]: Dragon Beacon should return the ingot used to craft it in addition to the Beacon when refunded

### ISSUE THREAD

**Issue by BKcatmoon** [DragonSurvivalTeam/DragonSurvival#576]
### ■ Your Discord ID or other contacts

bkcatmoon

### ■ Dragon Survival version

DragonSurvival-1.19.2-22.06.2024

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

After imbuing the Dragon Beacon with specific dragon attributes, it can be placed in the crafting interface to return an Empty Dragon Beacon and a Beacon. However, crafting the Dragon Beacon itself does not consume the Beacon; returning items should align with the materials consumed during the creation of the Dragon Beacon, such as a Netherite Ingot.

https://github.com/DragonSurvivalTeam/DragonSurvival/assets/108355376/0a92875c-aab1-4988-a9dc-36e2a122de6a

**Comment by BlackAures1** [comment]
Thank you for your consideration
