### ISSUE TITLE
[1.20.1 Bug]: A pic with fortune doesn't drop any dust

### ISSUE THREAD

**Issue by Iplaymods** [DragonSurvivalTeam/DragonSurvival#577]
### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all.jar

### ■ Forge/Neoforge version

Forge-47.3.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I was playing, thinking the fortune would give me more dust when drop or increase the chances of it droping. When I tried it I noticed that no ores droped any dust. I tested it with a stack of coal ores and no dust came out.

**Comment by seelderr** [comment]
fortuneLevel = tool.getEnchantmentLevel(Enchantments.BLOCK_FORTUNE);
silkTouchLevel = tool.getEnchantmentLevel(Enchantments.BLOCK_FORTUNE);

🤦

Fixed in 2150f52

**Comment by Iplaymods** [comment]
I'm confused, the way the code is worded it looks like it's supposed to not work.

**Comment by seelderr** [comment]
fortune != silktouch

**Comment by Iplaymods** [comment]
Is coded not to work? You did explain anything

**Comment by seelderr** [comment]
fortune will now correctly drop dust, that is all you need to know :)

**Comment by Iplaymods** [comment]
So it didn't before?
Also thank you for responding to me.
