### ISSUE TITLE
Mod Conflict, Pokecube. Server-Side Crash when the Ender Dragon spawns.

### ISSUE THREAD

**Issue by Wilevar** [DragonSurvivalTeam/DragonSurvival#58]
Love the mod's concept, and am looking forward to it reaching a more finished state. Unfortunately it has a server-only conflict with Pokecube AOI, causing a Ticking World Crash when entering The End, shortly after the ender dragon delivers her first statement.

Through mod removal testing I've confirmed that it's a conflict with Pokecube. Remove either it or Dragon Survival fixes the crash. I'll submit a report to Pokecube as well to let them know.

Crash Report:
https://pastebin.com/sv05aVPV

Forge Version:
forge-1.16.5-36.2.0

Mod Version:
0.0.39

**Comment by BlackAures1** [comment]
Thanks for the warning, we'll see what we can do about that.

**Comment by Wilevar** [comment]
Thanks. ^_^
For reference, I'm not using a any server hosting. Just a private server running from a command line batch file. Standard Forge server setup.

**Comment by BlackAures1** [comment]
Mohist is not hosting, but a server core that allows you to use Forge mods and Bukkit plugins on the same server. If you meant what I wrote on Curseforge.

**Comment by Wilevar** [comment]
Ah. Didn't know that. But no, I'm not using any hybrid server software. Just Forge.

**Comment by Wilevar** [comment]
Troubleshot this with Thutmose over discord and discovered that the crash has to do with a config option for Pokecube that deactivates vanilla monsters and how Dragon Survival reacts to that with the ender dragon. [Link to the other github issue here](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues/804).

**Comment by Thutmose** [comment]
The specific details seem to be somehow related to pokecube removes vanilla spawns if the config is enabled:

https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.16/src/main/java/pokecube/core/handlers/events/EventsHandler.java#L586

This is currently done by removing the matching spawn entries from the list passed along the `WorldEvent.PotentialSpawns` event fired by `net.minecraftforge.event.ForgeEventFactory.getPotentialSpawns` when vanilla is trying to decide what mobs spawn at a site.

It appear that somewhere a spawn entry with something null in weight is added to this list?

**Comment by AlexiyOrlov** [comment]
What options must be enabled to trigger the crash? I tested the mods with the defaults and it didn't crash.

**Comment by Wilevar** [comment]
Pokecube-common.tmol

[Spawning]
....
# Vanilla monsters will not spawn via normal spawning, this does not prevent mob spawners or special spawns. [Default: false]
	deactivateMonsters = false
	
If set to true, the crash happens.

**Comment by AlexiyOrlov** [comment]
Ok, I set it true, but it still doesn't crash. Can't reproduce...

**Comment by AlexiyOrlov** [comment]
Ok, I managed to trigger the crash and I found that it is caused by magical predators disabled in the config, that is, in the section [common.predator.spawnChances] `weight` is set to 0. This what causes to add their spawn entry with zero weight, and the crash. Until I fix this, a workaround would be setting the weight to 1 and leave their spawn biome list blank, that is, in section [common.predator.spawnBiomes] set `include` to `[]`.

**Comment by Wilevar** [comment]
Understood. Having checked my config, I can confirm that I do have those spawn weights set to `0.0`. They were spawning from pokemon deaths on a regular basis, likely due to the sheer amount of pokemon murder when training.

Thanks for the attention and the work-around! Looking forward to Dragon Survival getting more features. ^_^
