### ISSUE TITLE
[1.20.1 Bug]: Compatibility issues with Corail's Tombstone

### ISSUE THREAD

**Issue by BKcatmoon** [DragonSurvivalTeam/DragonSurvival#589]
### ■ Your Discord ID or other contacts

bkcatmoon

### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all

### ■ Forge/Neoforge version

Forge-47.3.0

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

When Dragon Survival and Corail's Tombstone are installed together, Dragon Treasure drops Corail's Tombstone scrolls when excavated. The scrolls from that mod should only drop when defeating the Wither. I have tried using KubeJS to modify the drops from Dragon Treasure, but the scrolls still drop. Therefore, I suspect that some attributes of Dragon Treasure are causing Corail's Tombstone to misjudge. I don't know how to fix this, so I'm submitting it here.

By the way, the latest version of Dragon Survival for 1.19.2 does not cause this issue.

**Comment by SiverDX** [comment]
due to that mod being closed-source it's unlikely we'll spend the time searching for the issue

**Comment by BlackAures1** [comment]
This is not the first time this mod has had problems. The developer fixed them, but apparently it's broken again. It is better to use other grave mods analogs.

**Comment by Corail31** [comment]
@BKcatmoon 8.7.1 is what you need ;)
@BlackAures1 your comment is funny as i only add compat to please players (you don't have api and have changed your inventory capability in the past ;) )
