### ISSUE TITLE
Server lags and crashes

### ISSUE THREAD

**Issue by tyggna** [DragonSurvivalTeam/DragonSurvival#59]
I have no idea what's causing this, but I get one exception every 30-50ms on my client console when logged into a server.  

[network.play.ClientPlayNetHandler] Unknown custom packet identifier: dragonsurvial:main 

This occurs when a player becomes a dragon, and goes away when they revert back to human.  It's particularly bad when there are two players as dragons and the lag becomes enough to crash the server.

You can try this in my modpack for convenience: Technic launcher - Learn 2 Spell

I suspect it has something to do with Pocket Dimensions 2 and Dragon survival.

Here are the appropriate versions of what I'm running:
Minecraft 1.16.5
Forge 36.2.1

**Comment by AlexiyOrlov** [comment]
Try the new mod version, 0.0.42.

**Comment by tyggna** [comment]
I just updated.  The error messages are much less numerous on my client, but the server still lags beyond 60s/tick and crashes when two class 3 dragon players and a human are on (without dragon survival forms, it can handle 10+ people pretty well),

I'm going to start stripping away other mods that might be interfering.
