### ISSUE TITLE
[1.20.1 Bug]: Can't join or create a world

### ISSUE THREAD

**Issue by Lantern377** [DragonSurvivalTeam/DragonSurvival#593]
### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all

### ■ Forge/Neoforge version

NeoForge 47.1.106

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Game freezes for minutes and becomes unresponsive when I try to join or create a world. This bug didn't occur in the last month.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/16251913/latest.log)

**Comment by SiverDX** [comment]
https://github.com/FirDragon/DragonSurvivalFix/releases might fix your issue until a new version of this mod is released

**Comment by BlackAures1** [comment]
> https://github.com/FirDragon/DragonSurvivalFix/releases might fix your issue until a new version of this mod is released

Is this fix on the official branch for posting?

**Comment by SiverDX** [comment]
> > https://github.com/FirDragon/DragonSurvivalFix/releases might fix your issue until a new version of this mod is released
> 
> Is this fix on the official branch for posting?

probably this one https://github.com/DragonSurvivalTeam/DragonSurvival/commit/4f852bd8de5468b6ed296ee989dedab12b993fa4

**Comment by SiverDX** [comment]
1.19.2 is this one https://github.com/DragonSurvivalTeam/DragonSurvival/commit/1ff345be828292261b8c1c7bcb47164b0e62a33a

**Comment by BlackAures1** [comment]
fixed in latest
