### ISSUE TITLE
[1.20.1 Bug]: Embeddium Breaks Lava Vision & Makes Armor in 1st Person Invisible

### ISSUE THREAD

**Issue by Jagkros** [DragonSurvivalTeam/DragonSurvival#595]
### ■ Your Discord ID or other contacts

voraciousdragon

### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all.jar

### ■ Forge/Neoforge version

Forge - 47.3.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I am a server host and I have confirmed this issue affects my players as well.

Embeddium appears to be the culprit:
- https://www.curseforge.com/minecraft/mc-mods/embeddium

Visual Issue:
- When Dragon Survival is installed with Embeddium (required dependency for Oculus) I can't see dragon armor in 1st person and lava vision does not work. 

Steps to try and resolve:
- Removing the Oculus mod did not fix the issue. The issue appears to be with Embeddium specifically.
- Changing Embeddium's in-game settings did not fix the issue.
- Installing just Dragon Survival, Embeddium and GeckoLib did not fix the issue.
- [New] Installing Iris/Oculus & GeckoLib Compat did not fix the issue. Dragon Survival failed to load.

Steps to re-create the issue:
1. Install Dragon Survival, Geckolib, and Embeddium.
2. Create a single player world or join a multiplayer server.
3. Become a Cave Dragon, and find or place some lava. 
4. Activate Lava Vision. You will be unable to see through the lava.
5. Find or create some armor and put it on. You will not see your armor in first person.

**Comment by SiverDX** [comment]
the geckolib compat thing is bait and doesn't do anything

in regards to vision not working - you mean only when looking at the fluid from above etc. I'm assuming? It should work while you're submerged

Since Embeddium / Sodium like mods implement a custom fluid renderer there would be some compat needed
Will have to look whether this can be done or not since that mod is complex af

**Comment by Jagkros** [comment]
> the geckolib compat thing is bait and doesn't do anything
> 
> in regards to vision not working - you mean only when looking at the fluid from above etc. I'm assuming? It should work while you're submerged
> 
> Since Embeddium / Sodium like mods implement a custom fluid renderer there would be some compat needed Will have to look whether this can be done or not since that mod is complex af

Yes, it works while you are under the lava. My players and I don't mind too much, but I thought it'd be an important issue to mention.

**Comment by seelderr** [comment]
@SiverDX can you confirm this is fixed in 1.21 and close?

**Comment by SiverDX** [comment]
fixed for...
- 1.20.1: Embeddium
- 1.21: Sodium and Embeddium

did not notice any issues with the armor in 1.20.1 (I also did no changes regarding that)
(not sure if this issue should be closed already since there is no published version with these fixes)

**Comment by SiverDX** [comment]
See comment above
