### ISSUE TITLE
[1.20.1 Bug]: Trying to eat out of a placed Caupona soup bowl will crash a dragon's client

### ISSUE THREAD

**Issue by Not-February** [DragonSurvivalTeam/DragonSurvival#598]
### ■ Your Discord ID or other contacts

notfebruary

### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all.jar

### ■ Forge/Neoforge version

Forge 47.3.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

This issue only occurs if Dragon Survival is installed alongside [Caupona](https://www.curseforge.com/minecraft/mc-mods/caupona). Caupona adds modular food items that can be placed in-world and right-clicked to be eaten out of.

If a dragon player right-clicks such a placed dish, their client will crash. Human players are fine.

It would also probably be a good idea to have a way of preventing dragon players from interacting with specific blocks like this one that don't align with dragon diets - maybe with a configurable block tag per dragon type?

I'm not sure whether this is Caupona's fault or Dragon Survival's; if it's on Caupona's end I will make an issue on that mod's issue tracker.

Caupona version: ``0.4.9``

### ■ Crash Report File and Logs

[crash-2024-07-19_10.19.07-client.txt](https://github.com/user-attachments/files/16315259/crash-2024-07-19_10.19.07-client.txt)
[debug.log](https://github.com/user-attachments/files/16315260/debug.log)
[latest.log](https://github.com/user-attachments/files/16315261/latest.log)

**Comment by seelderr** [comment]
Compatibility fixes are not planned for 1.20.1 and lower at this moment
