### ISSUE TITLE
---- Minecraft Crash Report ----2

### ISSUE THREAD

**Issue by BlackAures1** [DragonSurvivalTeam/DragonSurvival#6]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/17/21 7:50 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['_Kojiki_'/6444, l='MpServer', x=-69.32, y=59.00, z=4.20], RemoteClientPlayerEntity['Shaenarys'/246, l='MpServer', x=82.67, y=52.68, z=2.70]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: DimensionType{minecraft:the_end}
	Level name: MpServer
	Level seed: 934184822763882444
	Level generator: ID 03 - amplified, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (256,77,-224), Chunk: (at 0,4,0 in 16,-14; contains blocks 256,0,-224 to 271,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 5518219 game time, 1690752 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:572)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$407/1821010113.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 583698896 bytes (556 MB) / 2637692928 bytes (2515 MB) up to 6114770944 bytes (5831 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6560m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.15.2_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.50.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.50
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.50-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.50-universal.jar Forge {forge@31.2.50 DONE}
		DragonSurvival-0.0.26.jar Dragon Survival {dragonsurvival@0.0.26 DONE}
		geckolib-forge-1.15.2-3.0.15.jar GeckoLib Example Mod {geckolib3@3.0.15 DONE}
		journeymap-1.15.2-5.7.0.jar Journeymap {journeymap@5.7.0 DONE}
		jei-1.15.2-6.0.3.16.jar Just Enough Items {jei@6.0.3.16 DONE}
	Launched Version: forge-31.2.50
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 465.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, programer_art
	Current Language: Français (France)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G6
	OptiFine Build: 20210124-205244
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 465.89
	OpenGlRenderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by AlexiyOrlov** [comment]
Should be fixed by now
