### ISSUE TITLE
[1.20.1 Bug]: crash issue

### ISSUE THREAD

**Issue by White-Rose21** [DragonSurvivalTeam/DragonSurvival#607]
### ■ Your Discord ID or other contacts

Amy Shiko #460239

### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all jar

### ■ Forge/Neoforge version

forge 1.20.1

### ■ Single game or server?

Host site

### ■ Describe the bug

hello we started encountering a lot of crashing after having downloaded this mod. we really like this mod and wish to keep it but cannot seam to get the crashing to stop, after the crash if there are things in our inventory half the time it will go missing and we will have to start all over again to recollect it. our server is a multiplayer server and a 
lot of people enjoy playing on it so if there is a way to work the coding where the mod will work with other mods that would be wonderful.

![image_2024-07-22_190647322](https://github.com/user-attachments/assets/79139ff4-c7cf-43d0-9d53-32ad6ca4d014)

**Comment by Psither** [comment]
Your version is out of date.  This bug has been fixed in the latest patch.

**Comment by White-Rose21** [comment]
ok weeelll im not seeing any other versions that might be up to date can you maybe send me a link to the updated one?

**Comment by White-Rose21** [comment]
also was it an update for 1.20.1?

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/dragons-survival/files/5543771
