### ISSUE TITLE
[1.19.2 Bug]: Doors not placeable above certain height (Old world height limit possibly?)

### ISSUE THREAD

**Issue by Charmanth** [DragonSurvivalTeam/DragonSurvival#615]
### ■ Your Discord ID or other contacts

Charmanth

### ■ Dragon Survival version

DragonSurvival-1.19.2-18.07.2024_fix.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

First noticed this on a server, but checked in single player hence the single player tag.  You cannot place doors above level 255 (Current world height is 320)  Nothing happens when you right click to place a door above this level.

### ■ Crash Report File and Logs

No crash, just inability to place doors high up.

**Comment by Psither** [comment]
![image](https://github.com/user-attachments/assets/d15f1e32-4191-478e-9981-231ce51c6ab9)

**Comment by Psither** [comment]
#616

**Comment by Charmanth** [comment]
That was quick.
