### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by bingheng-wlm** [DragonSurvivalTeam/DragonSurvival#62]
How do you draw your skin? What software is used? Photoshop is too laggy and doesn't feel right.

**Comment by Claycorp** [comment]
You use whatever software you wish that can edit a PNG file.
[GIMP](https://www.gimp.org/) is a widely used tool. Otherwise Paint or Paint.net will work fine too. Just follow the [directions](https://dragons-survival.fandom.com/wiki/Skins) for making skins.
