### ISSUE TITLE
[1.19.2 Bug]: Server Crashes; Ticking entity

### ISSUE THREAD

**Issue by KJEntytek303** [DragonSurvivalTeam/DragonSurvival#624]
### ■ Your Discord ID or other contacts

kjentytek303

### ■ Dragon Survival version

DragonSurvival-1.19.2-22.06.2024.jar, after first crash updated to
DragonSurvival-1.19.2-18.07.2024_fix.jar, didn't helped.

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

Server crashes as soon as i join; ticking entity (likely dragon hunter or similar). Worked fine before.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/16474331/latest.log)
[crash-2024-08-02_21.06.53-server.txt](https://github.com/user-attachments/files/16474333/crash-2024-08-02_21.06.53-server.txt)

**Comment by KJEntytek303** [comment]
Weird thing is that after i tped myself 2000 blocks away via editing nbt player data server works fine.

**Comment by KJEntytek303** [comment]
Unfortunatelly, as soon as i go back to this location, server dies. I noticed dragon hunter entities, so it might be their fault.

**Comment by KJEntytek303** [comment]
Also there is this in the log:
at by.dragonsurvivalteam.dragonsurvival.common.entity.creatures.Shooter.performBolasThrow(Shooter.java:114) ~[DragonSurvival-1.19.2-22.06.2024.jar%23156!/:1.19.2-22.06.2024] {re:classloading}

**Comment by seelderr** [comment]
This is fixed in the latest version, make sure to update
