### ISSUE TITLE
[1.20.1 Bug]: 

### ISSUE THREAD

**Issue by Wakatsu** [DragonSurvivalTeam/DragonSurvival#628]
### ■ Your Discord ID or other contacts

wakazu

### ■ Dragon Survival version

this problem exists in literally all of them

### ■ Forge/Neoforge version

doesn't matter

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Sea Dragon eyes have different color overlays
For example if left eye is purple - right will be cyan, if left eye is yellow - left becomes pink, etc.
Other dragons don't seem to have that issue.
Please fix

**Comment by Psither** [comment]
Not a bug.

**Comment by Psither** [comment]
https://github.com/DragonSurvivalTeam/DragonSurvival/wiki/3.-Customization#-known-bugs

**Comment by Wakatsu** [comment]
Eh? Then maybe list it somewhere as a feature, something like "these dragons are known to have stunning heterochromatic eyes" or something like that. Because you WILL get more of these reports otherwise, as it very clearly looks like a bug.

**Comment by Wakatsu** [comment]
Also an option to have normal eyes on sea dragons could be nice too

**Comment by BlackAures1** [comment]
Not planned/not a bug
