### ISSUE TITLE
[1.20.1 Not-Exactly-a-Bug]: Move parts of the Dragon Editor further apart

### ISSUE THREAD

**Issue by Wakatsu** [DragonSurvivalTeam/DragonSurvival#629]
### ■ Your Discord ID or other contacts

wakazu

### ■ Dragon Survival version

all of them that have Dragon Editor

### ■ Forge/Neoforge version

doesn't matter

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

While not exactly a bug, this does decrease the enjoyment of the mod for quite a bit
In Dragon Editor option lists pretty much sit atop the dragon itself, so you either have to constantly check interface on \ off when designing your dragon, or minimize them into a barely visible dot, at with point all the intricate details become indistinguishable.
Please move the elements of the UI further apart or (ideally) make them stick to the edges of the screen instead of having fixed position.
![UI](https://github.com/user-attachments/assets/9dd4df1e-8b0f-48f2-b008-b71d763e10b5)

**Comment by BlackAures1** [comment]
Not planed

**Comment by Wakatsu** [comment]
Why not tho? Editor as it is now is very cumbersome and it's not that hard to fix, just tweak values a bit. Or am I missing something here?

**Comment by seelderr** [comment]
Turn up your GUI scale
