### ISSUE TITLE
Knights crash.

### ISSUE THREAD

**Issue by Shumbalion** [DragonSurvivalTeam/DragonSurvival#63]
Bug report: Possibly the knights, unable to recover game. 
**Single play**
**DragonSurvival-1.16.5-0.0.42.jar** 
**geckolib-forge-1.16.5-3.0.44.jar**
**Forge 36.1.32**
Had a few crashes, always a little while after the knights had spawned, that I was enjoying fighting. 
They ended up spawn camping me as I started on a very small island. Eventually I got a bad save point a second before the crash.
I was in single player, but used ‘open to lan’ to make it load up in spectator mode - in hopes that, if I was not a target it may fix something. But it still crashed. 
Here is the last crash report from that. 
Loving the mod so far =3
https://pastebin.com/zLdrEpQY

**Comment by Claycorp** [comment]
To load the world for now set `removeErroringEntities` to true in `\saves\YourWorldNameHere\serverconfig\forge-server.toml`. Then load the world till it runs again. It should remove the broken entities so you can play again.

You can also disable the hunters in the DS common config by setting `allowHunterSpawning` to false. That should stop them from spawning so you don't get another crash till a fix comes.

**Comment by AlexiyOrlov** [comment]
Also, update the forge to version at least 36.2.0

**Comment by Shumbalion** [comment]
I’m not sure if it’s specifically the hunter as they were not seen in previous crashes, although one may have spawned without me seeing it. 
removeErroringEntities just crashed the game before it could load, I tried a few times. 
I recovered by making a clone of the map and copying most files across. I had to kill the existing group before I could copy the player level.dat to the recovery world. So it’s when they are hostile that the game crashes.

I then updated forge to 36.2.0.
I reloaded the broken world and it has not crashed with the existing group that are spawned in, allowHunterSpawning is set to false.

I will continue with the broken world with allowHunterSpawning = true however, to see if I can reproduce the crash with this version of forge. 

You may consider upgrading the minimum forge requirements on the mod page. I simply chose the version of forge that was named in the requirements to start.

Will let you know if it get another crash with 36.2.0.
=3
