### ISSUE TITLE
[1.20.1 Bug]: Sea Dragon underwater Night Vision doesn't work with shaders present

### ISSUE THREAD

**Issue by Wakatsu** [DragonSurvivalTeam/DragonSurvival#630]
### ■ Your Discord ID or other contacts

wakazu

### ■ Dragon Survival version

DragonSurvival-1.20.1-18.07.2024

### ■ Forge/Neoforge version

Forge 47.3.1

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

Night Vision straight up doesn't work. The mana is removed, the cooldown is applied, but nothing happens visually

**Comment by BlackAures1** [comment]
Specify the name of the shader. It works with all shaders that I know of.

**Comment by Wakatsu** [comment]
Sildur's Enhanced Default v1.16 Fast and ComplementaryUnbound_r5.2.2
Tested with both, doesn't work

**Comment by SiverDX** [comment]
Added compatibility for water vision
Tested with `Complementary Unbound 5.2.2`

Without water vision:
![image](https://github.com/user-attachments/assets/0be948fa-92ee-4dfa-a781-5f427f8e0668)


With water vision:
![image](https://github.com/user-attachments/assets/9d350015-f844-4e35-ad69-ab1c39ac8a57)

**Comment by SiverDX** [comment]
I don't think anything can be done for lava, it just depends on the used shader and they config they provide
With some you can see a bit better with lava vision and with others it's just full of bloom and oversaturated effects and whatnot

**Comment by SiverDX** [comment]
Aside from lava (with certain shaders) thing should work correctly by now
