### ISSUE TITLE
[1.20.1 Bug]: game crashed while fighting monsters

### ISSUE THREAD

**Issue by FuryJack07** [DragonSurvivalTeam/DragonSurvival#632]
### ■ Your Discord ID or other contacts

FuryJack07#4376 on discord

### ■ Dragon Survival version

DragonSurvival-1.20.1-18.07.2024

### ■ Forge/Neoforge version

Forge 47.3.5

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I was fightning some drowned, as sea dragons often have to do, I used my lightning breath, once, then I was charging a ball of lightning and the game blew up. I don't have any other major mods installed, at least, none that should've been doing anything important at the moment, as I had just started the world

### ■ Crash Report File and Logs

https://pastebin.com/uaU0sJt3

**Comment by FuryJack07** [comment]
status effects that make the entity interact with other entities do seem pretty trigger happy with crashes, but this is the first one I actually decided to report, If I find more I'll report them too

**Comment by seelderr** [comment]
Very hard to figure out what happened here from the logs. Going to close as not planned unless more info comes up.
