### ISSUE TITLE
[1.19.2 Bug]: Save All Abilities and Save Growth Stage persist between worlds if using defaultconfigs

### ISSUE THREAD

**Issue by KJEntytek303** [DragonSurvivalTeam/DragonSurvival#635]
### ■ Your Discord ID or other contacts

kjentytek303

### ■ Dragon Survival version

1.19.2-18.07.2024

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

If Save All Abilities and/or Save Growth Stage are enabled in config, same save persist between singleplayer worlds, IE:
If on a creative world i set my size to cave dragon size 40, and unlock 4th level of the cave magic ability, then go create a survival world and change to cave dragon, i will have said abilities and growth size. I used defaultconfigs to copy custom server config to newly created worlds.

**Comment by seelderr** [comment]
Fixed in 1.21

**Comment by KJEntytek303** [comment]
Cool, when 1.19.2 fix?

**Comment by seelderr** [comment]
not planned
