### ISSUE TITLE
[1.19.2 Bug]: cant play minecraft with this mod

### ISSUE THREAD

**Issue by GODZILLA310** [DragonSurvivalTeam/DragonSurvival#636]
### ■ Your Discord ID or other contacts

teczalena@gmail.com

### ■ Dragon Survival version

DragonSurvival-1.19.2-02.03.2024_stable.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

when trying to play on 1.19.2 game crashes when launching tried literaly everything i was even trying on other versions of the mod but game freezes when trying to make a world or load one i dont know what to do help (yes i tried on diffrent versions of geckolib too)

### ■ Crash Report File and Logs

[crash-2024-08-10_18.32.58-client.txt](https://github.com/user-attachments/files/16570338/crash-2024-08-10_18.32.58-client.txt)
[latest.log](https://github.com/user-attachments/files/16570340/latest.log)

**Comment by KJEntytek303** [comment]
try updating the mod. Also in the crash log you provided i see that you didn't even had this mod in the "mods" folder, while also complaining about geckolib. latest.log says that you're missing the "geckolib" mod.

**Comment by GODZILLA310** [comment]
i have it but it some how doesnt work im using tlauncher

**Comment by GODZILLA310** [comment]
but i will try maybe this time i accidentaly got wrong geckolib

**Comment by GODZILLA310** [comment]
i put latest geckolib version now and still broken
[crash-2024-08-10_19.02.02-client.txt](https://github.com/user-attachments/files/16570363/crash-2024-08-10_19.02.02-client.txt)

**Comment by GODZILLA310** [comment]
[latest.log](https://github.com/user-attachments/files/16570365/latest.log)

**Comment by KJEntytek303** [comment]
update dragon survival

**Comment by GODZILLA310** [comment]
i added latest version of dragon survival and game freezes

**Comment by GODZILLA310** [comment]
i gave it full ram but still broken

**Comment by KJEntytek303** [comment]
Logs? Also giving the entire ram to mc is asking for kernel panic/system freeze.

**Comment by GODZILLA310** [comment]
my pc does not crash or freeze just game freezes when trying to create/load world
[crash-2024-08-10_19.44.57-server.txt](https://github.com/user-attachments/files/16570433/crash-2024-08-10_19.44.57-server.txt)
[latest.log](https://github.com/user-attachments/files/16570435/latest.log)

**Comment by GODZILLA310** [comment]
and then i just click  X  bc it just frozen

**Comment by KJEntytek303** [comment]
You're from poland, right? 

Caused by: java.nio.file.FileSystemException: C:\Users\Test\AppData\Roaming\.minecraft\versions\dragon test\saves\Nowy świat\serverconfig\dragonsurvival-server.toml: Nie można wykonać żądanej operacji na pliku z otwartą sekcją mapowania użytkownika

idk how to fix it, seems like broken WinDoS installation OR Kasperky Internet Security overreacting random things. Dragon Survival is unable to create server config file, and then crashes mc.

**Comment by GODZILLA310** [comment]
ok i think it can be it too thx

**Comment by GODZILLA310** [comment]
but i dont have kasperky internet security

**Comment by GODZILLA310** [comment]
i gave a log to chat gpt  and it says that im missing some mods.toml files

**Comment by GODZILLA310** [comment]
i have no idea how to download toml files

**Comment by GODZILLA310** [comment]
im too stupid to fix it

**Comment by KJEntytek303** [comment]
here is the config file you need taken from Play as Dragon Gothic Edition modpack, with my minimal changes to it, so it should be similar to vanilla DS (you can always revert the changes in the DS config GUI). Download it and change extension to ".toml" and it should work.

[dragonsurvival-server.txt](https://github.com/user-attachments/files/16570596/dragonsurvival-server.txt)
