### ISSUE TITLE
[1.20.1 Bug]: Flying speed continues accumulating while paused

### ISSUE THREAD

**Issue by molten-basalt** [DragonSurvivalTeam/DragonSurvival#637]
### ■ Your Discord ID or other contacts

`molten_basalt`

### ■ Dragon Survival version

`DragonSurvival-1.20.1-18.07.2024`

### ■ Forge/Neoforge version

`NeoForge 47.1.106`

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

If the game is paused while flying in elytra mode, and unpaused several seconds later, the player may be launched far towards flying direction.

https://github.com/user-attachments/assets/dc1ec4ba-0370-40c5-8b84-dcd6331560e5

**Comment by KJEntytek303** [comment]
According to GitHub, recording is damaged

**Comment by molten-basalt** [comment]
> According to GitHub, recording is damaged

I noticed that but not sure why, displays fine in Chromium but not Firefox.

**Comment by seelderr** [comment]
Fixed in fa8ae66b (1.21)
