### ISSUE TITLE
[1.19.2 Bug]: Altar usage cooldown does not tick

### ISSUE THREAD

**Issue by KJEntytek303** [DragonSurvivalTeam/DragonSurvival#638]
### ■ Your Discord ID or other contacts

kjentytek303

### ■ Dragon Survival version

1.19.2 - 18.07.2024_fix

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Bug is present in BOTH singleplayer and dedicated server.
If altar usage cooldown is >0, altar usage cooldown will not update. Reloading a singleplayer world seems to help, but then altar cooldown is set on whatever it was . This means:
-Altar usage cooldown will not tick, unless the world is reloaded.
-Altar usage cooldown will not update, event if the config change. 
-Dying (similar to other bugs i reported) seems to update the cooldown immediately. 

This is what i get on chat after clicking a dragon altar in 2-3 second intervals
![obraz](https://github.com/user-attachments/assets/512f91c9-226f-4995-9a55-058ecd0e9d17)

After using /kill, this is what i get on the altar
![obraz](https://github.com/user-attachments/assets/cc454ab7-de7e-4997-89a0-aca07a05b4fd)

After reloading a world, it updates again:
![obraz](https://github.com/user-attachments/assets/a948cadd-4910-44d6-a00f-33bf50713467)

Testing was done on a clear DS install, new world and mostly default configs, as altar usage cooldown was higher than 0.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/16573799/latest.log)

**Comment by seelderr** [comment]
Fixed in c5ac3621(1.21)
