### ISSUE TITLE
[1.19.2 Bug]: Server Crash, Ticking entity, entity.creatures.Shooter.performBolasThrow

### ISSUE THREAD

**Issue by KJEntytek303** [DragonSurvivalTeam/DragonSurvival#639]
### ■ Your Discord ID or other contacts

kjentytek303

### ■ Dragon Survival version

1.19.2 18.07.2024 fix

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

Crash when i'm in the same chunk as dragon hunters, likely same as this: https://github.com/DragonSurvivalTeam/DragonSurvival/issues/624, except it wasn't fixed in the newest version.

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/16573913/latest.log)

[crash-2024-08-11_16.03.26-server.txt](https://github.com/user-attachments/files/16573926/crash-2024-08-11_16.03.26-server.txt)

**Comment by Emberglow5000** [comment]
I am having this issue as well, same version, also on a dedicated server.

**Comment by seelderr** [comment]
this was fixed on 1.20 but not 1.19. fixed in b7b5f6a

**Comment by seelderr** [comment]
we'll post an official update with the fix in a bit
