### ISSUE TITLE
[1.18.2 Bug]: Vault hunters incompatabilty 

### ISSUE THREAD

**Issue by Neszumi** [DragonSurvivalTeam/DragonSurvival#647]
### ■ Your Discord ID

neszumiavali

### ■ Dragon Survival version

DragonSurvival-1.18.2-27.07.2024.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

not sure if this is the right place but, this mod does not work with Vault hunters 3rd Edition 
the mod it does not work with is "the_vault-1.18.2-3.15.1.3328.jar" I think 

### ■ Crash Report File and Logs

[latest.log](https://github.com/user-attachments/files/16596057/latest.log)

**Comment by Divism1234** [comment]
I have a version that works with Vault hunters, but swords don't work if they are in the dragon tool slot, this may go for other tools as well.
If you are still interested in it my discord id is divism13.
