### ISSUE TITLE
Opportunity to add an infinite number of dragon growth stages to the config.

### ISSUE THREAD

**Issue by BruteTigrex** [DragonSurvivalTeam/DragonSurvival#65]
You can give the opportunity to add an infinite number of stages for the dragon, which will change its size and other parameters: damage, HP, the amount of food that is required for it, the number of heart elements for the new stage.
For example
I don't like that the dragon has only three stages, so I'll just add a few stages to the config.
Of course you can optimize my idea for mod code

I, and not only me, will be very grateful to you for adding this function. (After all, the size of an adult dragon is really small)
I will be very happy if you add this to your to-do list.

**Comment by Claycorp** [comment]
Not sure why this was closed with no comment but the rewrite I have started on will allow for things like this.

**Comment by BlackAures1** [comment]
I don't want to turn bug tracking into a "suggestion and question section".
