### ISSUE TITLE
[1.20.1 Bug]: Ivy bug

### ISSUE THREAD

**Issue by IriDark** [DragonSurvivalTeam/DragonSurvival#654]
### ■ Your Discord ID or other contacts

iri_dark

### ■ Dragon Survival version

DragonSurvival-1.20.1-27.06.2024-all

### ■ Forge/Neoforge version

Forge 47.2.17

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Dragon starts flying on a ladder acting blocks like Ivy from Immersive Weathering, when shift key is down, most likely that's an issue of Immersive Weathing itself but idk

https://github.com/user-attachments/assets/b0be8e8a-f59a-4e23-9829-2180b1e51199

https://github.com/user-attachments/assets/e15117c5-b69e-4c1e-9ce7-f5364fb801af

**Comment by IriDark** [comment]
not something critical but anyway

**Comment by KJEntytek303** [comment]
Does the hitbox change? Cuz if yes you could use it to crawl through 2 tall tunnels as D60 (Dragon size 60, Adult 30) or similar, maybe D56, which would allow for some creative buildings. Also this would give me ideas on how to use it differently, if emotions didn't exist.

**Comment by IriDark** [comment]
> Does the hitbox change? Cuz if yes you could use it to crawl through 2 tall tunnels as D60 (Dragon size 60, Adult 30) or similar, maybe D56, which would allow for some creative buildings. Also this would give me ideas on how to use it differently, if emotions didn't exist.


https://github.com/user-attachments/assets/e7039d76-900c-4f64-b238-74f499a64680

**Comment by seelderr** [comment]
This is intended behavior, you have wings enabled and are technically not touching the ground when you are interacting with these type of blocks
