### ISSUE TITLE
[1.20.1 Bug]: Request for ability to use non-dragon foods normally, while still keeping the dragon food buffs

### ISSUE THREAD

**Issue by jcotton42** [DragonSurvivalTeam/DragonSurvival#655]
### ■ Your Discord ID or other contacts

jcotton42

### ■ Dragon Survival version

DragonSurvival-1.20.1-18.07.2024

### ■ Forge/Neoforge version

Forge 1.20.1-47.3.6

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I would like a "best of both worlds" food toggle, that both allows the dragon foods to have their dragon-specific buffs, while also not nerfing the non-dragon foods.

For example, with `dragonFoods = true`, a non-dragon food like an apple restores less for dragons than it would for humans. This can be resolved with `dragonFoods = false`, but that then makes the dragon foods apply the hunger effect to dragons.

I would like the ability for both, where dragons can eat "normal" foods while still having their own special foods.

I would be fine with this being pushed to the 1.21 version.

**Comment by seelderr** [comment]
This is fixed in 814095c3 with the new "requireDragonFood" config (if it is enabled, dragons can eat dragon and human food, but humans still can't eat dragon food)

**Comment by jcotton42** [comment]
Thanks!
