### ISSUE TITLE
[1.20.1 Bug]: Cave dragon 1 and 2 ability has no effect to some mobs.

### ISSUE THREAD

**Issue by kitstsu** [DragonSurvivalTeam/DragonSurvival#659]
### ■ Dragon Survival version

DragonSurvival-1.20.1-18.07.2024

### ■ Forge/Neoforge version

TLauncher 1.20.1 Forge.

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

It seems like cave dragon breath and fireball don't do any damage to some mobs. Tested on full grown dragons, creative and survival, single- and multiplayer. All the same.
1. Warden example. Breath has no effect and fireball just disappears when hits mob. Burning effect also doesn't work.
Bosses from other mods have same problems. Water and forest 1-2 abilities works fine.
2. Other mobs take damage and burn effect from cave dragon's abilities, but fireball still doesn't explode around. 
3. Hitting the ground both abilities work - burn all around and destroy blocks.

**Comment by BlackAures1** [comment]
Mobs with resistance to fire and explosions are resistant to fire and explosions :)
