### ISSUE TITLE
[1.20.1 Bug]: entity.dragon name tag bug

### ISSUE THREAD

**Issue by Amurkura** [DragonSurvivalTeam/DragonSurvival#666]
### ■ Your Discord ID or other contacts

amurkura@gmail.com

### ■ Dragon Survival version

DragonSurvival-1.20.1-18.07.2024.jar

### ■ Forge/Neoforge version

framework-forge-1.20.1-0.7.6.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I have read the wiki and have been playing the mod without problems but on one save the player dragon has a line of text floating over it that says "entity.dragonsurvival.dummy_dragon" that appears in first person and all third person views. It disappears at some camera angles but otherwise stays on screen. I had been playing that save for a couple of hours to generate chunks (chunk pregenerator mod) but the text did not appear until sometime after the chunk generation was finished.
Restart of the save and the game does not fix the problem.

**Comment by Amurkura** [comment]
The issue has not appeared on other saves.

**Comment by Amurkura** [comment]
Sorry new to github

**Comment by Amurkura** [comment]
Sorry new to github

**Comment by Amurkura** [comment]
Further update: dying did not fix the issue. The name tag appeared again underground

**Comment by seelderr** [comment]
Fixed in 1.21
