### ISSUE TITLE
[Play as Dragon]: if "glowing option is enabled in ANYTHING it causes pink squares to appear 

### ISSUE THREAD

**Issue by Siletohr** [DragonSurvivalTeam/DragonSurvival#675]
### ■ Your Discord ID

MiguelBat#8281

### ■ Modpack version

Non-official

### ■ Forge/Neoforge version

Neoforge - 21.0.167

### ■ Single game or server?

Single-player (Default)

### ■ Describe the problem

If the glowing option is enabled on anything it gives me pink squares all around the dragon
![imagem_2024-09-21_192414863](https://github.com/user-attachments/assets/3564dd41-eedc-43fd-bea9-0bac14f1d637)
 
if the image does not work tag me on the discord i guess '-'

**Comment by seelderr** [comment]
Fixed in 2.0.1
