### ISSUE TITLE
[1.19.2 Bug]: Tooltips for Bodytypes break

### ISSUE THREAD

**Issue by Charmanth** [DragonSurvivalTeam/DragonSurvival#686]
### ■ Your Discord ID or other contacts

Charmanth

### ■ Dragon Survival version

DragonSurvival-1.19.2-18.07.2024_fix.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Tried this in multiplayer on a server with way more mods, but with this super pared down pack I used to test a separate issue in my modpack, it's still present.  Basically, the tool tips that are supposed to show upon hovering for Body Types (Central, Northern, Eastern, Souther, Western), don't show.

The pared down pack is a fresh install, even, so I'm not sure what happened to the tool tips.  Unless one of the mods I was testing is the culprit for suppressing the tool tips.

I know they're supposed to show because I've seen them before, also other users in the discord showed that they show up for them.
![Screenshot 2024-10-22 203305](https://github.com/user-attachments/assets/15c8a986-9e23-4822-ba3e-7e3a87b7a9d4)
![2024-10-22_20 44 47](https://github.com/user-attachments/assets/c03ac0f7-061a-49ed-b61e-b2dccb59c15f)

**Comment by SiverDX** [comment]
Currently body tooltips are only implemented in 1.20+
Unsure if this will be brought to 1.19.2 as well

**Comment by Charmanth** [comment]
I'm confused, because I've seen screenshots of someone with 1.19.2 showing the tooltips.   You can find the screenshots in the discord, [https://discord.com/channels/486465167572336641/834003404711133204/1298218194691166230](here: https://discord.com/channels/486465167572336641/834003404711133204/1298218194691166230).  

This was even before the 1.20.1 branch got the tooltips enabled according to timestamps and github.

**Comment by SiverDX** [comment]
Fixed in `1.19.2-16.11.2024`
