### ISSUE TITLE
[1.20.1 Bug]: Altar's cooldown freeze on server

### ISSUE THREAD

**Issue by HarrMegiddon** [DragonSurvivalTeam/DragonSurvival#696]
### ■ Dragon Survival version

dragonsurvival-1.20.1-24.10.2024-all

### ■ Forge/Neoforge version

Forge 1.20.1 4735

### ■ Single game or server?

Self-made dedicated server

### ■ Describe the bug

Since this newest edition making Dragon Altar having internal 5 minuets cooldown (which means unable to be changed by dragonsurvival-server.toml even I set the cooldown to 0),  while I had interacted with the Dragon Altar, it's time countdown freeze to 5 minuets without decreasing. This problem didn't appear in single-player.  It keeps frozen after suicide or server reboot.

**Comment by AzaleaFlame59** [comment]
I too have this problem. Forge 47.3.0, Minecraft 1.20.1, self-made & run server, config says 0 second cooldown, even setting to like 5sec does nothing (with full server reboot), waiting a few in game and real life days does nothing.
I personally found it to occur as I tried placing the altar in human form, right clicked it to attempt putting a torch on it, it brought up the gui so I hit ESC, crouched & placed torch, right clicking after that from then on gives me an Altar on Cooldown for 5 minutes thing.
Interestingly, atleast one of my players on my server has no issues accessing and re-accessing the altar. I am unable to go to another altar and use it, however the command (/dragon-altar) works fine.
Hope this helps, let me know if I can add any more information! :)

**Comment by SiverDX** [comment]
Can you test it with this version
The cooldown was hardcoded when using the altar block
I wasn't able to re-produce the initial reported issue about the cooldown being stuck (when on a server) though

[dragonsurvival-1.20.1-05.11.2024-all.zip](https://github.com/user-attachments/files/17630220/dragonsurvival-1.20.1-05.11.2024-all.zip)

**Comment by HarrMegiddon** [comment]
We skipped this bug with another way, using command block with: /execute as @p run dragon-altar

**Comment by AzaleaFlame59** [comment]
I tried the update on my server, and it still persists but now it gives me "Altar is on cooldown: 1" instead of 5m0s. I will note I did have my config set to 1 in an attempt to convince it to fix itself, but that did nothing, and I forgot to reset it to 0. I did change it back to 0, restarted the server, and it still says 1.

**Comment by HarrMegiddon** [comment]
The same as before, new edition (dragonsurvival-1.20.1-05.11.2024-all.jar) didn't solve the problem
![QQ图片20241108104544](https://github.com/user-attachments/assets/5ed39835-e05d-428e-b45a-1b02f6e107fd)

**Comment by SiverDX** [comment]
I think I see the issue
The cooldown doesn't go down at the moment if the config 'startWithDragonChoice' is set to 'false'

**Comment by HarrMegiddon** [comment]
Strange bug, cute but a little annoying, but taught me how to use command block.

**Comment by HarrMegiddon** [comment]
Maybe its sort of a punishment for the server that refusing the first turning dragon power. :P

**Comment by SiverDX** [comment]
Should work with this one

[dragonsurvival-1.20.1-08.11.2024-all.zip](https://github.com/user-attachments/files/17674707/dragonsurvival-1.20.1-08.11.2024-all.zip)

**Comment by gamerpotion** [comment]
> Should work with this one
> 
> ~[dragonsurvival-1.20.1-08.11.2024-all.zip](https://github.com/user-attachments/files/17674707/dragonsurvival-1.20.1-08.11.2024-all.zip)~ (this one had a wrong check leading to the start choice potentially not showing up)
> 
> [dragonsurvival-1.20.1-08.11.2024-all.zip](https://github.com/user-attachments/files/17674819/dragonsurvival-1.20.1-08.11.2024-all.zip)

Recently added this mod to my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg-forge
had the same issue on servers.
testing dragonsurvival-1.20.1-08.11.2024-all.zip on a server, altars now work and not stuck on 5mins, but there is no cooldown at all now. Is that meant to happen?

**Comment by SiverDX** [comment]
> > Should work with this one
> > ~[dragonsurvival-1.20.1-08.11.2024-all.zip](https://github.com/user-attachments/files/17674707/dragonsurvival-1.20.1-08.11.2024-all.zip)~ (this one had a wrong check leading to the start choice potentially not showing up)
> > [dragonsurvival-1.20.1-08.11.2024-all.zip](https://github.com/user-attachments/files/17674819/dragonsurvival-1.20.1-08.11.2024-all.zip)
> 
> Recently added this mod to my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg-forge had the same issue on servers. testing dragonsurvival-1.20.1-08.11.2024-all.zip on a server, altars now work and not stuck on 5mins, but there is no cooldown at all now. Is that meant to happen?

are you sure your config has a cooldown? i think the default is 0

**Comment by SiverDX** [comment]
Fixed in `1.20.1-16.11.2024`
