### ISSUE TITLE
[1.20.1 Bug]: Placing big dragon doors on snow layers causes them to get instantly destroyed.

### ISSUE THREAD

**Issue by KJEntytek303** [DragonSurvivalTeam/DragonSurvival#705]
### ■ Your Discord ID or other contacts

KJEntytek303

### ■ Dragon Survival version

Compilation from source code, at 14.11.2024, after this patch: https://github.com/DragonSurvivalTeam/DragonSurvival/commit/1785496b87816606cfd3fbb49f14e3e3ca059a0e

### ■ Forge/Neoforge version

Neoforge 47.1.106

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Place a grass block or mycelium
Place 1 snow layer on it
Place any big dragon door on the snow layer
The door will get instantly destroyed.

Doors do not get duped, they drop normally.

**Comment by SiverDX** [comment]
Fixed in `1.20.1-16.11.2024`
