### ISSUE TITLE
Tooltips won't show

### ISSUE THREAD

**Issue by Wakatsu** [DragonSurvivalTeam/DragonSurvival#78]
Pretty much what it says on the label - with DragonSurvival mod present, items won't display tooltips when hovered over with mouse cursor, not just for draconic players, but for everyone on the server.

My server mods load:
https://i.imgur.com/IagPysO.png

Дублирую на русском на всякий пожарный:
При наличии мода в загрузке у всего сервера перестают отображаться информационные окошки (окошки с именами вещей, параметрами брони и проч), независимо от того, играет ли игрок за дракона или человека. По ссылке список установленных модов (кроме DragonSurvival).

**Comment by BlackAures1** [comment]
Have you figured out which mod the conflict is with? If not, I'm closing this thread.

**Comment by Horeak** [comment]
With the newest version there is now a config to disable all tooltip changes DS makes so if it was caused by DS then that should solve it.
