### ISSUE TITLE
Cannot see breath.

### ISSUE THREAD

**Issue by NotAPotter** [DragonSurvivalTeam/DragonSurvival#80]
I have not been able to see the breath weapons of any dragon for a few versions now. I get some visual indication they're working and there(fires, status effects), but I can never actually see it in front of the dragon. I am a patron and have been using some of the exclusive builds, if that helps at all.

**Comment by Horeak** [comment]
The breath visuals are particles, so what is your particles setting set to under video settings? Turning it to the lowest will result in the breaths not showing.

**Comment by NotAPotter** [comment]
Ah, it's usually on low. Turning it to medium seems to solve it. Thank you.
