### ISSUE TITLE
Freeze on server standup, Flight Update

### ISSUE THREAD

**Issue by Wakatsu** [DragonSurvivalTeam/DragonSurvival#81]
Server freezes dead when starting a new world (immediately after hitting the button and before the animated sequence starts playing)
Attaching crash log, says something about food, would be glad if you could help pinpoint the mod it conflicts with. This issue is new, tho, server worked just fine before the Flight Update with the same exact mods present
[crash-2021-12-26_16.20.46-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/7776657/crash-2021-12-26_16.20.46-server.txt)
.

**Comment by BlackAures1** [comment]
This has already been fixed. It will be in the next patch. For now, bring back the custom food in the config.
