### ISSUE TITLE
Trade menu's for Princes and Princesses close immediately after interacting with them.

### ISSUE THREAD

**Issue by Smokeymaxamus** [DragonSurvivalTeam/DragonSurvival#82]
Right click and it closes immediately can see it for a split second.
Running a big mod pack gonna start just deleting mods one by one til I CAN see the inventory in a test world.
Then try with just the last one before it worked deleted.
I'll let you know the results eventually having to reload each time a mod is removed takes time.
I googled the problem to see if happened in the past with other various mods.
All I could find was some stuff about 1.14 version stock Minecraft bugs.

**Comment by BlackAures1** [comment]
In vanilla mc and us on modpack everything works fine. Check also trade with other mod dwellers, if any, and with regular villagers/dwellers.

**Comment by Smokeymaxamus** [comment]
Other normal villagers and some mod added ones work, haven't checked ALL the other mod added ones but several do work as intended. rats-plague doctor, fey wild-dwarves, more villagers-new custom villagers, vanilla- stock villagers.

**Comment by Smokeymaxamus** [comment]
As I delete mods I found what ever it is that is affecting them sticks to them.
I can place a new prince/princess and can trade with them and still cant trade with the old one.

**Comment by Smokeymaxamus** [comment]
The one you can trade with it labeled nitwit and the one you can not is unemployed.
The unemployed status is reapplied to prior nitwits when the mod is reactivated, but not removed when it is disabled.
I'm getting closer.

**Comment by Smokeymaxamus** [comment]
They wont "attach" to a village or gain a job.

**Comment by BlackAures1** [comment]
Does it work for you in pure minecraft + DS + Geckolib?

**Comment by Smokeymaxamus** [comment]
It worked with a bunch of mods about half of the 300+ I have

**Comment by Smokeymaxamus** [comment]
Or do you mean "contaminate" one and then strip the pack down to just those 2 mods?

**Comment by BlackAures1** [comment]
I mean pure minecraft + 2 mods. Not 300.

**Comment by Smokeymaxamus** [comment]
he Charm Reforged mod removes nitwits, which the princes and princesses are flagged as making them into unemployed villagers. which breaks trading. turning (#When any action would cause a villager to become a nitwit, it becomes an unemployed villager instead. "RemoveNitwits enabled" = true) to false fixes it, But now you have nitwits in villages again, so a minor incapability.

**Comment by BlackAures1** [comment]
Thanks for the information!

**Comment by Horeak** [comment]
There is a possible fix for this issue coming in the next version.

**Comment by BlackAures1** [comment]
Has the new update solved your problem?
