### ISSUE TITLE
Firebreath doesn't have a config in the server config like Forestbreath/Stormbreath

### ISSUE THREAD

**Issue by Smokeymaxamus** [DragonSurvivalTeam/DragonSurvival#84]
In the Ds 0.7 version.
Not sure if this is intentional or not, if the config existed it would look something like this I'd imagine.

#The amount of damage the firebreath ability deals. This value is multiplied by the skill level.
					#Range: 0.0 ~ 100.0
					firebreathDamage = 2.0

**Comment by BlackAures1** [comment]
Take a closer look. All damage settings are available for all breath types.

**Comment by Smokeymaxamus** [comment]
I'll delete the config and have it regenerate it and check again. This is with ONLY ds 0.7 and the geckolib installed.

**Comment by Smokeymaxamus** [comment]
Here is the brand new server setting file which has the other two breath damage values but not fire, had to change the file extension to .txt vice .toml since its not supported by Github. 

[dragonsurvival-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/7798776/dragonsurvival-server.txt)

Can I just manually add it?

**Comment by BlackAures1** [comment]
closer look
![image](https://user-images.githubusercontent.com/43911230/147870033-c6d241ea-35f9-4993-bf06-bd7448d1e09b.png)
![image](https://user-images.githubusercontent.com/43911230/147870054-78a0a283-b631-4b00-a97b-a076afbd0a8b.png)
![image](https://user-images.githubusercontent.com/43911230/147870063-70be4cc7-9a35-4eee-acb1-b8c99cc828e5.png)

**Comment by BlackAures1** [comment]
Yes, you're right. There is no damage from fire. We will try to add it in the next patch.

**Comment by Horeak** [comment]
Fixed in the next version.
