### ISSUE TITLE
Bug in multiplayer game

### ISSUE THREAD

**Issue by DragonIlyxa** [DragonSurvivalTeam/DragonSurvival#90]
Hello, I apologize for the trivial concerns, but I have a question. After installing the mod version - DragonSurvival_TreasureUpdate 0.8, I went into the world to play with friends over the network in modpack. And we noticed an interesting bug - when the host chooses the type of dragon, the rest of the players who are still human have the dragon's diet chosen by the host. We checked this bug in the modpack and separately, the result is the same. Thanks in advance for your reply.

**Comment by DragonIlyxa** [comment]
Могу ли я писать на русском здесь?

**Comment by Horeak** [comment]
I am having issues trying to reproduce this issue, do you have some more specifics? Like what issues are you facing specifically, are you getting the hunger effects from items, are you able to eat items you arent supposed to?

**Comment by DragonIlyxa** [comment]
First thing first, i am apologising for the mistakes, I write with the translator. When I create a local server and turn into a dragon, my friends playing as humans, when they eat ordinary human food, get the "Hunger". I think the dragon host's diet is expanding onto human players.

**Comment by Horeak** [comment]
Found a possible fix for this issue, will be up to @BlackAures1 when a version with the fix is released though.

**Comment by DragonIlyxa** [comment]
Thanks. I'll be waiting)
