### ISSUE TITLE
Mod incapability

### ISSUE THREAD

**Issue by kabadath** [DragonSurvivalTeam/DragonSurvival#94]
Hello, I have an issue, when starting the game with the DragonSurvival 0.9 and Cyclic mod, the game is crashing. The same problem is spotted with the TConstruct mod, it were quietly launched on the previous patch.

**Comment by BlackAures1** [comment]
Send a crashlog

**Comment by kabadath** [comment]
> Send a crashlog

Прощу, прощения, файл с модом был немного повреждён при загрузке, и конкретно с этими двумя модами, он крашился при загрузке, сейчас, после переустановки мода, проблема решена
